// Code generated by mockery v2.46.3. DO NOT EDIT.

package intel_dlb

import mock "github.com/stretchr/testify/mock"

// mockRasReader is an autogenerated mock type for the rasReader type
type mockRasReader struct {
	mock.Mock
}

// gatherPaths provides a mock function with given fields: path
func (_m *mockRasReader) gatherPaths(path string) ([]string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for gatherPaths")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// readFromFile provides a mock function with given fields: filePath
func (_m *mockRasReader) readFromFile(filePath string) ([]byte, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for readFromFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockRasReader creates a new instance of mockRasReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRasReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRasReader {
	mock := &mockRasReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
