# Configuration for the Kafka server to send metrics to
[[outputs.kafka]]
  ## URLs of kafka brokers
  brokers = ["localhost:9092"]

  ## Kafka topic for producer messages
  topic = "telegraf"

  ## Optional TLS Config
  ca = "../../testutil/pki/cacert.pem"
  certificate = "../../testutil/pki/clientcert.pem"
  key = "../../testutil/pki/clientkey.pem"

  ## Data format to output.
  data_format = "influx"
