# Parse the new lines appended to a file
[[inputs.tail]]
  files = ["/var/mymetrics.out"]

  ## Keep the default behavior using the deprecated option
  initial_read_offset = "saved-or-end"

  data_format = "influx"
