// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/pfe_ifl_oc/pfe_ifl_oc.proto

package pfe_ifl_oc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InterfacesPfeIfl struct {
	Interface            []*InterfacesPfeIflInterfaceList `protobuf:"bytes,151,rep,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InterfacesPfeIfl) Reset()         { *m = InterfacesPfeIfl{} }
func (m *InterfacesPfeIfl) String() string { return proto.CompactTextString(m) }
func (*InterfacesPfeIfl) ProtoMessage()    {}
func (*InterfacesPfeIfl) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0}
}
func (m *InterfacesPfeIfl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIfl.Unmarshal(m, b)
}
func (m *InterfacesPfeIfl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIfl.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIfl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIfl.Merge(dst, src)
}
func (m *InterfacesPfeIfl) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIfl.Size(m)
}
func (m *InterfacesPfeIfl) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIfl.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIfl proto.InternalMessageInfo

func (m *InterfacesPfeIfl) GetInterface() []*InterfacesPfeIflInterfaceList {
	if m != nil {
		return m.Interface
	}
	return nil
}

type InterfacesPfeIflInterfaceList struct {
	Subinterfaces        *InterfacesPfeIflInterfaceListSubinterfacesType `protobuf:"bytes,151,opt,name=subinterfaces" json:"subinterfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *InterfacesPfeIflInterfaceList) Reset()         { *m = InterfacesPfeIflInterfaceList{} }
func (m *InterfacesPfeIflInterfaceList) String() string { return proto.CompactTextString(m) }
func (*InterfacesPfeIflInterfaceList) ProtoMessage()    {}
func (*InterfacesPfeIflInterfaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0, 0}
}
func (m *InterfacesPfeIflInterfaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIflInterfaceList.Unmarshal(m, b)
}
func (m *InterfacesPfeIflInterfaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIflInterfaceList.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIflInterfaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIflInterfaceList.Merge(dst, src)
}
func (m *InterfacesPfeIflInterfaceList) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIflInterfaceList.Size(m)
}
func (m *InterfacesPfeIflInterfaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIflInterfaceList.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIflInterfaceList proto.InternalMessageInfo

func (m *InterfacesPfeIflInterfaceList) GetSubinterfaces() *InterfacesPfeIflInterfaceListSubinterfacesType {
	if m != nil {
		return m.Subinterfaces
	}
	return nil
}

type InterfacesPfeIflInterfaceListSubinterfacesType struct {
	Subinterface         []*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList `protobuf:"bytes,51,rep,name=subinterface" json:"subinterface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                          `json:"-"`
	XXX_unrecognized     []byte                                                            `json:"-"`
	XXX_sizecache        int32                                                             `json:"-"`
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesType) Reset() {
	*m = InterfacesPfeIflInterfaceListSubinterfacesType{}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesType) String() string {
	return proto.CompactTextString(m)
}
func (*InterfacesPfeIflInterfaceListSubinterfacesType) ProtoMessage() {}
func (*InterfacesPfeIflInterfaceListSubinterfacesType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0, 0, 0}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType.Unmarshal(m, b)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIflInterfaceListSubinterfacesType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType.Merge(dst, src)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesType) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType.Size(m)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesType proto.InternalMessageInfo

func (m *InterfacesPfeIflInterfaceListSubinterfacesType) GetSubinterface() []*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList {
	if m != nil {
		return m.Subinterface
	}
	return nil
}

type InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList struct {
	State                *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                 `json:"-"`
	XXX_unrecognized     []byte                                                                   `json:"-"`
	XXX_sizecache        int32                                                                    `json:"-"`
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) Reset() {
	*m = InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList{}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) String() string {
	return proto.CompactTextString(m)
}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) ProtoMessage() {}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0, 0, 0, 0}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList.Unmarshal(m, b)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList.Merge(dst, src)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList.Size(m)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList proto.InternalMessageInfo

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList) GetState() *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType {
	if m != nil {
		return m.State
	}
	return nil
}

type InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType struct {
	Counters             *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType `protobuf:"bytes,151,opt,name=counters" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                             `json:"-"`
	XXX_unrecognized     []byte                                                                               `json:"-"`
	XXX_sizecache        int32                                                                                `json:"-"`
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) Reset() {
	*m = InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType{}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) String() string {
	return proto.CompactTextString(m)
}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) ProtoMessage() {}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0, 0, 0, 0, 0}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType.Unmarshal(m, b)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType.Merge(dst, src)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType.Size(m)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType proto.InternalMessageInfo

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType) GetCounters() *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType {
	if m != nil {
		return m.Counters
	}
	return nil
}

type InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType struct {
	InOctets             *uint64  `protobuf:"varint,51,opt,name=in_octets,json=inOctets" json:"in_octets,omitempty"`
	InUnicastPkts        *uint64  `protobuf:"varint,52,opt,name=in_unicast_pkts,json=inUnicastPkts" json:"in_unicast_pkts,omitempty"`
	InBroadcastPkts      *uint64  `protobuf:"varint,53,opt,name=in_broadcast_pkts,json=inBroadcastPkts" json:"in_broadcast_pkts,omitempty"`
	InMulticastPkts      *uint64  `protobuf:"varint,54,opt,name=in_multicast_pkts,json=inMulticastPkts" json:"in_multicast_pkts,omitempty"`
	InDiscards           *uint64  `protobuf:"varint,55,opt,name=in_discards,json=inDiscards" json:"in_discards,omitempty"`
	InErrors             *uint64  `protobuf:"varint,56,opt,name=in_errors,json=inErrors" json:"in_errors,omitempty"`
	InUnknownProtos      *uint32  `protobuf:"varint,57,opt,name=in_unknown_protos,json=inUnknownProtos" json:"in_unknown_protos,omitempty"`
	OutOctets            *uint64  `protobuf:"varint,58,opt,name=out_octets,json=outOctets" json:"out_octets,omitempty"`
	OutUnicastPkts       *uint64  `protobuf:"varint,59,opt,name=out_unicast_pkts,json=outUnicastPkts" json:"out_unicast_pkts,omitempty"`
	OutBroadcastPkts     *uint64  `protobuf:"varint,60,opt,name=out_broadcast_pkts,json=outBroadcastPkts" json:"out_broadcast_pkts,omitempty"`
	OutMulticastPkts     *uint64  `protobuf:"varint,61,opt,name=out_multicast_pkts,json=outMulticastPkts" json:"out_multicast_pkts,omitempty"`
	OutDiscards          *uint64  `protobuf:"varint,62,opt,name=out_discards,json=outDiscards" json:"out_discards,omitempty"`
	OutErrors            *uint64  `protobuf:"varint,63,opt,name=out_errors,json=outErrors" json:"out_errors,omitempty"`
	LastClear            *string  `protobuf:"bytes,64,opt,name=last_clear,json=lastClear" json:"last_clear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) Reset() {
	*m = InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType{}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) String() string {
	return proto.CompactTextString(m)
}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) ProtoMessage() {
}
func (*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_ifl_oc_1cec2f093bed3330, []int{0, 0, 0, 0, 0, 0}
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType.Unmarshal(m, b)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType.Marshal(b, m, deterministic)
}
func (dst *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType.Merge(dst, src)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) XXX_Size() int {
	return xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType.Size(m)
}
func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType proto.InternalMessageInfo

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInOctets() uint64 {
	if m != nil && m.InOctets != nil {
		return *m.InOctets
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInUnicastPkts() uint64 {
	if m != nil && m.InUnicastPkts != nil {
		return *m.InUnicastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInBroadcastPkts() uint64 {
	if m != nil && m.InBroadcastPkts != nil {
		return *m.InBroadcastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInMulticastPkts() uint64 {
	if m != nil && m.InMulticastPkts != nil {
		return *m.InMulticastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInDiscards() uint64 {
	if m != nil && m.InDiscards != nil {
		return *m.InDiscards
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInErrors() uint64 {
	if m != nil && m.InErrors != nil {
		return *m.InErrors
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetInUnknownProtos() uint32 {
	if m != nil && m.InUnknownProtos != nil {
		return *m.InUnknownProtos
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutOctets() uint64 {
	if m != nil && m.OutOctets != nil {
		return *m.OutOctets
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutUnicastPkts() uint64 {
	if m != nil && m.OutUnicastPkts != nil {
		return *m.OutUnicastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutBroadcastPkts() uint64 {
	if m != nil && m.OutBroadcastPkts != nil {
		return *m.OutBroadcastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutMulticastPkts() uint64 {
	if m != nil && m.OutMulticastPkts != nil {
		return *m.OutMulticastPkts
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutDiscards() uint64 {
	if m != nil && m.OutDiscards != nil {
		return *m.OutDiscards
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetOutErrors() uint64 {
	if m != nil && m.OutErrors != nil {
		return *m.OutErrors
	}
	return 0
}

func (m *InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType) GetLastClear() string {
	if m != nil && m.LastClear != nil {
		return *m.LastClear
	}
	return ""
}

var E_JnprInterfacesPfeIflExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*InterfacesPfeIfl)(nil),
	Field:         58,
	Name:          "jnpr_interfaces_pfe_ifl_ext",
	Tag:           "bytes,58,opt,name=jnpr_interfaces_pfe_ifl_ext,json=jnprInterfacesPfeIflExt",
	Filename:      "plugins/parsers/jtinative/pfe_ifl_oc/pfe_ifl_oc.proto",
}

func init() {
	proto.RegisterType((*InterfacesPfeIfl)(nil), "interfaces_pfe_ifl")
	proto.RegisterType((*InterfacesPfeIflInterfaceList)(nil), "interfaces_pfe_ifl.interface_list")
	proto.RegisterType((*InterfacesPfeIflInterfaceListSubinterfacesType)(nil), "interfaces_pfe_ifl.interface_list.subinterfaces_type")
	proto.RegisterType((*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceList)(nil), "interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list")
	proto.RegisterType((*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateType)(nil), "interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type")
	proto.RegisterType((*InterfacesPfeIflInterfaceListSubinterfacesTypeSubinterfaceListStateTypeCountersType)(nil), "interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type.counters_type")
	proto.RegisterExtension(E_JnprInterfacesPfeIflExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/pfe_ifl_oc/pfe_ifl_oc.proto", fileDescriptor_pfe_ifl_oc_1cec2f093bed3330)
}

var fileDescriptor_pfe_ifl_oc_1cec2f093bed3330 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4b, 0x6f, 0x13, 0x31,
	0x14, 0x85, 0x15, 0xd1, 0x42, 0x72, 0xd3, 0xb4, 0xd4, 0x5d, 0x74, 0x34, 0x55, 0x45, 0xe8, 0x02,
	0x8d, 0x10, 0x9a, 0x48, 0x2d, 0xe1, 0x11, 0xde, 0x8f, 0x0a, 0x15, 0x09, 0x88, 0x06, 0x75, 0x87,
	0x64, 0xa6, 0x13, 0x07, 0x39, 0x99, 0xda, 0x23, 0xfb, 0x9a, 0xb6, 0x0b, 0x7e, 0x07, 0x1b, 0x16,
	0xac, 0x61, 0xc1, 0xff, 0x63, 0x85, 0xec, 0x79, 0x24, 0xd3, 0x20, 0x21, 0xa1, 0xee, 0x32, 0xc7,
	0x9f, 0xcf, 0xf1, 0x3d, 0xba, 0x81, 0x7e, 0x96, 0x9a, 0x4f, 0x5c, 0xe8, 0x5e, 0x16, 0x2b, 0xcd,
	0x94, 0xee, 0x4d, 0x90, 0x8b, 0x18, 0xf9, 0x67, 0xd6, 0xcb, 0xc6, 0x8c, 0xf2, 0x71, 0x4a, 0x65,
	0x32, 0xf7, 0x33, 0xcc, 0x94, 0x44, 0xe9, 0x6f, 0x20, 0x4b, 0xd9, 0x31, 0x43, 0x75, 0x46, 0x51,
	0x66, 0xb9, 0xb8, 0xf3, 0xbb, 0x09, 0x84, 0x0b, 0x64, 0x6a, 0x1c, 0x27, 0x4c, 0xd3, 0xe2, 0x12,
	0x79, 0x06, 0xad, 0x4a, 0xf5, 0xbe, 0x36, 0xba, 0x97, 0x82, 0xf6, 0xee, 0x4e, 0xb8, 0x08, 0xce,
	0x24, 0x9a, 0x72, 0x8d, 0xd1, 0xec, 0x96, 0xff, 0xbd, 0x09, 0xab, 0xf5, 0x53, 0xf2, 0x01, 0x3a,
	0xda, 0x1c, 0xcd, 0x5c, 0xac, 0x73, 0x23, 0x68, 0xef, 0xf6, 0xff, 0xed, 0x1c, 0xd6, 0x2e, 0x52,
	0x3c, 0xcb, 0x58, 0x54, 0x37, 0xf3, 0x7f, 0x5d, 0x01, 0xb2, 0x48, 0x91, 0x29, 0xac, 0xcc, 0xab,
	0xde, 0x9e, 0x1b, 0xe6, 0xd5, 0x7f, 0x45, 0xd6, 0xa4, 0x7c, 0xe2, 0x9a, 0xb9, 0xff, 0xf3, 0x32,
	0xac, 0x2f, 0x30, 0x84, 0xc3, 0xb2, 0xc6, 0x18, 0x59, 0x39, 0x6f, 0x74, 0x41, 0xe1, 0xa1, 0x73,
	0xcd, 0xcb, 0xc8, 0x13, 0xfc, 0x1f, 0xcb, 0x00, 0x33, 0x95, 0x7c, 0x81, 0x66, 0x22, 0x8d, 0xbd,
	0x54, 0x95, 0xfd, 0xf1, 0xe2, 0xc3, 0xc3, 0x32, 0x23, 0x7f, 0x4a, 0x15, 0xe9, 0x7f, 0x5b, 0x82,
	0x4e, 0xed, 0x8c, 0x6c, 0xd9, 0xc5, 0xa2, 0x32, 0x41, 0x86, 0xda, 0xdb, 0xeb, 0x36, 0x82, 0xa5,
	0xa8, 0xc9, 0xc5, 0x3b, 0xf7, 0x4d, 0x6e, 0xc0, 0x1a, 0x17, 0xd4, 0x08, 0x9e, 0xc4, 0x1a, 0x69,
	0x36, 0x45, 0xed, 0xdd, 0x76, 0x48, 0x87, 0x8b, 0xc3, 0x5c, 0x1d, 0x4e, 0x51, 0x93, 0x9b, 0xb0,
	0xce, 0x05, 0x3d, 0x52, 0x32, 0x1e, 0xcd, 0xc8, 0xbe, 0x23, 0xd7, 0xb8, 0x78, 0x5e, 0xea, 0x73,
	0xec, 0xb1, 0x49, 0x71, 0xce, 0xf5, 0x4e, 0xc9, 0xbe, 0x29, 0x75, 0xc7, 0x5e, 0x83, 0x36, 0x17,
	0x74, 0xc4, 0x75, 0x12, 0xab, 0x91, 0xf6, 0xee, 0x3a, 0x0a, 0xb8, 0x78, 0x59, 0x28, 0xc5, 0xeb,
	0x99, 0x52, 0x52, 0x69, 0xef, 0x5e, 0xf9, 0xfa, 0x7d, 0xf7, 0x5d, 0x24, 0x19, 0x31, 0x15, 0xf2,
	0x44, 0x50, 0xf7, 0xf7, 0xd2, 0xde, 0xfd, 0x6e, 0x23, 0xe8, 0xd8, 0xa4, 0xc3, 0x5c, 0x1f, 0x3a,
	0x99, 0x6c, 0x03, 0x48, 0x83, 0x65, 0x0f, 0x03, 0xe7, 0xd4, 0x92, 0x06, 0x8b, 0x22, 0x02, 0xb8,
	0x6a, 0x8f, 0x6b, 0x4d, 0x3c, 0x70, 0xd0, 0xaa, 0x34, 0x38, 0x5f, 0xc5, 0x2d, 0x20, 0x96, 0x3c,
	0xd7, 0xc5, 0x43, 0xc7, 0x5a, 0x8f, 0x7a, 0x19, 0x05, 0x7d, 0xae, 0x8d, 0x47, 0x15, 0x5d, 0xaf,
	0xe3, 0x3a, 0xac, 0x58, 0xba, 0xea, 0xe3, 0xb1, 0xe3, 0xda, 0xd2, 0x60, 0x55, 0x48, 0x31, 0x47,
	0xd1, 0xc8, 0x93, 0x6a, 0x8e, 0xa2, 0x92, 0x6d, 0x80, 0xd4, 0xc6, 0x24, 0x29, 0x8b, 0x95, 0xf7,
	0xb4, 0xdb, 0x08, 0x5a, 0x51, 0xcb, 0x2a, 0x2f, 0xac, 0x30, 0x98, 0xc0, 0xd6, 0x44, 0x64, 0x8a,
	0x2e, 0x2e, 0x24, 0x65, 0xa7, 0x48, 0x36, 0xc3, 0xd7, 0x46, 0xf0, 0x8c, 0xa9, 0xb7, 0x0c, 0x4f,
	0xa4, 0x9a, 0xea, 0xf7, 0x4c, 0x68, 0x9b, 0x33, 0x70, 0x8b, 0xbc, 0xf1, 0x97, 0x45, 0x8e, 0x36,
	0xad, 0xe1, 0x41, 0xa5, 0x0f, 0xc7, 0xec, 0x60, 0x9c, 0xee, 0x9f, 0xe2, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0x89, 0x42, 0x49, 0x35, 0x05, 0x00, 0x00,
}
