[agent]
  interval = "2s"
  flush_interval = "3s"

[[inputs.http_listener_v2]]
  service_address = ":9888"
  # path = "/prometheus.metrics.container"
  path_tag = "path"
  data_format = "prometheusremotewrite"
  paths = ["/prometheus.metrics.controller-manager", "/prometheus.metrics.scheduler", "/prometheus.metrics.apiserver", "/prometheus.metrics.kubelet", "/prometheus.metrics.container", "/prometheus.metrics.container", "/prometheus.metrics.node", "/prometheus.metrics.operator.rule", "/prometheus.metrics", "/prometheus.metrics.control-plane.coredns", "/prometheus.metrics.control-plane.kube-etcd", "/prometheus.metrics.applications.nginx-ingress", "/prometheus.metrics.applications.nginx", "/prometheus.metrics.applications.redis", "/prometheus.metrics.applications.jmx", "/prometheus.metrics.applications.kafka", "/prometheus.metrics.applications.mysql", "/prometheus.metrics.applications.postgresql", "/prometheus.metrics.applications.apache"]

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "prometheus"
