package netflow

import (
	"log"
)

type Application struct {
	Name string
	Desc string
}

type ApplicationReadOp struct {
	Key  string
	Resp chan Application
	Fail chan bool
}

func (n *Netflow) applicationPoller() error {
	defer n.wg.Done()
	var applicationTable = map[string]Application{
		"1:8":     {"egp", "Exterior Gateway Protocol"},
		"1:47":    {"gre", "General Routing Encapsulation"},
		"1:1":     {"icmp", "Internet Control Message Protocol"},
		"1:88":    {"eigrp", "Enhanced Interior Gateway Routing Protocol"},
		"1:4":     {"ipinip", "IP in IP"},
		"1:89":    {"ospf", "Open Shortest Path First"},
		"1:115":   {"l2tp", "Layer 2 Tunneling Protocol"},
		"1:46":    {"rsvp", "Resource Reservation Protocol"},
		"1:0":     {"hopopt", "DEPRECATED, traffic will not match"},
		"1:3":     {"ggp", "Gateway-to-Gateway"},
		"1:5":     {"st", "Stream"},
		"1:7":     {"cbt", "CBT"},
		"1:9":     {"igrp", "Cisco interior gateway"},
		"1:10":    {"bbnrccmon", "BBN RCC Monitoring"},
		"1:11":    {"nvp-ii", "Network Voice Protocol"},
		"1:12":    {"pup", "PUP"},
		"1:13":    {"argus", "ARGUS"},
		"1:14":    {"emcon", "EMCON"},
		"1:15":    {"xnet", "Cross Net Debugger"},
		"1:16":    {"chaos", "Chaos"},
		"1:18":    {"mux", "Multiplexing"},
		"1:19":    {"dcn-meas", "DCN Measurement Subsystems"},
		"1:20":    {"hmp", "Host Monitoring"},
		"1:21":    {"prm", "Packet Radio Measurement"},
		"1:22":    {"xns-idp", "XEROX NS IDP"},
		"1:23":    {"trunk-1", "Trunk-1"},
		"1:24":    {"trunk-2", "Trunk-2"},
		"1:25":    {"leaf-1", "Leaf-1"},
		"1:26":    {"leaf-2", "Leaf-2"},
		"1:27":    {"rdp", "Reliable Data Protocol"},
		"1:28":    {"irtp", "Internet Reliable Transaction"},
		"1:29":    {"iso-tp4", "ISO Transport Protocol Class 4"},
		"1:30":    {"netblt", "Bulk Data Transfer Protocol"},
		"1:31":    {"mfe-nsp", "MFE Network Services Protocol"},
		"1:32":    {"merit-inp", "MERIT Internodal Protocol"},
		"1:34":    {"3pc", "Third Party Connect Protocol"},
		"1:35":    {"idpr", "Inter-Domain Policy Routing Protocol"},
		"1:36":    {"xtp", "XTP"},
		"1:37":    {"ddp", "Datagram Delivery Protocol"},
		"1:38":    {"idpr-cmtp", "IDPR Control Message Transport Proto"},
		"1:39":    {"tp++", ""},
		"1:40":    {"il", "IL Transport Protocol"},
		"1:41":    {"ipv6inip", "Ipv6 encapsulated"},
		"1:42":    {"sdrp", "Source Demand Routing Protocol"},
		"1:43":    {"ipv6-route", "DEPRECATED, traffic will not match"},
		"1:44":    {"ipv6-frag", "DEPRECATED, traffic will not match"},
		"1:45":    {"idrp", "Inter-Domain Routing Protocol"},
		"1:49":    {"bna", "BNA"},
		"1:52":    {"i-nlsp", "Integrated Net Layer Security TUBA"},
		"1:53":    {"swipe", "IP with Encryption"},
		"1:54":    {"narp", "NBMA Address Resolution Protocol"},
		"1:55":    {"mobile", "IP Mobility"},
		"1:56":    {"tlsp", "Transport Layer Security Protocol"},
		"1:57":    {"skip", "SKIP"},
		"1:58":    {"ipv6-icmp", "ICMP for IPv6"},
		"1:59":    {"ipv6-nonxt", "DEPRECATED, traffic will not match"},
		"1:60":    {"ipv6-opts", "DEPRECATED, traffic will not match"},
		"1:61":    {"any-host-internal", "any host internal protocol"},
		"1:62":    {"cftp", "CFTP"},
		"1:64":    {"sat-expak", "SATNET and Backroom EXPAK"},
		"1:66":    {"rvd", "MIT Remote Virtual Disk Protocol"},
		"1:67":    {"ippc", "Internet Pluribus Packet Core"},
		"1:69":    {"sat-mon", "SATNET Monitoring"},
		"1:70":    {"visa", "VISA Protocol"},
		"1:71":    {"ipcv", "Internet Packet Core Utility"},
		"1:72":    {"cpnx", "Computer Protocol Network Executive"},
		"1:73":    {"cphb", "Computer Protocol Heart Beat"},
		"1:74":    {"wsn", "Wang Span Network"},
		"1:75":    {"pvp", "Packet Video Protocol"},
		"1:76":    {"br-sat-mon", "Backroom SATNET Monitoring"},
		"1:77":    {"sun-nd", "SUN ND PROTOCOL-Temporary"},
		"1:78":    {"wb-mon", "WIDEBAND Monitoring"},
		"1:79":    {"wb-expak", "WIDEBAND EXPAK"},
		"1:81":    {"vmtp", "VMTP"},
		"1:82":    {"secure-vmtp", "SECURE-VMTP"},
		"1:84":    {"ttp", "TTP"},
		"1:85":    {"nsfnet-igp", "NSFNET-IGP"},
		"1:86":    {"dgp", "Dissimilar Gateway Protocol"},
		"1:87":    {"tcf", "TCF"},
		"1:90":    {"sprite-rpc", "Sprite RPC Protocol"},
		"1:91":    {"larp", "Locus Address Resolution Protocol"},
		"1:92":    {"mtp", "Multicast Transport Protocol"},
		"1:93":    {"ax25", "AX.25 Frames"},
		"1:94":    {"ipip", "IP-within-IP Encapsulation Protocol"},
		"1:95":    {"micp", "Mobile Internetworking Control Pro."},
		"1:96":    {"scc-sp", "Semaphore Communications Sec. Pro."},
		"1:97":    {"etherip", "Ethernet-within-IP Encapsulation"},
		"1:98":    {"encap", "Encapsulation Header"},
		"1:100":   {"gmtp", "graphical Media Transfer Protocol"},
		"1:101":   {"ifmp", "Ipsilon Flow Management Protocol"},
		"1:102":   {"pnni", "PNNI over IP"},
		"1:103":   {"pim", "Protocol Independent Multicast"},
		"1:104":   {"aris", "ARIS"},
		"1:105":   {"scps", "SCPS"},
		"1:106":   {"qnx", "QNX"},
		"1:107":   {"an", "Active Networks"},
		"1:108":   {"ipcomp", "IP Payload Compression Protocol"},
		"1:109":   {"snp", "Sitara Networks Protocol"},
		"1:110":   {"compaq-peer", "Compaq Peer Protocol"},
		"1:111":   {"ipx-in-ip", "IPX in IP"},
		"1:112":   {"vrrp", "Virtual Router Redundancy Protocol"},
		"1:113":   {"pgm", "PGM Reliable Transport Protocol"},
		"1:116":   {"ddx", "D-II Data Exchange"},
		"1:117":   {"iatp", "Interactive Agent Transfer Protocol"},
		"1:118":   {"schedule-transfer", "Schedule Transfer Protocol"},
		"1:119":   {"srp", "SpectraLink Radio Protocol"},
		"1:120":   {"uti", "UTI"},
		"1:121":   {"smp", "Simple Message Protocol"},
		"1:122":   {"sm", "SM"},
		"1:123":   {"ptp", "Performance Transparency Protocol"},
		"1:124":   {"isis", "Intermediate System-to-Intermediate System (ISIS) over"},
		"1:125":   {"fire", "FIRE"},
		"1:126":   {"crtp", "Combat Radio Transport Protocol"},
		"1:127":   {"crudp", "Combat Radio User Datagram"},
		"1:128":   {"sscopmce", "SSCOPMCE"},
		"1:129":   {"iplt", "IPLT"},
		"1:130":   {"sps", "Secure Packet Shield"},
		"1:131":   {"pipe", "Private IP Encapsulation within IP"},
		"1:132":   {"sctp", "Stream Control Transmission Protocol"},
		"1:133":   {"fc", "Fibre Channel"},
		"1:134":   {"rsvp-e2e-ignore", "RSVP-E2E-IGNORE"},
		"1:136":   {"udplite", "UDPLite, Lightweight connectionless User Datagram Proto"},
		"1:137":   {"mpls-in-ip", "MPLS-in-IP"},
		"1:138":   {"manet", "MANET Protocols"},
		"1:139":   {"hip", "Host Identity Protocol"},
		"1:33":    {"dccp", "Datagram Congestion Control Protocol"},
		"1:48":    {"dsr", "Dynamic Source Routing Protocol"},
		"3:21":    {"ftp", "File Transfer Protocol"},
		"3:80":    {"http", "World Wide Web traffic"},
		"3:179":   {"bgp", "Border Gateway Protocol"},
		"3:79":    {"finger", "Finger"},
		"3:70":    {"gopher", "Internet Gopher protocol, online document management."},
		"3:443":   {"secure-http", "Secured HTTP or SSL"},
		"3:143":   {"imap", "Internet Mail Access Protocol"},
		"3:993":   {"secure-imap", "Internet Message Access Protocol over TLS/SSL"},
		"3:194":   {"irc", "Internet Relay Chat"},
		"3:994":   {"secure-irc", "irc protocol over TLS"},
		"3:88":    {"kerberos", "Kerberos Authentication Protocol"},
		"3:389":   {"ldap", "Lightweight Directory Access Protocol"},
		"3:636":   {"secure-ldap", "ldap protocol over TLS"},
		"3:1433":  {"sqlserver", "Microsoft SQL Server"},
		"3:2049":  {"nfs", "Network File System"},
		"3:119":   {"nntp", "network news transfer protocol"},
		"3:563":   {"secure-nntp", "nntp protocol over TLS"},
		"3:123":   {"ntp", "Network Time Protocol"},
		"3:110":   {"pop3", "Post Office Protocol 3"},
		"3:995":   {"secure-pop3", "pop3 protocol over TLS"},
		"3:1723":  {"pptp", "Point-to-Point Tunneling Protocol"},
		"3:520":   {"rip", "Routing Information Protocol"},
		"3:161":   {"snmp", "Simple Network Messaging Protocol"},
		"3:1080":  {"socks", "generic proxy protocol for TCP/IP-based networking appl"},
		"3:22":    {"ssh", "Secure Shell"},
		"3:23":    {"telnet", "Telnet - virtual text-oriented terminal over network"},
		"3:992":   {"secure-telnet", "telnet protocol over TLS"},
		"3:990":   {"secure-ftp", "ftp protocol, control, over TLS/SSL"},
		"3:6000":  {"xwindows", "X-Windows remote access"},
		"3:515":   {"printer", "spooler"},
		"3:69":    {"tftp", "Trivial File Transfer Protocol"},
		"3:1700":  {"sqlnet", "DEPRECATED,traffic will not match"},
		"3:111":   {"sunrpc", "SUN Remote Procedure Call"},
		"3:554":   {"rtsp", "Real Time Streaming Protocol"},
		"3:5060":  {"sip", "Session Initiation Protocol"},
		"3:25":    {"smtp", "Simple Mail Transfer Protocol"},
		"3:53":    {"dns", "Domain Name Server lookup"},
		"3:3724":  {"blizwow", "World of Warcraft Gaming Protocol"},
		"3:63":    {"whois++", ""},
		"3:543":   {"klogin", "klogin"},
		"3:544":   {"kshell", "krcmd"},
		"3:1525":  {"ora-srv", "Oracle TCP/IP Listener"},
		"3:9088":  {"sqlexec", "SQL Informix"},
		"3:371":   {"clearcase", "Rational ClearCase"},
		"3:458":   {"appleqtc", "apple quick time"},
		"3:469":   {"rcp", "Radio Control Protocol"},
		"3:500":   {"isakmp", "Internet Security Association and Key Management Protoc"},
		"3:523":   {"ibm-db2", "IBM-DB2"},
		"3:4045":  {"lockd", "NFS Lock Daemon Manager"},
		"3:92":    {"npp", "Network Printing Protocol"},
		"3:445":   {"microsoftds", "Microsoft-DS"},
		"3:666":   {"doom", "doom Id Software"},
		"3:7":     {"echo", "Echo debugging and measurement tool"},
		"3:11":    {"systat", "Active Users"},
		"3:13":    {"daytime", "Daytime (RFC 867)"},
		"3:19":    {"chargen", "Character Generator"},
		"3:37":    {"time", "Time"},
		"3:55":    {"isi-gl", "ISI Graphics Language"},
		"3:107":   {"rtelnet", "Remote Telnet Service"},
		"3:213":   {"server-ipx", "Internetwork Packet Exchange Protocol"},
		"3:177":   {"xdmcp", "X Display Manager Control Protocol"},
		"3:43":    {"nicname", "Who Is"},
		"3:683":   {"corba-iiop", "CORBA Internet Inter-ORB Protocol"},
		"3:49":    {"tacacs", "Login Host Protocol"},
		"3:349":   {"mftp", "mftp"},
		"3:350":   {"matip-type-a", "MATIP Type A"},
		"3:351":   {"matip-type-b", "MATIP Type B"},
		"3:352":   {"dtag-ste-sb", "DTAG"},
		"3:353":   {"ndsauth", "NDSAUTH"},
		"3:355":   {"datex-asn", "datex-asn"},
		"3:356":   {"cloanto-net-1", "cloanto-net-1"},
		"3:357":   {"bhevent", "bhevent"},
		"3:358":   {"shrinkwrap", "shrinkwrap"},
		"3:359":   {"nsrmp", "Network Security Risk Management Protocol"},
		"3:360":   {"scoi2odialog", "scoi2odialog"},
		"3:361":   {"semantix", "semantix"},
		"3:362":   {"srssend", "srssend"},
		"3:363":   {"rsvp_tunnel", "rsvp_tunnel"},
		"3:364":   {"aurora-cmgr", "Aurora CMGR"},
		"3:365":   {"dtk", "dtk"},
		"3:366":   {"odmr", "odmr"},
		"3:367":   {"mortgageware", "mortgageware"},
		"3:368":   {"qbikgdp", "qbikgdp"},
		"3:369":   {"rpc2portmap", "rpc2portmap"},
		"3:370":   {"codaauth2", "codaauth2"},
		"3:372":   {"ulistproc", "List Processor"},
		"3:373":   {"legent-1", "Legent Corporation"},
		"3:374":   {"legent-2", "Legent Corporation"},
		"3:375":   {"hassle", "hassle"},
		"3:377":   {"tnETOS", "NEC Corporation"},
		"3:379":   {"is99c", "TIA/EIA/IS-99 modem client"},
		"3:380":   {"is99s", "TIA/EIA/IS-99 modem server"},
		"3:381":   {"hp-collector", "hp performance data collector"},
		"3:382":   {"hp-managed-node", "hp performance data managed node"},
		"3:383":   {"hp-alarm-mgr", "hp performance data alarm manager"},
		"3:384":   {"arns", "A remote network server system"},
		"3:385":   {"ibm-app", "IBM Application"},
		"3:386":   {"asa", "ASA Message router object def"},
		"3:387":   {"aurp", "AppleTalk Update-Based Routing Pro."},
		"3:388":   {"unidata-ldm", "Unidata LDM"},
		"3:347":   {"fatserv", "Fatmen Server"},
		"3:390":   {"uis", "uis"},
		"3:391":   {"synotics-relay", "SynOptics SNMP Relay Port"},
		"3:392":   {"synotics-broker", "SynOptics Port Broker Port"},
		"3:393":   {"meta5", "meta5"},
		"3:394":   {"embl-ndt", "EMBL Nucleic Data Transfer"},
		"3:396":   {"netware-ip", "Novell Netware over IP"},
		"3:397":   {"mptn", "Multi Protocol Trans. Net"},
		"3:398":   {"kryptolan", "kryptolan"},
		"3:399":   {"iso-tsap-c2", "ISO Transport Class 2 Non-Control"},
		"3:401":   {"ups", "Uninterruptible Power Supply"},
		"3:402":   {"genie", "Genie Protocol"},
		"3:403":   {"decap", "decap"},
		"3:404":   {"nced", "nced"},
		"3:405":   {"ncld", "ncld"},
		"3:406":   {"imsp", "Interactive Mail Support Protocol"},
		"3:407":   {"timbuktu", "Timbuktu"},
		"3:408":   {"prm-sm", "Prospero Resource Manager Sys. Man"},
		"3:409":   {"prm-nm", "Prospero Resource Manager Node Man"},
		"3:410":   {"decladebug", "DECLadebug Remote Debug Protocol"},
		"3:411":   {"rmt", "Remote MT Protocol"},
		"3:412":   {"synoptics-trap", "Trap Convention Port"},
		"3:413":   {"smsp", "Storage Management Services Protocol"},
		"3:414":   {"infoseek", "InfoSeek"},
		"3:415":   {"bnet", "bnet"},
		"3:417":   {"onmux", "onmux"},
		"3:418":   {"hyper-g", "hyper-g"},
		"3:419":   {"ariel1", "Ariel1"},
		"3:421":   {"ariel2", "Ariel2"},
		"3:422":   {"ariel3", "Ariel3"},
		"3:423":   {"opc-job-start", "IBM Operations Planning and Control Start"},
		"3:424":   {"opc-job-track", "IBM Operations Planning and Control Track"},
		"3:426":   {"smartsdp", "smartsdp"},
		"3:427":   {"svrloc", "Server Location"},
		"3:428":   {"ocs_cmu", "ocs_cmu"},
		"3:429":   {"ocs_amu", "ocs_amu"},
		"3:430":   {"utmpsd", "utmpsd"},
		"3:431":   {"utmpcd", "utmpcd"},
		"3:432":   {"iasd", "iasd"},
		"3:433":   {"nnsp", "nnsp"},
		"3:434":   {"mobileip-agent", "mobileip-agent"},
		"3:435":   {"mobilip-mn", "mobilip-mn"},
		"3:436":   {"dna-cml", "DNA-CML"},
		"3:437":   {"comscm", "comscm"},
		"3:438":   {"dsfgw", "dsfgw"},
		"3:439":   {"dasp", "dasp"},
		"3:440":   {"sgcp", "sgcp"},
		"3:441":   {"decvms-sysmgt", "decvms-sysmgt"},
		"3:442":   {"cvc_hostd", "cvc_hostd"},
		"3:444":   {"snpp", "Simple Network Paging Protocol"},
		"3:446":   {"ddm-rdb", "DDM-Remote Relational Database Access"},
		"3:447":   {"ddm-dfm", "DDM Distributed File management"},
		"3:448":   {"ddm-ssl", "DDM-Remote DB Access Using Secure Sockets"},
		"3:449":   {"as-servermap", "AS Server Mapper"},
		"3:450":   {"tserver", "Computer Supported Telecommunication Applications"},
		"3:451":   {"sfs-smp-net", "Cray Network Semaphore server"},
		"3:452":   {"sfs-config", "Cray SFS config server"},
		"3:453":   {"creativeserver", "creativeserver"},
		"3:3365":  {"contentserver", "contentserver"},
		"3:455":   {"creativepartnr", "creativepartnr"},
		"3:457":   {"scohelp", "scohelp"},
		"3:460":   {"skronk", "skronk"},
		"3:461":   {"datasurfsrv", "DataRamp Svr"},
		"3:462":   {"datasurfsrvsec", "DataRamp Svr svs"},
		"3:463":   {"alpes", "Alpes"},
		"3:464":   {"kpasswd", "kpasswd"},
		"3:466":   {"digital-vrc", "digital-vrc"},
		"3:467":   {"mylex-mapd", "mylex-mapd"},
		"3:468":   {"photuris", "photuris"},
		"3:470":   {"scx-proxy", "scx-proxy"},
		"3:471":   {"mondex", "mondex"},
		"3:472":   {"ljk-login", "ljk-login"},
		"3:473":   {"hybrid-pop", "hybrid-pop"},
		"3:476":   {"tn-tl-fd1", "tn-tl-fd1"},
		"3:477":   {"ss7ns", "ss7ns"},
		"3:478":   {"spsc", "spsc"},
		"3:479":   {"iafserver", "iafserver"},
		"3:480":   {"iafdbase", "iafdbase"},
		"3:482":   {"bgs-nsi", "bgs-nsi"},
		"3:483":   {"ulpnet", "ulpnet"},
		"3:484":   {"integra-sme", "Integra Software Management Environment"},
		"3:485":   {"powerburst", "Air Soft Power Burst"},
		"3:486":   {"avian", "avian"},
		"3:487":   {"saft", "saft Simple Asynchronous File Transfer"},
		"3:488":   {"gss-http", "gss-http"},
		"3:489":   {"nest-protocol", "nest-protocol"},
		"3:490":   {"micom-pfs", "micom-pfs"},
		"3:491":   {"go-login", "go-login"},
		"3:492":   {"ticf-1", "Transport Independent Convergence for FNA"},
		"3:493":   {"ticf-2", "Transport Independent Convergence for FNA"},
		"3:494":   {"pov-ray", "pov-ray"},
		"3:495":   {"intecourier", "intecourier"},
		"3:496":   {"pim-rp-disc", "PIM-RP-DISC"},
		"3:497":   {"dantz", "dantz"},
		"3:498":   {"siam", "siam"},
		"3:499":   {"iso-ill", "ISO ILL Protocol"},
		"3:501":   {"stmf", "stmf"},
		"3:502":   {"asa-appl-proto", "asa-appl-proto"},
		"3:503":   {"intrinsa", "intrinsa"},
		"3:505":   {"mailbox-lm", "mailbox-lm"},
		"3:506":   {"ohimsrv", "ohimsrv"},
		"3:507":   {"crs", "crs"},
		"3:508":   {"xvttp", "xvttp"},
		"3:509":   {"snare", "snare"},
		"3:510":   {"fcp", "FirstClass Protocol"},
		"3:511":   {"passgo", "passgo"},
		"3:512":   {"exec", "remote process execution"},
		"3:513":   {"login", "Obtain a remote login Terminal"},
		"3:514":   {"shell", "Execute a program on remote shell"},
		"3:516":   {"videotex", "videotex"},
		"3:517":   {"talk", "talk"},
		"3:518":   {"ntalk", "ntalk"},
		"3:519":   {"utime", "unixtime"},
		"3:521":   {"ripng", "Routing information protocol for IPV6 networks"},
		"3:522":   {"ulp", "ulp"},
		"3:344":   {"pdap", "Prospero Data Access Protocol"},
		"3:524":   {"ncp", "Network services Protocol"},
		"3:525":   {"timed", "timeserver"},
		"3:526":   {"tempo", "newdate"},
		"3:527":   {"stx", "Stock IXChange"},
		"3:528":   {"custix", "Customer Ixchange"},
		"3:529":   {"irc-serv", "IRC-SERV"},
		"3:530":   {"courier", "rpc"},
		"3:531":   {"conference", "chat"},
		"3:532":   {"netnews", "readnews"},
		"3:533":   {"netwall", "for emergency broadcasts"},
		"3:535":   {"iiop", "iiop"},
		"3:536":   {"opalis-rdv", "opalis-rdv"},
		"3:537":   {"nmsp", "Networked Media Streaming Protocol"},
		"3:538":   {"gdomap", "gdomap"},
		"3:539":   {"apertus-ldp", "Apertus Tech Load Distribution"},
		"3:540":   {"uucp", "uucpd"},
		"3:541":   {"uucp-rlogin", "uucp-rlogin"},
		"3:542":   {"commerce", "commerce"},
		"3:545":   {"appleqtcsrvr", "appleqtcsrvr"},
		"3:546":   {"dhcpv6-client", "DHCPv6 Client"},
		"3:547":   {"dhcpv6-server", "DHCPv6 Server"},
		"3:549":   {"idfp", "idfp"},
		"3:550":   {"new-rwho", "new who"},
		"3:551":   {"cybercash", "cybercash"},
		"3:553":   {"pirp", "pirp"},
		"3:556":   {"remotefs", "rfs server"},
		"3:557":   {"openvms-sysipc", "openvms-sysipc"},
		"3:558":   {"sdnskmp", "SDNSKMP"},
		"3:559":   {"teedtap", "teedtap"},
		"3:560":   {"rmonitor", "rmonitord"},
		"3:561":   {"monitor", "monitor"},
		"3:562":   {"chshell", "chcmd"},
		"3:564":   {"9pfs", "Plan 9 file service"},
		"3:565":   {"whoami", "whoami"},
		"3:566":   {"streettalk", "streettalk"},
		"3:567":   {"banyan-rpc", "banyan-rpc"},
		"3:568":   {"ms-shuttle", "microsoft shuttle"},
		"3:569":   {"ms-rome", "microsoft rome"},
		"3:570":   {"meter", "meter"},
		"3:572":   {"sonar", "sonar"},
		"3:573":   {"banyan-vip", "banyan-vip"},
		"3:574":   {"ftp-agent", "FTP Software Agent System"},
		"3:575":   {"vemmi", "vemmi"},
		"3:576":   {"ipcd", "ipcd"},
		"3:577":   {"vnas", "vnas"},
		"3:578":   {"ipdd", "ipdd"},
		"3:579":   {"decbsrv", "decbsrv"},
		"3:580":   {"sntp-heartbeat", "SNTP HEARTBEAT"},
		"3:581":   {"bdp", "Bundle Discovery protocol"},
		"3:582":   {"scc-security", "scc-security"},
		"3:583":   {"philips-vc", "Philips Video-Conferencing"},
		"3:584":   {"keyserver", "Key Server"},
		"3:586":   {"password-chg", "Password Change"},
		"3:587":   {"submission", "submission"},
		"3:590":   {"tns-cml", "tns-cml"},
		"3:8080":  {"http-alt", "HTTP Alternate"},
		"3:592":   {"eudora-set", "Eudora Set"},
		"3:593":   {"http-rpc-epmap", "HTTP RPC Ep Map"},
		"3:594":   {"tpip", "tpip"},
		"3:595":   {"cab-protocol", "CAB Protocol"},
		"3:596":   {"smsd", "smsd"},
		"3:597":   {"ptcnameservice", "PTC Name Service"},
		"3:598":   {"sco-websrvrmg3", "SCO Web Server Manager 3"},
		"3:599":   {"acp", "Aeolon Core Protocol"},
		"3:600":   {"ipcserver", "Sun IPC server"},
		"3:606":   {"urm", "Cray Unified Resource Manager"},
		"3:607":   {"nqs", "nqs"},
		"3:608":   {"sift-uft", "Sender-Initiated/Unsolicited File Transfer"},
		"3:609":   {"npmp-trap", "npmp-trap"},
		"3:610":   {"npmp-local", "npmp-local"},
		"3:611":   {"npmp-gui", "npmp-gui"},
		"3:612":   {"hmmp-ind", "HMMP Indication"},
		"3:613":   {"hmmp-op", "HMMP Operation"},
		"3:614":   {"sshell", "SSLshell"},
		"3:615":   {"sco-inetmgr", "Internet Configuration Manager"},
		"3:616":   {"sco-sysmgr", "SCO System Administration Server"},
		"3:617":   {"sco-dtmgr", "SCO Desktop Administration Server"},
		"3:618":   {"dei-icda", "dei-icda"},
		"3:620":   {"sco-websrvrmgr", "SCO Web Server Manager"},
		"3:621":   {"escp-ip", "escp-ip"},
		"3:622":   {"collaborator", "collaborator"},
		"3:624":   {"cryptoadmin", "Crypto Admin"},
		"3:625":   {"dec_dlm", "dec_dlm"},
		"3:627":   {"passgo-tivoli", "passgo-tivoli"},
		"3:628":   {"qmqp", "qmqp"},
		"3:629":   {"3com-amp3", "3Com AMP3"},
		"3:630":   {"rda", "rda"},
		"3:631":   {"ipp", "Internet Printing Protocol"},
		"3:632":   {"bmpp", "bmpp"},
		"3:633":   {"servstat", "Service Status update"},
		"3:634":   {"ginad", "ginad"},
		"3:635":   {"rlzdbase", "rlzdbase"},
		"3:637":   {"lanserver", "lanserver"},
		"3:638":   {"mcns-sec", "mcns-sec"},
		"3:639":   {"msdp", "msdp"},
		"3:640":   {"entrust-sps", "entrust-sps"},
		"3:641":   {"repcmd", "repcmd"},
		"3:642":   {"esro-emsdp", "ESRO-EMSDP V1.3"},
		"3:643":   {"sanity", "sanity"},
		"3:644":   {"dwr", "dwr"},
		"3:646":   {"ldp", "LDP"},
		"3:647":   {"dhcp-failover", "DHCP Failover"},
		"3:648":   {"rrp", "Registry Registrar Protocol"},
		"3:2639":  {"aminet", "AMInet"},
		"3:650":   {"obex", "obex"},
		"3:651":   {"ieee-mms", "ieee-mms"},
		"3:652":   {"hello-port", "HELLO_PORT"},
		"3:653":   {"repscmd", "repscmd"},
		"3:654":   {"aodv", "AODV"},
		"3:655":   {"tinc", "tinc"},
		"3:656":   {"spmp", "spmp"},
		"3:657":   {"rmc", "rmc"},
		"3:658":   {"tenfold", "tenfold"},
		"3:660":   {"mac-srvr-admin", "MacOS Server Admin"},
		"3:661":   {"hap", "hap"},
		"3:662":   {"pftp", "pftp"},
		"3:663":   {"purenoise", "purenoise"},
		"3:665":   {"sun-dr", "sun-dr"},
		"3:667":   {"disclose", "campaign contribution disclosures"},
		"3:668":   {"mecomm", "mecomm"},
		"3:669":   {"meregister", "meregister"},
		"3:670":   {"vacdsm-sws", "VACDSM-SWS"},
		"3:671":   {"vacdsm-app", "VACDSM-APP"},
		"3:672":   {"vpps-qua", "vpps-qua"},
		"3:673":   {"cimplex", "cimplex"},
		"3:674":   {"acap", "ACAP"},
		"3:675":   {"dctp", "dctp"},
		"3:676":   {"vpps-via", "vpps-via"},
		"3:677":   {"vpp", "Virtual Presence Protocol"},
		"3:678":   {"ggf-ncp", "GNU Generation Foundation NCP"},
		"3:679":   {"mrm", "mrm"},
		"3:680":   {"entrust-aaas", "entrust-aaas"},
		"3:681":   {"entrust-aams", "entrust-aams"},
		"3:685":   {"mdc-portmapper", "mdc-portmapper"},
		"3:686":   {"hcp-wismar", "Hardware Control Protocol Wismar"},
		"3:687":   {"asipregistry", "asipregistry"},
		"3:688":   {"realm-rusd", "ApplianceWare management protocol"},
		"3:689":   {"nmap", "nmap"},
		"3:690":   {"vatp", "Velazquez Application Transfer Protocol"},
		"3:691":   {"msexch-routing", "MS Exchange Routing"},
		"3:692":   {"hyperwave-isp", "hyperwave-isp"},
		"3:693":   {"connendp", "almanid Connection Endpoint"},
		"3:694":   {"ha-cluster", "ha-cluster"},
		"3:695":   {"ieee-mms-ssl", "ieee-mms-ssl"},
		"3:696":   {"rushd", "rushd"},
		"3:697":   {"uuidgen", "UUIDGEN"},
		"3:698":   {"olsr", "olsr"},
		"3:699":   {"accessnetwork", "Access Network"},
		"3:704":   {"elcsd", "errlog copy/server daemon"},
		"3:705":   {"agentx", "AgentX"},
		"3:706":   {"silc", "silc"},
		"3:707":   {"borland-dsj", "borland-dsj"},
		"3:709":   {"entrust-kmsh", "Entrust Key Management Service Handler"},
		"3:710":   {"entrust-ash", "Entrust Administration Service Handler"},
		"3:711":   {"cisco-tdp", "Cisco TDP"},
		"3:729":   {"netviewdm1", "IBM NetView DM"},
		"3:730":   {"netviewdm2", "IBM NetView DM"},
		"3:731":   {"netviewdm3", "IBM NetView DM"},
		"3:741":   {"netgw", "netgw"},
		"3:742":   {"netrcs", "Network based RCS"},
		"3:744":   {"flexlm", "Flexible License Manager"},
		"3:747":   {"fujitsu-dev", "Fujitsu Device Control"},
		"3:748":   {"ris-cm", "Russell Info Sci Calendar Manager"},
		"3:749":   {"kerberos-adm", "kerberos administration"},
		"3:751":   {"pump", "pump"},
		"3:752":   {"qrh", "qrh"},
		"3:753":   {"rrh", "rrh"},
		"3:754":   {"tell", "send"},
		"3:758":   {"nlogin", "nlogin"},
		"3:759":   {"con", "con"},
		"3:760":   {"ns", "ns"},
		"3:761":   {"rxe", "rxe"},
		"3:762":   {"quotad", "quotad"},
		"3:763":   {"cycleserv", "cycleserv"},
		"3:764":   {"omserv", "omserv"},
		"3:765":   {"webster", "webster"},
		"3:767":   {"phonebook", "Phone"},
		"3:769":   {"vid", "vid"},
		"3:770":   {"cadlock", "cadlock"},
		"3:771":   {"rtip", "rtip"},
		"3:772":   {"cycleserv2", "cycleserv2"},
		"3:773":   {"submit", "Submit Protocol"},
		"3:775":   {"entomb", "entomb"},
		"3:777":   {"multiling-http", "Multiling HTTP"},
		"3:780":   {"wpgs", "wpgs"},
		"3:801":   {"device", "device"},
		"3:828":   {"itm-mcell-s", "itm-mcell-s"},
		"3:829":   {"pkix-3-ca-ra", "PKIX-3 CA/RA"},
		"3:847":   {"dhcp-failover2", "dhcp-failover2"},
		"3:873":   {"rsync", "rsync"},
		"3:886":   {"iclcnet-locate", "ICL coNETion locate server"},
		"3:887":   {"iclcnet_svinfo", "ICL coNETion server info"},
		"3:888":   {"accessbuilder", "Access Builder"},
		"3:900":   {"omginitialrefs", "omginitialrefs"},
		"3:901":   {"smpnameres", "smpnameres"},
		"3:911":   {"xact-backup", "xact-backup"},
		"3:989":   {"ftps-data", "ftp protocol, data, over TLS/SSL"},
		"3:991":   {"nas", "Netnews Administration System"},
		"3:996":   {"vsinet", "vsinet"},
		"3:997":   {"maitrd", "maitrd"},
		"3:1010":  {"surf", "surf"},
		"3:1098":  {"rmiactivation", "rmiactivation"},
		"3:1099":  {"rmiregistry", "rmiregistry"},
		"3:156":   {"sqlsrv", "SQL Service"},
		"3:1434":  {"ms-sql-m", "Microsoft-SQL-Monitor"},
		"3:2393":  {"ms-olap", "Microsoft OLAP"},
		"3:3268":  {"msft-gc", "Microsoft Global Catalog"},
		"3:3269":  {"msft-gc-ssl", "Microsoft Global Catalog with LDAP/SSL"},
		"3:3389":  {"ms-wbt", "Microsoft Windows based Terminal Services"},
		"3:1527":  {"tlisrv", "oracle"},
		"3:1529":  {"coauthor", "oracle"},
		"3:1571":  {"rdb-dbs-disp", "Oracle Remote Data Base"},
		"3:1575":  {"oraclenames", "oraclenames"},
		"3:1630":  {"oraclenet8cman", "Oracle Net8 Cman"},
		"3:1830":  {"net8-cman", "Oracle Net8 CMan Admin"},
		"3:1534":  {"micromuse-lm", "micromuse-lm"},
		"3:3075":  {"orbix-locator", "Orbix 2000 Locator"},
		"3:3076":  {"orbix-config", "Orbix 2000 Config"},
		"3:3077":  {"orbix-loc-ssl", "Orbix 2000 Locator SSL"},
		"3:1626":  {"shockwave", "Shockwave"},
		"3:2629":  {"sitaraserver", "sitaraserver"},
		"3:2630":  {"sitaramgmt", "sitaramgmt"},
		"3:2631":  {"sitaradir", "sitaradir"},
		"3:3306":  {"mysql", "database management system"},
		"3:3300":  {"net-assistant", "DEPRECATED,traffic will not match"},
		"3:1863":  {"msnp", "msnp"},
		"3:2492":  {"groove", "groove"},
		"3:2234":  {"directplay", "DirectPlay"},
		"3:6073":  {"directplay8", "DirectPlay8"},
		"3:2213":  {"kali", "kali"},
		"3:2595":  {"worldfusion", "World Fusion"},
		"3:3334":  {"directv-web", "Direct TV Webcasting"},
		"3:3335":  {"directv-soft", "Direct TV Software Updates"},
		"3:3336":  {"directv-tick", "Direct TV Tickers"},
		"3:3337":  {"directv-catlg", "Direct TV Data Catalog"},
		"3:2948":  {"wap-push", "WAP PUSH"},
		"3:2949":  {"wap-pushsecure", "WAP PUSH SECURE"},
		"3:4035":  {"wap-push-http", "WAP Push OTA-HTTP port"},
		"3:4036":  {"wap-push-https", "WAP Push OTA-HTTP secure"},
		"3:9200":  {"wap-wsp", "WAP connectionless session service"},
		"3:9201":  {"wap-wsp-wtp", "WAP session service"},
		"3:9202":  {"wap-wsp-s", "WAP secure connectionless session service"},
		"3:9203":  {"wap-wsp-wtp-s", "WAP secure session service"},
		"3:9204":  {"wap-vcard", "WAP vCard"},
		"3:9205":  {"wap-vcal", "WAP vCal"},
		"3:9206":  {"wap-vcard-s", "WAP vCard Secure"},
		"3:9207":  {"wap-vcal-s", "WAP vCal Secure"},
		"3:6714":  {"ibprotocol", "Internet Backplane Protocol"},
		"3:1812":  {"radius", "Remote Authentication Dial In User Service protocol"},
		"3:2152":  {"gtp-user", "GTP-User Plane"},
		"3:3088":  {"xdtp", "eXtensible Data Transfer Protocol"},
		"3:6582":  {"parsec-game", "Parsec Gameserver"},
		"3:346":   {"zserv", "Zebra server"},
		"3:345":   {"pawserv", "Perf Analysis Workbench"},
		"3:333":   {"texar", "Texar Security Port"},
		"3:322":   {"rtsps", "RTSPS"},
		"3:1321":  {"pip", "pip"},
		"3:320":   {"ptp-general", "PTP General"},
		"3:3478":  {"stun-nat", "Session Traversal Utilities for NAT (STUN)"},
		"3:2":     {"compressnet", "Management Utility"},
		"3:5":     {"rje", "Remote Job Entry"},
		"3:9":     {"discard", "Discard"},
		"3:17":    {"qotd", "Quote of the Day"},
		"3:18":    {"msp", "Message Send Protocol"},
		"3:20":    {"ftp-data", "File Transfer Protocol, Data part only"},
		"3:27":    {"nsw-fe", "NSW User System FE"},
		"3:29":    {"msg-icp", "msg-icp"},
		"3:348":   {"csi-sgwp", "Cabletron Management Protocol"},
		"3:31":    {"msg-auth", "msg-auth"},
		"3:33":    {"dsp", "Display Support Protocol"},
		"3:38":    {"rap", "Route Access Protocol"},
		"3:39":    {"rlp", "Resource Location Protocol"},
		"3:41":    {"graphics", "Graphics"},
		"3:42":    {"name", "Host Name Server"},
		"3:136":   {"profile", "PROFILE Naming System"},
		"3:44":    {"mpm-flags", "MPM FLAGS Protocol"},
		"3:45":    {"mpm", "Message Processing Module"},
		"3:46":    {"mpm-snd", "MPM [default send]"},
		"3:47":    {"ni-ftp", "NI FTP"},
		"3:48":    {"auditd", "Digital Audit daemon"},
		"3:140":   {"emfis-data", "EMFIS Data Service"},
		"3:50":    {"re-mail-ck", "Remote Mail Checking Protocol"},
		"3:51":    {"la-maint", "IMP Logical Address Maintenance"},
		"3:52":    {"xns-time", "XNS Time Protocol"},
		"3:141":   {"emfis-cntl", "EMFIS Control Service"},
		"3:54":    {"xns-ch", "XNS Clearinghouse"},
		"3:142":   {"bl-idm", "Britton Lee IDM"},
		"3:56":    {"xns-auth", "XNS Authentication"},
		"3:58":    {"xns-mail", "XNS mail"},
		"3:61":    {"ni-mail", "NI MAIL"},
		"3:62":    {"acas", "ACA Services"},
		"3:64":    {"covia", "Communications Integrator"},
		"3:145":   {"uaac", "UAAC Protocol"},
		"3:146":   {"iso-tp0", "iso-tp0"},
		"3:71":    {"netrjs-1", "Remote Job Service"},
		"3:72":    {"netrjs-2", "Remote Job Service"},
		"3:73":    {"netrjs-3", "Remote Job Service"},
		"3:74":    {"netrjs-4", "Remote Job Service"},
		"3:76":    {"deos", "Distributed External Object Store"},
		"3:147":   {"iso-ip", "iso-ip"},
		"3:82":    {"xfer", "XFER Utility"},
		"3:83":    {"mit-ml-dev", "MIT ML Device"},
		"3:84":    {"ctf", "Common Trace Facility"},
		"3:86":    {"mfcobol", "Micro Focus Cobol"},
		"3:148":   {"jargon", "Jargon"},
		"3:89":    {"su-mit-tg", "SU/MIT Telnet Gateway"},
		"3:90":    {"dnsix", "DNSIX Security Attribute Token Map"},
		"3:91":    {"mit-dov", "MIT Dover Spooler"},
		"3:149":   {"aed-512", "AED 512 Emulation service"},
		"3:93":    {"dcp", "Device Control Protocol"},
		"3:94":    {"objcall", "Tivoli Object Dispatcher"},
		"3:95":    {"supdup", "SUPDUP"},
		"3:96":    {"dixie", "DIXIE Protocol Specification"},
		"3:97":    {"swift-rvf", "Swift Remote Virtual File Protocol"},
		"3:98":    {"tacnews", "TAC News"},
		"3:99":    {"metagram", "metagram"},
		"3:101":   {"hostname", "NIC Host Name Server"},
		"3:102":   {"iso-tsap", "ISO-TSAP Class 0"},
		"3:104":   {"acr-nema", "ACR-NEMA Digital Img"},
		"3:105":   {"csnet-ns", "Mailbox Name Nameserver"},
		"3:106":   {"3com-tsmux", "3Com TSMUX"},
		"3:150":   {"sql-net", "SQL-NET"},
		"3:108":   {"snagas", "SNA Gateway Access Server"},
		"3:109":   {"pop2", "Post Office Protocol - Version 2"},
		"3:151":   {"hems", "hems"},
		"3:112":   {"mcidas", "McIDAS Data Transmission Protocol"},
		"3:113":   {"auth", "Authentication Service"},
		"3:115":   {"sftp", "Simple File Transfer Protocol"},
		"3:116":   {"ansanotify", "ANSA REX Notify"},
		"3:117":   {"uucp-path", "UUCP Path Service"},
		"3:118":   {"sqlserv", "SQL Services"},
		"3:120":   {"cfdptkt", "cfdptkt"},
		"3:121":   {"erpc", "Encore Expedited Remote Pro.Call"},
		"3:122":   {"smakynet", "smakynet"},
		"3:152":   {"bftp", "Background File Transfer Program"},
		"3:124":   {"ansatrader", "ansatrader"},
		"3:125":   {"locus-map", "Locus PC-Interface Net Map Server"},
		"3:126":   {"nxedit", "nxedit"},
		"3:127":   {"locus-con", "Locus PC-Interface Conn Server"},
		"3:128":   {"gss-xlicen", "GNU Generation Foundation NCP"},
		"3:129":   {"pwdgen", "Password Generator Protocol"},
		"3:130":   {"cisco-fna", "cisco FNATIVE"},
		"3:153":   {"sgmp", "sgmp"},
		"3:154":   {"netsc-prod", "NETSC"},
		"3:155":   {"netsc-dev", "NETSC"},
		"3:157":   {"knet-cmp", "KNET/VM Command/Message Protocol"},
		"3:158":   {"pcmail-srv", "PCMail Server"},
		"3:159":   {"nss-routing", "NSS-Routing"},
		"3:160":   {"sgmp-traps", "sgmp-traps"},
		"3:163":   {"cmip-man", "CMIP/TCP Manager"},
		"3:164":   {"cmip-agent", "CMIP/TCP Agent"},
		"3:165":   {"xns-courier", "Xerox"},
		"3:166":   {"s-net", "Sirius Systems"},
		"3:167":   {"namp", "namp"},
		"3:168":   {"rsvd", "rsvd"},
		"3:169":   {"send", "SEND"},
		"3:170":   {"print-srv", "Network PostScript"},
		"3:171":   {"multiplex", "Network Innovations Multiplex"},
		"3:173":   {"xyplex-mux", "Xyplex"},
		"3:174":   {"mailq", "MAILQ"},
		"3:175":   {"vmnet", "vmnet"},
		"3:176":   {"genrad-mux", "genrad-mux"},
		"3:178":   {"nextstep", "NextStep Window Server"},
		"3:180":   {"ris", "Intergraph"},
		"3:181":   {"unify", "Unify"},
		"3:182":   {"audit", "Unisys Audit SITP"},
		"3:183":   {"ocbinder", "ocbinder"},
		"3:184":   {"ocserver", "ocserver"},
		"3:185":   {"remote-kis", "remote-kis"},
		"3:186":   {"kis", "KIS Protocol"},
		"3:188":   {"mumps", "Plus Fives MUMPS"},
		"3:189":   {"qft", "Queued File Transport"},
		"3:190":   {"gacp", "Gateway Access Control Protocol"},
		"3:191":   {"prospero", "Prospero Directory Service"},
		"3:192":   {"osu-nms", "OSU Network Monitoring System"},
		"3:193":   {"srmp", "Spider Remote Monitoring Protocol"},
		"3:195":   {"dn6-nlm-aud", "DNSIX Network Level Module Audit"},
		"3:197":   {"dls", "Directory Location Service"},
		"3:198":   {"dls-mon", "Directory Location Service Monitor"},
		"3:199":   {"smux", "SMUX"},
		"3:200":   {"src", "IBM System Resource Controller"},
		"3:201":   {"at-rtmp", "AppleTalk Routing Maintenance"},
		"3:202":   {"at-nbp", "AppleTalk Name Binding"},
		"3:203":   {"at-3", "AppleTalk Unused"},
		"3:204":   {"at-echo", "AppleTalk Echo"},
		"3:205":   {"at-5", "AppleTalk Unused"},
		"3:206":   {"at-zis", "AppleTalk Zone Information"},
		"3:207":   {"at-7", "AppleTalk Unused"},
		"3:208":   {"at-8", "AppleTalk Unused"},
		"3:209":   {"qmtp", "The Quick Mail Transfer Protocol"},
		"3:210":   {"z39.50", ""},
		"3:211":   {"914c/g", ""},
		"3:212":   {"anet", "ATEXSSTR"},
		"3:214":   {"vmpwscs", "vmpwscs"},
		"3:215":   {"softpc", "Insignia Solutions"},
		"3:216":   {"CAIlic", "Computer Associates Intl License Server"},
		"3:217":   {"dbase", "dBASE Unix"},
		"3:218":   {"mpp", "Netix Message Posting Protocol"},
		"3:219":   {"uarps", "Unisys ARPs"},
		"3:221":   {"fln-spx", "Berkeley rlogind with SPX auth"},
		"3:222":   {"rsh-spx", "Berkeley rshd with SPX auth"},
		"3:223":   {"cdc", "Certificate Distribution Center"},
		"3:224":   {"masqdialer", "masqdialer"},
		"3:243":   {"sur-meas", "Survey Measurement"},
		"3:244":   {"inbusiness", "inbusiness"},
		"3:246":   {"dsp3270", "Display Systems Protocol"},
		"3:247":   {"subntbcst_tftp", "subntbcst_tftp"},
		"3:248":   {"bhfhs", "bhfhs"},
		"3:257":   {"set", "Secure Electronic Transaction"},
		"3:259":   {"esro-gen", "Efficient Short Remote Operations"},
		"3:260":   {"openport", "openport"},
		"3:261":   {"nsiiops", "IIOP Name Service over TLS/SSL"},
		"3:262":   {"arcisdms", "arcisdms"},
		"3:263":   {"hdap", "hdap"},
		"3:264":   {"bgmp", "BGMP"},
		"3:265":   {"x-bone-ctl", "Xbone CTL"},
		"3:266":   {"sst", "SCSI on ST"},
		"3:267":   {"td-service", "Tobit David Service Layer"},
		"3:268":   {"td-replica", "Tobit David Replica"},
		"3:280":   {"http-mgmt", "http-mgmt"},
		"3:281":   {"personal-link", "personal-link"},
		"3:282":   {"cableport-ax", "Cable Port A/X"},
		"3:283":   {"rescap", "rescap"},
		"3:284":   {"corerjd", "corerjd"},
		"3:287":   {"k-block", "k-block"},
		"3:308":   {"novastorbakcup", "Novastor Backup"},
		"3:310":   {"bhmds", "bhmds"},
		"3:311":   {"asip-webadmin", "AppleShare IP WebAdmin"},
		"3:312":   {"vslmp", "vslmp"},
		"3:313":   {"magenta-logic", "magenta-logic"},
		"3:314":   {"opalis-robot", "opalis-robot"},
		"3:315":   {"dpsi", "dpsi"},
		"3:316":   {"decauth", "decauth"},
		"3:317":   {"zannet", "zannet"},
		"3:318":   {"pkix-timestamp", "pkix-timestamp"},
		"3:319":   {"ptp-event", "PTP Event"},
		"3:131":   {"cisco-tna", "cisco TNATIVE"},
		"3:132":   {"cisco-sys", "cisco SYSMAINT"},
		"3:133":   {"statsrv", "Statistics Service"},
		"3:134":   {"ingres-net", "INGRES-NET Service"},
		"3:6085":  {"Konspire2b", "konspire2b p2p network"},
		"3:5246":  {"capwap-control", "Control And Provisioning of Wireless Access Points Cont"},
		"3:5190":  {"aol-protocol", "America OnLine software suite"},
		"3:135":   {"epmap", "DCE endpoint resolution"},
		"3:2811":  {"gsiftp", "GSI FTP"},
		"3:5349":  {"stuns", "STUN over TLS"},
		"3:5222":  {"xmpp-client", "Extensible Messaging and Presence Protocol (XMPP) Clien"},
		"3:5247":  {"capwap-data", "Control And Provisioning of Wireless Access Points Data"},
		"3:548":   {"afpovertcp", "AFP over TCP"},
		"3:8211":  {"aruba-papi", "Aruba access point manager"},
		"3:4569":  {"iax", "Inter-Asterisk eXchange"},
		"3:47808": {"bacnet", "Building Automation and Control Networks"},
		"3:1984":  {"bb", "Big Brother network monitoring tool"},
		"3:18190": {"checkpoint-cpmi", "Check Point Management Interface"},
		"3:8905":  {"cisco-nac", "Cisco Network Access Control (NAC) system"},
		"3:6499":  {"cooltalk", "Internet telephony tool"},
		"3:2301":  {"cpq-wbem", "Compaq HTTP"},
		"3:2401":  {"cvspserver", "CVS pserver"},
		"3:5999":  {"cvsup", "Cvsup"},
		"3:52300": {"desknets", "Groupware application for resource sharing"},
		"3:3632":  {"distcc", "Distributed Compiler"},
		"3:20000": {"dnp", "Distributed Network Protocol (DNP3) over TCP"},
		"3:3218":  {"smartpackets", "EMC SmartPackets"},
		"3:3050":  {"gds_db", "GDS DataBase"},
		"3:19150": {"gkrellm", "Monitoring program"},
		"3:5325":  {"goboogy", "P2P file sharing"},
		"3:2217":  {"gotodevice", "Online device management application"},
		"3:1677":  {"groupwise", "Groupwise messaging and groupware platform"},
		"3:20016": {"hitachi-spc", "Hitachi Universal Storage Platform"},
		"3:3260":  {"iscsi-target", "Internet Small Computer System Interface"},
		"3:4514":  {"loglogic", "Log and security management"},
		"3:7210":  {"maxdb", "MaxDB relational database management system"},
		"3:8801":  {"mcafee-update", "Update client of McAfee-computer security software"},
		"3:1755":  {"ms-streaming", "Microsoft media services"},
		"3:6891":  {"ms-ocs-file-transfer", "Microsoft Office Communications Server and File Transfe"},
		"3:10000": {"ndmp", "Network Data Management Protocol"},
		"3:33435": {"netvmg-traceroute", "Routing diagnostics tool"},
		"3:9703":  {"oracle-bi", "Oracle Business Intelligence"},
		"3:2351":  {"psrserver", "Pharos psrserver"},
		"3:5432":  {"postgresql", "PostgreSQL database"},
		"3:4899":  {"radmin-port", "Remote Admin"},
		"3:6970":  {"rdt", "Real Data Transport"},
		"3:6343":  {"sflow", "Sflow traffic monitoring"},
		"3:19880": {"softros-messenger-ft", "Softros LAN Messenger and File Transfer"},
		"3:3690":  {"svn", "Apache subversion software revision control"},
		"3:27665": {"trinoo", "Set of computer programs to conduct a DDoS attack"},
		"3:15868": {"websense", "Web filtering software"},
		"3:7100":  {"font-service", "X font service"},
		"3:25999": {"xfire", "Freeware instant messaging service"},
		"3:3817":  {"tapeware", "Yosemite tech tapeware"},
		"3:2160":  {"apc-powerchute", "American Power Conversion"},
		"3:9022":  {"applejuice", "Apple juice P2P file sharing"},
		"3:3211":  {"avocent", "Secure management and installation discovery"},
		"3:20500": {"call-of-duty", "Call of duty online gaming"},
		"3:8880":  {"cddbp-alt", "CD Data base Protocol"},
		"3:6305":  {"dclink", "Automated Data Collection Solution"},
		"3:2189":  {"esignal", "Real-time market data and decision support tools"},
		"3:2399":  {"filemaker-announcement", "Filemaker relational database application"},
		"3:12975": {"hamachi", "Shareware VPN application"},
		"3:7220":  {"heroix-longitude", "Network performance monitoring software"},
		"3:9100":  {"hp-pdl-datastr", "PDL data streaming port"},
		"3:1533":  {"virtual-places", "Virtual places software"},
		"3:6997":  {"MobilitySrv", "Mobility XE protocol"},
		"3:1270":  {"opsmgr", "Microsoft Operations Manager"},
		"3:5723":  {"omhs", "Operations Manager - Health Service"},
		"3:1521":  {"ncube-lm", "Ncube License Manager"},
		"3:1498":  {"sybase", "Database management system"},
		"3:40001": {"teamsound", "Voice conferencing software for online game"},
		"3:7631":  {"tesla-sys-msg", "TESLA System Messaging"},
		"3:11010": {"tradestation", "Technical analysis software"},
		"3:8182":  {"vmware-fdm", "VMware Fault Domain Manager"},
		"3:5330":  {"war-rock", "War-rock online gaming"},
		"3:2048":  {"wccp", "Web Cache Communication Protocol"},
		"3:2887":  {"wlccp", "Wireless LAN Context Control Protocol"},
		"3:4490":  {"ibm-director", "Element management system"},
		"3:1970":  {"netop-remote-control", "Remote control management and support software"},
		"3:6665":  {"p10", "Internet relay chat"},
		"3:137":   {"netbios-ns", "NetBIOS Naming Service"},
		"3:1698":  {"rsvp-encap-1", "Resource Reservation Protocol"},
		"3:1699":  {"rsvp-encap-2", "Resource Reservation Protocol"},
		"3:66":    {"oracle-sqlnet", "SQL*NET for Oracle"},
		"3:4172":  {"pcoip", "PC-over-IP - Virtual Desktop Infrastructure"},
		"3:5061":  {"sip-tls", "Secure Session Initiation Protocol tunneled in SSL or T"},
		"3:1604":  {"citrix-static", "Citrix Static"},
		"3:860":   {"iscsi", "Internet Small Computer System Interface"},
		"3:1352":  {"lotus-notes", "IBM Lotus Notes collaborative client-server platform"},
		"3:3283":  {"apple-remote-desktop", "Apple Remote Desktop"},
		"3:17500": {"dropbox", "Dropbox, file hosting service"},
		"3:10080": {"amanda", "Advanced Maryland Automatic Network Disk Archiver"},
		"13:0":    {"unclassified", "Unclassified traffic"},
		"13:1":    {"unknown", "Unknown application"},
		"13:9":    {"ipsec", "IPSec traffic"},
		"13:12":   {"cuseeme", "CU-SeeMe desktop video conference"},
		"13:13":   {"dhcp", "Dynamic Host Configuration Protocol"},
		"13:26":   {"netbios", "netbios"},
		"13:2000": {"notes", "DEPRECATED, traffic will not match. Please use lotus-no"},
		"13:32":   {"pcanywhere", "Symantec pcAnywhere remote desktop"},
		"13:41":   {"syslog", "System Logging Utility"},
		"13:47":   {"novadigm", "Novadigm EDM"},
		"13:49":   {"exchange", "MS-Exchange"},
		"13:425":  {"vdolive", "VDOLive streaming video"},
		"13:426":  {"netshow", "Microsoft Netshow, media streaming protocol"},
		"13:427":  {"streamwork", "Xing Technology StreamWorks player"},
		"13:56":   {"citrix", "Citrix Systems Metaframe 3.0"},
		"13:57":   {"fasttrack", "DEPRECATED, traffic will not match"},
		"13:58":   {"gnutella", "Gnutella Version2 Traffic, peer-to-peer file-sharing pr"},
		"13:59":   {"kazaa2", "DEPRECATED, traffic will not match"},
		"13:61":   {"rtp", "Real Time Protocol"},
		"13:62":   {"mgcp", "Media Gateway Control Protocol"},
		"13:63":   {"skinny", "Skinny Call Control Protocol"},
		"13:64":   {"h323", "H323 Protocol"},
		"13:66":   {"rtcp", "Real Time Control Protocol"},
		"13:67":   {"edonkey", "eDonkey p2p file sharing client"},
		"13:68":   {"winmx", "WinMx file-sharing application"},
		"13:69":   {"bittorrent", "bittorrent p2p file sharing client"},
		"13:70":   {"directconnect", "Direct Connect Version 2.0, peer-to-peer file sharing p"},
		"13:73":   {"hl7", "Health Level Seven protocol, information exchanging bet"},
		"13:74":   {"fix", "Financial Information eXchange Protocol"},
		"13:75":   {"msn-messenger", "MSN Messenger IM, Status Messages, News and Gaming"},
		"13:76":   {"dicom", "Digital Imaging and Communication in Medicine"},
		"13:77":   {"yahoo-messenger", "Yahoo Messenger, Instant Messaging Client"},
		"13:78":   {"mapi", "Messaging Application Programming Interface"},
		"13:79":   {"aol-messenger", "AOL Instant Messenger Text Chat"},
		"13:80":   {"cifs", "common internet file system"},
		"13:81":   {"cisco-phone", "Cisco IP Phones and PC-based Unified Communicators"},
		"13:82":   {"youtube", "Youtube, video streaming"},
		"13:83":   {"skype", "Skype Peer-to-Peer Internet Telephony Protocol"},
		"13:84":   {"sap", "SAP Systems Applications Product in Data processing"},
		"13:100":  {"vnc", "Virtual Network Computing"},
		"13:113":  {"telepresence-media", "Cisco Telepresence-media"},
		"13:114":  {"telepresence-control", "Cisco Telepresence-control"},
		"13:428":  {"zattoo", "Peer-to-Peer Internet Video Protocol"},
		"13:429":  {"sopcast", "Free P2P internet TV"},
		"13:299":  {"flash-video", "Flash video streams"},
		"13:301":  {"flashyahoo", "Flash streams at yahoo"},
		"13:300":  {"flashmyspace", "Flash streams at myspace.com"},
		"13:430":  {"audio-over-http", "Audio traffic over HTTP"},
		"13:431":  {"binary-over-http", "Binary traffic over HTTP"},
		"13:432":  {"video-over-http", "Video traffic over HTTP"},
		"13:420":  {"networking-gnutella", "Gnutella-networking Version2 Traffic"},
		"13:469":  {"winny", "winny2 and winnyP traffic, peer-to-peer file sharing pr"},
		"13:266":  {"manolito", "Free secure P2P file sharing"},
		"13:267":  {"soulseek", "P2P file sharing application"},
		"13:433":  {"filetopia", "Secure P2P file sharing application"},
		"13:434":  {"itunes", "Organize and play media application"},
		"13:268":  {"napster", "Commercial Media Distribution Application"},
		"13:421":  {"waste", "encrypted file sharing client"},
		"13:542":  {"pptv", "P2P video streaming app"},
		"13:422":  {"yahoo-voip-messenger", "Free P2P calls"},
		"13:264":  {"applix", "Applix ac"},
		"13:423":  {"ppstream", "P2P video streaming application"},
		"13:424":  {"poco", "P2P file sharing Software"},
		"13:435":  {"tunnel-http", "HTTP Tunneling"},
		"13:436":  {"guruguru", "DEPRECATED, traffic will not match"},
		"13:437":  {"kuro", "Japanese file sharing client"},
		"13:438":  {"soribada", "a Korean P2P music sharing protocol"},
		"13:417":  {"encrypted-emule", "P2P file sharing encrypted protocol"},
		"13:439":  {"dht", "Distributed sloppy Hash Table protocol"},
		"13:440":  {"sling", "SlingBox Internet TV"},
		"13:441":  {"google-earth", "Location Based Service"},
		"13:269":  {"icq", "I seek you (ICQ), Instant Messaging Protocol"},
		"13:470":  {"gtalk", "Base google-talk protocol"},
		"13:60":   {"fring-video", "Fring Video, video conversations on mobiles"},
		"13:328":  {"secondlife", "SecondLife traffic"},
		"13:331":  {"tcpoverdns", "TCP over DNS traffic"},
		"13:442":  {"baidu-movie", "Internet TV"},
		"13:443":  {"pando", "Peer-to-Peer File-Sharing"},
		"13:54":   {"fring", "Fring IM setups and Ads"},
		"13:444":  {"fring-voip", "Fring Voip, voice conversations on mobiles over IP"},
		"13:445":  {"webthunder", "Peer-to-Peer File-Sharing"},
		"13:454":  {"babelgum", "Internet TV web platform"},
		"13:418":  {"rtmp", "Real Time Messaging Protocol"},
		"13:446":  {"ventrilo", "Ventrilo VOIP and chat protocol"},
		"13:447":  {"teamspeak", "Voice communication protocol"},
		"13:462":  {"gmail", "Gmail and Gmail-chat traffic"},
		"13:533":  {"yahoo-accounts", "Yahoo Accounts"},
		"13:448":  {"maplestory", "Maple Story Gaming Protocol"},
		"13:449":  {"tomatopang", "Tomatopang Peer-to-Peer File Sharing"},
		"13:450":  {"songsari", "Songsari P2P File Sharing"},
		"13:473":  {"active-directory", "Active Directory Traffic"},
		"13:302":  {"yahoo-voip-over-sip", "Yahoo VoIP over SIP"},
		"13:305":  {"gtalk-voip", "Google Talk voice"},
		"13:308":  {"gtalk-ft", "Google Talk File Transfer"},
		"13:309":  {"msn-messenger-ft", "MSN Messenger file transfer"},
		"13:311":  {"icq-filetransfer", "DEPRECATED, signatures moved to OSCAR File-Transfer"},
		"13:312":  {"my-jabber-ft", "DEPRECATED,traffic will not match"},
		"13:313":  {"encrypted-bittorrent", "Encrypted Bittorrent Traffic"},
		"13:323":  {"msn-messenger-video", "MSN Messenger Video"},
		"13:326":  {"teredo-ipv6-tunneled", "Teredo IPv6 over IPv4 tunneling protocol"},
		"13:327":  {"ayiya-ipv6-tunneled", "Ayiya IPv6 tunneling protocol"},
		"13:329":  {"isatap-ipv6-tunneled", "Intra-Site Automatic Tunnel Addressing Protocol IPv6 ov"},
		"13:330":  {"sixtofour-ipv6-tunneled", "Sixtofour IPv6 over IPv4 tunneling protocol"},
		"13:401":  {"netapp-snapmirror", "Data replication Enterprise Solution"},
		"13:414":  {"webex-meeting", "Online conferencing application"},
		"13:415":  {"windows-update", "DEPRECATED,traffic will not match"},
		"13:451":  {"gridftp", "File Transfer Protocol over the Grid"},
		"13:1310": {"ms-rpc", "Microsoft Remote Procedure Call"},
		"13:453":  {"ssl", "Secure Socket Layer Protocol"},
		"13:455":  {"openvpn", "OpenVPN protocol"},
		"13:456":  {"cisco-ip-camera", "Cisco video surveillance camera"},
		"13:457":  {"netflix", "Netflix online video streaming and browsing"},
		"13:458":  {"hulu", "Hulu browsing"},
		"13:459":  {"megavideo", "DEPRECATED, traffic will not match"},
		"13:460":  {"tor", "The Onion Routing Protocol"},
		"13:1320": {"viber", "Viber VoIP is a mobile voice communication application."},
		"13:467":  {"fasttrack-static", "FastTrack Traffic - KaZaA, Morpheus, Grokster..."},
		"13:464":  {"gtalk-chat", "IM between the Google Talk servers and its clients"},
		"13:475":  {"ip-messenger", "Instant messaging over IP application"},
		"13:416":  {"edonkey-static", "Static Edonkey"},
		"13:506":  {"game-spy", "Game-spy online gaming"},
		"13:378":  {"lwapp", "Lightweight Access Point Protocol"},
		"13:379":  {"synergy", "Computer resources sharing application"},
		"13:472":  {"steam", "Online game platform"},
		"13:474":  {"livemeeting", "DEPRECATED, traffic will not match"},
		"13:471":  {"gtalk-video", "Google Talk Video Call"},
		"13:479":  {"ping", "Ping is echo-req/echo-reply over ICMP"},
		"13:480":  {"livestation", "Live television and radio broadcasts"},
		"13:481":  {"ms-win-dns", "MS-RPC windows Domain Naming System"},
		"13:482":  {"ms-iis", "MS-RPC Internet Information Services (IIS)"},
		"13:483":  {"ms-netlogon", "MS-RPC Net Logon, log on management service"},
		"13:484":  {"ms-sms", "Microsoft Systems Management Server"},
		"13:485":  {"vnc-http", "VNC-HTTP is a graphical desktop sharing system that run"},
		"13:486":  {"perforce", "Software Version Management"},
		"13:487":  {"rtmpe", "Encrypted Real Time Messaging Protocol"},
		"13:488":  {"share-point", "SharePoint web application protocol"},
		"13:489":  {"rhapsody", "Online Music Service"},
		"13:490":  {"activesync", "Microsoft Activesync protocolmobile data synchronizatio"},
		"13:491":  {"rtmpt", "Real Time Messaging Protocol tunneled over HTTP"},
		"13:492":  {"dmp", "Cisco Digital Media Player"},
		"13:476":  {"vmware-view", "match UI and login of VMware. Actual desktop data is se"},
		"13:493":  {"vmware-vmotion", "VMware live Migration of Virtual Machines"},
		"13:494":  {"teamviewer", "free remote access and desktop sharing"},
		"13:495":  {"ms-office-365", "Microsoft Office 365"},
		"13:497":  {"ms-update", "Microsoft Update Service"},
		"13:498":  {"ms-live-accounts", "Windows Live Services Authentication"},
		"13:499":  {"gotomypc", "GoToMyPc is a remote control service"},
		"13:500":  {"aol-messenger-audio", "AOL Instant Messenger Audio Calls traffic"},
		"13:501":  {"aol-messenger-video", "AOL Instant Messenger Video Calls traffic"},
		"13:502":  {"aol-messenger-ft", "DEPRECATED, signatures moved to OSCAR File-Transfer"},
		"13:503":  {"ghostsurf", "DEPRECATED, traffic will not match"},
		"13:528":  {"google-accounts", "Google Services Authentication"},
		"13:505":  {"adobe-connect", "web conferencing software"},
		"13:507":  {"realmedia", "RealMedia traffic"},
		"13:508":  {"ms-dynamics-crm-online", "Microsoft Dynamics CRM Online"},
		"13:509":  {"salesforce", "Customer relationship management web application"},
		"13:510":  {"windows-azure", "Microsoft Windows Azure"},
		"13:511":  {"hotmail", "DEPRECATED, traffic will not match. Please check outloo"},
		"13:513":  {"oscar-filetransfer", "OSCAR Protocol File-transfer classification"},
		"13:514":  {"mikogo", "Mikogo is a remote desktop sharing software"},
		"13:515":  {"pandora", "Pandora Internet Radio"},
		"13:516":  {"oracle-ebsuite-unsecured", "Oracle E-Business Suite - Un-encrypted Traffic"},
		"13:517":  {"twitter", "Twitter Microblogging Social Network"},
		"13:518":  {"facebook", "Facebook, social web application and service"},
		"13:519":  {"logmein", "remote-access software for PC and Mobile"},
		"13:520":  {"google-services", "google-services, set of tools and apis used by google a"},
		"13:521":  {"google-plus", "google-plus, social networking web and mobile applicati"},
		"13:522":  {"google-docs", "google-docs, web-based office suite and data storage"},
		"13:523":  {"picasa", "Picasa, social photo sharing web application"},
		"13:525":  {"blogger", "blogger, social blog-publishing service"},
		"13:526":  {"yahoo-mail", "Yahoo! Mail"},
		"13:527":  {"linkedin", "LinkedIn Professional Network"},
		"13:530":  {"gbridge", "Remote Access and file sharing software"},
		"13:531":  {"ms-lync", "MS-Lync, a unified communications platform"},
		"13:532":  {"ms-lync-media", "DEPRECATED, see ms-lync-video and ms-lync-audio"},
		"13:534":  {"showmypc", "Showmypc is a remote control software"},
		"13:535":  {"facetime", "Facetime video calling software"},
		"13:537":  {"xunlei", "Xunlei is a Chinese download manager and p2p client."},
		"13:538":  {"xunlei-kankan", "xunlei-kankan, xunlei-kankan is a chinese download mana"},
		"13:541":  {"spdy", "SPDY is a web content transporting protocol."},
		"13:540":  {"qqlive", "QQLIVE, a video streaming freeware"},
		"13:543":  {"bittorrent-networking", "bittorrent p2p file sharing client networking"},
		"13:544":  {"shoutcast", "SHOUTcast Internet Radio"},
		"13:545":  {"webex-media", "Webex audio, video and file sharing with HTTP-Proxy con"},
		"13:546":  {"webex-app-sharing", "Webex application sharing with HTTP-Proxy configured"},
		"13:547":  {"dameware-mrc", "DameWare Mini Remote Control"},
		"13:549":  {"airplay", "Apple AirPlay wireless media streaming"},
		"13:550":  {"outlook-web-service", "Microsoft Web-Based email services under Outlook brand,"},
		"13:551":  {"espn-browsing", "ESPN related websites browsing and mobile applications"},
		"13:552":  {"espn-video", "ESPN related websites and mobile applications video con"},
		"13:553":  {"whatsapp", "WhatsApp, Text chat and multimedia sharing"},
		"13:554":  {"qq-accounts", "QQ general account login and common traffic"},
		"13:555":  {"modbus", "Industrial Standard Communication Protocol"},
		"13:557":  {"cisco-jabber-im", "Cisco Jabber Client; Instant Messaging"},
		"13:558":  {"cisco-jabber-audio", "Cisco Jabber Client; Audio Calls and Voice Mail"},
		"13:561":  {"cisco-jabber-video", "Cisco Jabber Client; Video Calls"},
		"13:559":  {"ms-lync-audio", "MS Lync Audio flows classification"},
		"13:560":  {"ms-lync-video", "MS Lync video calls classification"},
		"13:556":  {"cisco-jabber-control", "Cisco Jabber Client; Control and Signaling"},
		"13:562":  {"skydrive", "SkyDrive Cloud Storage Server From Microsoft"},
		"13:563":  {"ms-office-web-apps", "Web-based versions of Microsoft Word, Excel, PowerPoint"},
		"13:478":  {"telepresence-data", "telepresence-data stream"},
		"13:5060": {"sip", "Session Initiation Protocol"},
		"13:496":  {"jabber", "Jabber Protocol"},
		"13:5222": {"xmpp-client", "XMPP Client"},
		"13:777":  {"ip-camera", "IP Video Surveillance Camera"},
		"13:778":  {"surveillance-distributio", "Surveillance Distribution"},
	}
	for {
		select {
		case <-n.done:
			return nil
		case read := <-n.readApplication:
			log.Println("D! read application")
			application, ok := applicationTable[read.Key]
			if ok {
				read.Resp <- application
			} else {
				read.Resp <- Application{"unknown", "Unknown"}
			}
		}
	}
}
