package netflow

import (
	"log"
)

type Application struct {
	Name string
	Desc string
}

type ApplicationReadOp struct {
	Key  string
	Resp chan Application
	Fail chan bool
}

func (n *Netflow) applicationPoller() error {
	defer n.wg.Done()
	var applicationTable = map[string]Application{
		"1:8":     Application{"egp", "Exterior Gateway Protocol"},
		"1:47":    Application{"gre", "General Routing Encapsulation"},
		"1:1":     Application{"icmp", "Internet Control Message Protocol"},
		"1:88":    Application{"eigrp", "Enhanced Interior Gateway Routing Protocol"},
		"1:4":     Application{"ipinip", "IP in IP"},
		"1:89":    Application{"ospf", "Open Shortest Path First"},
		"1:115":   Application{"l2tp", "Layer 2 Tunneling Protocol"},
		"1:46":    Application{"rsvp", "Resource Reservation Protocol"},
		"1:0":     Application{"hopopt", "DEPRECATED, traffic will not match"},
		"1:3":     Application{"ggp", "Gateway-to-Gateway"},
		"1:5":     Application{"st", "Stream"},
		"1:7":     Application{"cbt", "CBT"},
		"1:9":     Application{"igrp", "Cisco interior gateway"},
		"1:10":    Application{"bbnrccmon", "BBN RCC Monitoring"},
		"1:11":    Application{"nvp-ii", "Network Voice Protocol"},
		"1:12":    Application{"pup", "PUP"},
		"1:13":    Application{"argus", "ARGUS"},
		"1:14":    Application{"emcon", "EMCON"},
		"1:15":    Application{"xnet", "Cross Net Debugger"},
		"1:16":    Application{"chaos", "Chaos"},
		"1:18":    Application{"mux", "Multiplexing"},
		"1:19":    Application{"dcn-meas", "DCN Measurement Subsystems"},
		"1:20":    Application{"hmp", "Host Monitoring"},
		"1:21":    Application{"prm", "Packet Radio Measurement"},
		"1:22":    Application{"xns-idp", "XEROX NS IDP"},
		"1:23":    Application{"trunk-1", "Trunk-1"},
		"1:24":    Application{"trunk-2", "Trunk-2"},
		"1:25":    Application{"leaf-1", "Leaf-1"},
		"1:26":    Application{"leaf-2", "Leaf-2"},
		"1:27":    Application{"rdp", "Reliable Data Protocol"},
		"1:28":    Application{"irtp", "Internet Reliable Transaction"},
		"1:29":    Application{"iso-tp4", "ISO Transport Protocol Class 4"},
		"1:30":    Application{"netblt", "Bulk Data Transfer Protocol"},
		"1:31":    Application{"mfe-nsp", "MFE Network Services Protocol"},
		"1:32":    Application{"merit-inp", "MERIT Internodal Protocol"},
		"1:34":    Application{"3pc", "Third Party Connect Protocol"},
		"1:35":    Application{"idpr", "Inter-Domain Policy Routing Protocol"},
		"1:36":    Application{"xtp", "XTP"},
		"1:37":    Application{"ddp", "Datagram Delivery Protocol"},
		"1:38":    Application{"idpr-cmtp", "IDPR Control Message Transport Proto"},
		"1:39":    Application{"tp++", ""},
		"1:40":    Application{"il", "IL Transport Protocol"},
		"1:41":    Application{"ipv6inip", "Ipv6 encapsulated"},
		"1:42":    Application{"sdrp", "Source Demand Routing Protocol"},
		"1:43":    Application{"ipv6-route", "DEPRECATED, traffic will not match"},
		"1:44":    Application{"ipv6-frag", "DEPRECATED, traffic will not match"},
		"1:45":    Application{"idrp", "Inter-Domain Routing Protocol"},
		"1:49":    Application{"bna", "BNA"},
		"1:52":    Application{"i-nlsp", "Integrated Net Layer Security TUBA"},
		"1:53":    Application{"swipe", "IP with Encryption"},
		"1:54":    Application{"narp", "NBMA Address Resolution Protocol"},
		"1:55":    Application{"mobile", "IP Mobility"},
		"1:56":    Application{"tlsp", "Transport Layer Security Protocol"},
		"1:57":    Application{"skip", "SKIP"},
		"1:58":    Application{"ipv6-icmp", "ICMP for IPv6"},
		"1:59":    Application{"ipv6-nonxt", "DEPRECATED, traffic will not match"},
		"1:60":    Application{"ipv6-opts", "DEPRECATED, traffic will not match"},
		"1:61":    Application{"any-host-internal", "any host internal protocol"},
		"1:62":    Application{"cftp", "CFTP"},
		"1:64":    Application{"sat-expak", "SATNET and Backroom EXPAK"},
		"1:66":    Application{"rvd", "MIT Remote Virtual Disk Protocol"},
		"1:67":    Application{"ippc", "Internet Pluribus Packet Core"},
		"1:69":    Application{"sat-mon", "SATNET Monitoring"},
		"1:70":    Application{"visa", "VISA Protocol"},
		"1:71":    Application{"ipcv", "Internet Packet Core Utility"},
		"1:72":    Application{"cpnx", "Computer Protocol Network Executive"},
		"1:73":    Application{"cphb", "Computer Protocol Heart Beat"},
		"1:74":    Application{"wsn", "Wang Span Network"},
		"1:75":    Application{"pvp", "Packet Video Protocol"},
		"1:76":    Application{"br-sat-mon", "Backroom SATNET Monitoring"},
		"1:77":    Application{"sun-nd", "SUN ND PROTOCOL-Temporary"},
		"1:78":    Application{"wb-mon", "WIDEBAND Monitoring"},
		"1:79":    Application{"wb-expak", "WIDEBAND EXPAK"},
		"1:81":    Application{"vmtp", "VMTP"},
		"1:82":    Application{"secure-vmtp", "SECURE-VMTP"},
		"1:84":    Application{"ttp", "TTP"},
		"1:85":    Application{"nsfnet-igp", "NSFNET-IGP"},
		"1:86":    Application{"dgp", "Dissimilar Gateway Protocol"},
		"1:87":    Application{"tcf", "TCF"},
		"1:90":    Application{"sprite-rpc", "Sprite RPC Protocol"},
		"1:91":    Application{"larp", "Locus Address Resolution Protocol"},
		"1:92":    Application{"mtp", "Multicast Transport Protocol"},
		"1:93":    Application{"ax25", "AX.25 Frames"},
		"1:94":    Application{"ipip", "IP-within-IP Encapsulation Protocol"},
		"1:95":    Application{"micp", "Mobile Internetworking Control Pro."},
		"1:96":    Application{"scc-sp", "Semaphore Communications Sec. Pro."},
		"1:97":    Application{"etherip", "Ethernet-within-IP Encapsulation"},
		"1:98":    Application{"encap", "Encapsulation Header"},
		"1:100":   Application{"gmtp", "graphical Media Transfer Protocol"},
		"1:101":   Application{"ifmp", "Ipsilon Flow Management Protocol"},
		"1:102":   Application{"pnni", "PNNI over IP"},
		"1:103":   Application{"pim", "Protocol Independent Multicast"},
		"1:104":   Application{"aris", "ARIS"},
		"1:105":   Application{"scps", "SCPS"},
		"1:106":   Application{"qnx", "QNX"},
		"1:107":   Application{"an", "Active Networks"},
		"1:108":   Application{"ipcomp", "IP Payload Compression Protocol"},
		"1:109":   Application{"snp", "Sitara Networks Protocol"},
		"1:110":   Application{"compaq-peer", "Compaq Peer Protocol"},
		"1:111":   Application{"ipx-in-ip", "IPX in IP"},
		"1:112":   Application{"vrrp", "Virtual Router Redundancy Protocol"},
		"1:113":   Application{"pgm", "PGM Reliable Transport Protocol"},
		"1:116":   Application{"ddx", "D-II Data Exchange"},
		"1:117":   Application{"iatp", "Interactive Agent Transfer Protocol"},
		"1:118":   Application{"schedule-transfer", "Schedule Transfer Protocol"},
		"1:119":   Application{"srp", "SpectraLink Radio Protocol"},
		"1:120":   Application{"uti", "UTI"},
		"1:121":   Application{"smp", "Simple Message Protocol"},
		"1:122":   Application{"sm", "SM"},
		"1:123":   Application{"ptp", "Performance Transparency Protocol"},
		"1:124":   Application{"isis", "Intermediate System-to-Intermediate System (ISIS) over"},
		"1:125":   Application{"fire", "FIRE"},
		"1:126":   Application{"crtp", "Combat Radio Transport Protocol"},
		"1:127":   Application{"crudp", "Combat Radio User Datagram"},
		"1:128":   Application{"sscopmce", "SSCOPMCE"},
		"1:129":   Application{"iplt", "IPLT"},
		"1:130":   Application{"sps", "Secure Packet Shield"},
		"1:131":   Application{"pipe", "Private IP Encapsulation within IP"},
		"1:132":   Application{"sctp", "Stream Control Transmission Protocol"},
		"1:133":   Application{"fc", "Fibre Channel"},
		"1:134":   Application{"rsvp-e2e-ignore", "RSVP-E2E-IGNORE"},
		"1:136":   Application{"udplite", "UDPLite, Lightweight connectionless User Datagram Proto"},
		"1:137":   Application{"mpls-in-ip", "MPLS-in-IP"},
		"1:138":   Application{"manet", "MANET Protocols"},
		"1:139":   Application{"hip", "Host Identity Protocol"},
		"1:33":    Application{"dccp", "Datagram Congestion Control Protocol"},
		"1:48":    Application{"dsr", "Dynamic Source Routing Protocol"},
		"3:21":    Application{"ftp", "File Transfer Protocol"},
		"3:80":    Application{"http", "World Wide Web traffic"},
		"3:179":   Application{"bgp", "Border Gateway Protocol"},
		"3:79":    Application{"finger", "Finger"},
		"3:70":    Application{"gopher", "Internet Gopher protocol, online document management."},
		"3:443":   Application{"secure-http", "Secured HTTP or SSL"},
		"3:143":   Application{"imap", "Internet Mail Access Protocol"},
		"3:993":   Application{"secure-imap", "Internet Message Access Protocol over TLS/SSL"},
		"3:194":   Application{"irc", "Internet Relay Chat"},
		"3:994":   Application{"secure-irc", "irc protocol over TLS"},
		"3:88":    Application{"kerberos", "Kerberos Authentication Protocol"},
		"3:389":   Application{"ldap", "Lightweight Directory Access Protocol"},
		"3:636":   Application{"secure-ldap", "ldap protocol over TLS"},
		"3:1433":  Application{"sqlserver", "Microsoft SQL Server"},
		"3:2049":  Application{"nfs", "Network File System"},
		"3:119":   Application{"nntp", "network news transfer protocol"},
		"3:563":   Application{"secure-nntp", "nntp protocol over TLS"},
		"3:123":   Application{"ntp", "Network Time Protocol"},
		"3:110":   Application{"pop3", "Post Office Protocol 3"},
		"3:995":   Application{"secure-pop3", "pop3 protocol over TLS"},
		"3:1723":  Application{"pptp", "Point-to-Point Tunneling Protocol"},
		"3:520":   Application{"rip", "Routing Information Protocol"},
		"3:161":   Application{"snmp", "Simple Network Messaging Protocol"},
		"3:1080":  Application{"socks", "generic proxy protocol for TCP/IP-based networking appl"},
		"3:22":    Application{"ssh", "Secure Shell"},
		"3:23":    Application{"telnet", "Telnet - virtual text-oriented terminal over network"},
		"3:992":   Application{"secure-telnet", "telnet protocol over TLS"},
		"3:990":   Application{"secure-ftp", "ftp protocol, control, over TLS/SSL"},
		"3:6000":  Application{"xwindows", "X-Windows remote access"},
		"3:515":   Application{"printer", "spooler"},
		"3:69":    Application{"tftp", "Trivial File Transfer Protocol"},
		"3:1700":  Application{"sqlnet", "DEPRECATED,traffic will not match"},
		"3:111":   Application{"sunrpc", "SUN Remote Procedure Call"},
		"3:554":   Application{"rtsp", "Real Time Streaming Protocol"},
		"3:5060":  Application{"sip", "Session Initiation Protocol"},
		"3:25":    Application{"smtp", "Simple Mail Transfer Protocol"},
		"3:53":    Application{"dns", "Domain Name Server lookup"},
		"3:3724":  Application{"blizwow", "World of Warcraft Gaming Protocol"},
		"3:63":    Application{"whois++", ""},
		"3:543":   Application{"klogin", "klogin"},
		"3:544":   Application{"kshell", "krcmd"},
		"3:1525":  Application{"ora-srv", "Oracle TCP/IP Listener"},
		"3:9088":  Application{"sqlexec", "SQL Informix"},
		"3:371":   Application{"clearcase", "Rational ClearCase"},
		"3:458":   Application{"appleqtc", "apple quick time"},
		"3:469":   Application{"rcp", "Radio Control Protocol"},
		"3:500":   Application{"isakmp", "Internet Security Association and Key Management Protoc"},
		"3:523":   Application{"ibm-db2", "IBM-DB2"},
		"3:4045":  Application{"lockd", "NFS Lock Daemon Manager"},
		"3:92":    Application{"npp", "Network Printing Protocol"},
		"3:445":   Application{"microsoftds", "Microsoft-DS"},
		"3:666":   Application{"doom", "doom Id Software"},
		"3:7":     Application{"echo", "Echo debugging and measurement tool"},
		"3:11":    Application{"systat", "Active Users"},
		"3:13":    Application{"daytime", "Daytime (RFC 867)"},
		"3:19":    Application{"chargen", "Character Generator"},
		"3:37":    Application{"time", "Time"},
		"3:55":    Application{"isi-gl", "ISI Graphics Language"},
		"3:107":   Application{"rtelnet", "Remote Telnet Service"},
		"3:213":   Application{"server-ipx", "Internetwork Packet Exchange Protocol"},
		"3:177":   Application{"xdmcp", "X Display Manager Control Protocol"},
		"3:43":    Application{"nicname", "Who Is"},
		"3:683":   Application{"corba-iiop", "CORBA Internet Inter-ORB Protocol"},
		"3:49":    Application{"tacacs", "Login Host Protocol"},
		"3:349":   Application{"mftp", "mftp"},
		"3:350":   Application{"matip-type-a", "MATIP Type A"},
		"3:351":   Application{"matip-type-b", "MATIP Type B"},
		"3:352":   Application{"dtag-ste-sb", "DTAG"},
		"3:353":   Application{"ndsauth", "NDSAUTH"},
		"3:355":   Application{"datex-asn", "datex-asn"},
		"3:356":   Application{"cloanto-net-1", "cloanto-net-1"},
		"3:357":   Application{"bhevent", "bhevent"},
		"3:358":   Application{"shrinkwrap", "shrinkwrap"},
		"3:359":   Application{"nsrmp", "Network Security Risk Management Protocol"},
		"3:360":   Application{"scoi2odialog", "scoi2odialog"},
		"3:361":   Application{"semantix", "semantix"},
		"3:362":   Application{"srssend", "srssend"},
		"3:363":   Application{"rsvp_tunnel", "rsvp_tunnel"},
		"3:364":   Application{"aurora-cmgr", "Aurora CMGR"},
		"3:365":   Application{"dtk", "dtk"},
		"3:366":   Application{"odmr", "odmr"},
		"3:367":   Application{"mortgageware", "mortgageware"},
		"3:368":   Application{"qbikgdp", "qbikgdp"},
		"3:369":   Application{"rpc2portmap", "rpc2portmap"},
		"3:370":   Application{"codaauth2", "codaauth2"},
		"3:372":   Application{"ulistproc", "List Processor"},
		"3:373":   Application{"legent-1", "Legent Corporation"},
		"3:374":   Application{"legent-2", "Legent Corporation"},
		"3:375":   Application{"hassle", "hassle"},
		"3:377":   Application{"tnETOS", "NEC Corporation"},
		"3:379":   Application{"is99c", "TIA/EIA/IS-99 modem client"},
		"3:380":   Application{"is99s", "TIA/EIA/IS-99 modem server"},
		"3:381":   Application{"hp-collector", "hp performance data collector"},
		"3:382":   Application{"hp-managed-node", "hp performance data managed node"},
		"3:383":   Application{"hp-alarm-mgr", "hp performance data alarm manager"},
		"3:384":   Application{"arns", "A remote network server system"},
		"3:385":   Application{"ibm-app", "IBM Application"},
		"3:386":   Application{"asa", "ASA Message router object def"},
		"3:387":   Application{"aurp", "AppleTalk Update-Based Routing Pro."},
		"3:388":   Application{"unidata-ldm", "Unidata LDM"},
		"3:347":   Application{"fatserv", "Fatmen Server"},
		"3:390":   Application{"uis", "uis"},
		"3:391":   Application{"synotics-relay", "SynOptics SNMP Relay Port"},
		"3:392":   Application{"synotics-broker", "SynOptics Port Broker Port"},
		"3:393":   Application{"meta5", "meta5"},
		"3:394":   Application{"embl-ndt", "EMBL Nucleic Data Transfer"},
		"3:396":   Application{"netware-ip", "Novell Netware over IP"},
		"3:397":   Application{"mptn", "Multi Protocol Trans. Net"},
		"3:398":   Application{"kryptolan", "kryptolan"},
		"3:399":   Application{"iso-tsap-c2", "ISO Transport Class 2 Non-Control"},
		"3:401":   Application{"ups", "Uninterruptible Power Supply"},
		"3:402":   Application{"genie", "Genie Protocol"},
		"3:403":   Application{"decap", "decap"},
		"3:404":   Application{"nced", "nced"},
		"3:405":   Application{"ncld", "ncld"},
		"3:406":   Application{"imsp", "Interactive Mail Support Protocol"},
		"3:407":   Application{"timbuktu", "Timbuktu"},
		"3:408":   Application{"prm-sm", "Prospero Resource Manager Sys. Man"},
		"3:409":   Application{"prm-nm", "Prospero Resource Manager Node Man"},
		"3:410":   Application{"decladebug", "DECLadebug Remote Debug Protocol"},
		"3:411":   Application{"rmt", "Remote MT Protocol"},
		"3:412":   Application{"synoptics-trap", "Trap Convention Port"},
		"3:413":   Application{"smsp", "Storage Management Services Protocol"},
		"3:414":   Application{"infoseek", "InfoSeek"},
		"3:415":   Application{"bnet", "bnet"},
		"3:417":   Application{"onmux", "onmux"},
		"3:418":   Application{"hyper-g", "hyper-g"},
		"3:419":   Application{"ariel1", "Ariel1"},
		"3:421":   Application{"ariel2", "Ariel2"},
		"3:422":   Application{"ariel3", "Ariel3"},
		"3:423":   Application{"opc-job-start", "IBM Operations Planning and Control Start"},
		"3:424":   Application{"opc-job-track", "IBM Operations Planning and Control Track"},
		"3:426":   Application{"smartsdp", "smartsdp"},
		"3:427":   Application{"svrloc", "Server Location"},
		"3:428":   Application{"ocs_cmu", "ocs_cmu"},
		"3:429":   Application{"ocs_amu", "ocs_amu"},
		"3:430":   Application{"utmpsd", "utmpsd"},
		"3:431":   Application{"utmpcd", "utmpcd"},
		"3:432":   Application{"iasd", "iasd"},
		"3:433":   Application{"nnsp", "nnsp"},
		"3:434":   Application{"mobileip-agent", "mobileip-agent"},
		"3:435":   Application{"mobilip-mn", "mobilip-mn"},
		"3:436":   Application{"dna-cml", "DNA-CML"},
		"3:437":   Application{"comscm", "comscm"},
		"3:438":   Application{"dsfgw", "dsfgw"},
		"3:439":   Application{"dasp", "dasp"},
		"3:440":   Application{"sgcp", "sgcp"},
		"3:441":   Application{"decvms-sysmgt", "decvms-sysmgt"},
		"3:442":   Application{"cvc_hostd", "cvc_hostd"},
		"3:444":   Application{"snpp", "Simple Network Paging Protocol"},
		"3:446":   Application{"ddm-rdb", "DDM-Remote Relational Database Access"},
		"3:447":   Application{"ddm-dfm", "DDM Distributed File management"},
		"3:448":   Application{"ddm-ssl", "DDM-Remote DB Access Using Secure Sockets"},
		"3:449":   Application{"as-servermap", "AS Server Mapper"},
		"3:450":   Application{"tserver", "Computer Supported Telecommunication Applications"},
		"3:451":   Application{"sfs-smp-net", "Cray Network Semaphore server"},
		"3:452":   Application{"sfs-config", "Cray SFS config server"},
		"3:453":   Application{"creativeserver", "creativeserver"},
		"3:3365":  Application{"contentserver", "contentserver"},
		"3:455":   Application{"creativepartnr", "creativepartnr"},
		"3:457":   Application{"scohelp", "scohelp"},
		"3:460":   Application{"skronk", "skronk"},
		"3:461":   Application{"datasurfsrv", "DataRamp Svr"},
		"3:462":   Application{"datasurfsrvsec", "DataRamp Svr svs"},
		"3:463":   Application{"alpes", "Alpes"},
		"3:464":   Application{"kpasswd", "kpasswd"},
		"3:466":   Application{"digital-vrc", "digital-vrc"},
		"3:467":   Application{"mylex-mapd", "mylex-mapd"},
		"3:468":   Application{"photuris", "photuris"},
		"3:470":   Application{"scx-proxy", "scx-proxy"},
		"3:471":   Application{"mondex", "mondex"},
		"3:472":   Application{"ljk-login", "ljk-login"},
		"3:473":   Application{"hybrid-pop", "hybrid-pop"},
		"3:476":   Application{"tn-tl-fd1", "tn-tl-fd1"},
		"3:477":   Application{"ss7ns", "ss7ns"},
		"3:478":   Application{"spsc", "spsc"},
		"3:479":   Application{"iafserver", "iafserver"},
		"3:480":   Application{"iafdbase", "iafdbase"},
		"3:482":   Application{"bgs-nsi", "bgs-nsi"},
		"3:483":   Application{"ulpnet", "ulpnet"},
		"3:484":   Application{"integra-sme", "Integra Software Management Environment"},
		"3:485":   Application{"powerburst", "Air Soft Power Burst"},
		"3:486":   Application{"avian", "avian"},
		"3:487":   Application{"saft", "saft Simple Asynchronous File Transfer"},
		"3:488":   Application{"gss-http", "gss-http"},
		"3:489":   Application{"nest-protocol", "nest-protocol"},
		"3:490":   Application{"micom-pfs", "micom-pfs"},
		"3:491":   Application{"go-login", "go-login"},
		"3:492":   Application{"ticf-1", "Transport Independent Convergence for FNA"},
		"3:493":   Application{"ticf-2", "Transport Independent Convergence for FNA"},
		"3:494":   Application{"pov-ray", "pov-ray"},
		"3:495":   Application{"intecourier", "intecourier"},
		"3:496":   Application{"pim-rp-disc", "PIM-RP-DISC"},
		"3:497":   Application{"dantz", "dantz"},
		"3:498":   Application{"siam", "siam"},
		"3:499":   Application{"iso-ill", "ISO ILL Protocol"},
		"3:501":   Application{"stmf", "stmf"},
		"3:502":   Application{"asa-appl-proto", "asa-appl-proto"},
		"3:503":   Application{"intrinsa", "intrinsa"},
		"3:505":   Application{"mailbox-lm", "mailbox-lm"},
		"3:506":   Application{"ohimsrv", "ohimsrv"},
		"3:507":   Application{"crs", "crs"},
		"3:508":   Application{"xvttp", "xvttp"},
		"3:509":   Application{"snare", "snare"},
		"3:510":   Application{"fcp", "FirstClass Protocol"},
		"3:511":   Application{"passgo", "passgo"},
		"3:512":   Application{"exec", "remote process execution"},
		"3:513":   Application{"login", "Obtain a remote login Terminal"},
		"3:514":   Application{"shell", "Execute a program on remote shell"},
		"3:516":   Application{"videotex", "videotex"},
		"3:517":   Application{"talk", "talk"},
		"3:518":   Application{"ntalk", "ntalk"},
		"3:519":   Application{"utime", "unixtime"},
		"3:521":   Application{"ripng", "Routing information protocol for IPV6 networks"},
		"3:522":   Application{"ulp", "ulp"},
		"3:344":   Application{"pdap", "Prospero Data Access Protocol"},
		"3:524":   Application{"ncp", "Network services Protocol"},
		"3:525":   Application{"timed", "timeserver"},
		"3:526":   Application{"tempo", "newdate"},
		"3:527":   Application{"stx", "Stock IXChange"},
		"3:528":   Application{"custix", "Customer Ixchange"},
		"3:529":   Application{"irc-serv", "IRC-SERV"},
		"3:530":   Application{"courier", "rpc"},
		"3:531":   Application{"conference", "chat"},
		"3:532":   Application{"netnews", "readnews"},
		"3:533":   Application{"netwall", "for emergency broadcasts"},
		"3:535":   Application{"iiop", "iiop"},
		"3:536":   Application{"opalis-rdv", "opalis-rdv"},
		"3:537":   Application{"nmsp", "Networked Media Streaming Protocol"},
		"3:538":   Application{"gdomap", "gdomap"},
		"3:539":   Application{"apertus-ldp", "Apertus Tech Load Distribution"},
		"3:540":   Application{"uucp", "uucpd"},
		"3:541":   Application{"uucp-rlogin", "uucp-rlogin"},
		"3:542":   Application{"commerce", "commerce"},
		"3:545":   Application{"appleqtcsrvr", "appleqtcsrvr"},
		"3:546":   Application{"dhcpv6-client", "DHCPv6 Client"},
		"3:547":   Application{"dhcpv6-server", "DHCPv6 Server"},
		"3:549":   Application{"idfp", "idfp"},
		"3:550":   Application{"new-rwho", "new who"},
		"3:551":   Application{"cybercash", "cybercash"},
		"3:553":   Application{"pirp", "pirp"},
		"3:556":   Application{"remotefs", "rfs server"},
		"3:557":   Application{"openvms-sysipc", "openvms-sysipc"},
		"3:558":   Application{"sdnskmp", "SDNSKMP"},
		"3:559":   Application{"teedtap", "teedtap"},
		"3:560":   Application{"rmonitor", "rmonitord"},
		"3:561":   Application{"monitor", "monitor"},
		"3:562":   Application{"chshell", "chcmd"},
		"3:564":   Application{"9pfs", "Plan 9 file service"},
		"3:565":   Application{"whoami", "whoami"},
		"3:566":   Application{"streettalk", "streettalk"},
		"3:567":   Application{"banyan-rpc", "banyan-rpc"},
		"3:568":   Application{"ms-shuttle", "microsoft shuttle"},
		"3:569":   Application{"ms-rome", "microsoft rome"},
		"3:570":   Application{"meter", "meter"},
		"3:572":   Application{"sonar", "sonar"},
		"3:573":   Application{"banyan-vip", "banyan-vip"},
		"3:574":   Application{"ftp-agent", "FTP Software Agent System"},
		"3:575":   Application{"vemmi", "vemmi"},
		"3:576":   Application{"ipcd", "ipcd"},
		"3:577":   Application{"vnas", "vnas"},
		"3:578":   Application{"ipdd", "ipdd"},
		"3:579":   Application{"decbsrv", "decbsrv"},
		"3:580":   Application{"sntp-heartbeat", "SNTP HEARTBEAT"},
		"3:581":   Application{"bdp", "Bundle Discovery protocol"},
		"3:582":   Application{"scc-security", "scc-security"},
		"3:583":   Application{"philips-vc", "Philips Video-Conferencing"},
		"3:584":   Application{"keyserver", "Key Server"},
		"3:586":   Application{"password-chg", "Password Change"},
		"3:587":   Application{"submission", "submission"},
		"3:590":   Application{"tns-cml", "tns-cml"},
		"3:8080":  Application{"http-alt", "HTTP Alternate"},
		"3:592":   Application{"eudora-set", "Eudora Set"},
		"3:593":   Application{"http-rpc-epmap", "HTTP RPC Ep Map"},
		"3:594":   Application{"tpip", "tpip"},
		"3:595":   Application{"cab-protocol", "CAB Protocol"},
		"3:596":   Application{"smsd", "smsd"},
		"3:597":   Application{"ptcnameservice", "PTC Name Service"},
		"3:598":   Application{"sco-websrvrmg3", "SCO Web Server Manager 3"},
		"3:599":   Application{"acp", "Aeolon Core Protocol"},
		"3:600":   Application{"ipcserver", "Sun IPC server"},
		"3:606":   Application{"urm", "Cray Unified Resource Manager"},
		"3:607":   Application{"nqs", "nqs"},
		"3:608":   Application{"sift-uft", "Sender-Initiated/Unsolicited File Transfer"},
		"3:609":   Application{"npmp-trap", "npmp-trap"},
		"3:610":   Application{"npmp-local", "npmp-local"},
		"3:611":   Application{"npmp-gui", "npmp-gui"},
		"3:612":   Application{"hmmp-ind", "HMMP Indication"},
		"3:613":   Application{"hmmp-op", "HMMP Operation"},
		"3:614":   Application{"sshell", "SSLshell"},
		"3:615":   Application{"sco-inetmgr", "Internet Configuration Manager"},
		"3:616":   Application{"sco-sysmgr", "SCO System Administration Server"},
		"3:617":   Application{"sco-dtmgr", "SCO Desktop Administration Server"},
		"3:618":   Application{"dei-icda", "dei-icda"},
		"3:620":   Application{"sco-websrvrmgr", "SCO Web Server Manager"},
		"3:621":   Application{"escp-ip", "escp-ip"},
		"3:622":   Application{"collaborator", "collaborator"},
		"3:624":   Application{"cryptoadmin", "Crypto Admin"},
		"3:625":   Application{"dec_dlm", "dec_dlm"},
		"3:627":   Application{"passgo-tivoli", "passgo-tivoli"},
		"3:628":   Application{"qmqp", "qmqp"},
		"3:629":   Application{"3com-amp3", "3Com AMP3"},
		"3:630":   Application{"rda", "rda"},
		"3:631":   Application{"ipp", "Internet Printing Protocol"},
		"3:632":   Application{"bmpp", "bmpp"},
		"3:633":   Application{"servstat", "Service Status update"},
		"3:634":   Application{"ginad", "ginad"},
		"3:635":   Application{"rlzdbase", "rlzdbase"},
		"3:637":   Application{"lanserver", "lanserver"},
		"3:638":   Application{"mcns-sec", "mcns-sec"},
		"3:639":   Application{"msdp", "msdp"},
		"3:640":   Application{"entrust-sps", "entrust-sps"},
		"3:641":   Application{"repcmd", "repcmd"},
		"3:642":   Application{"esro-emsdp", "ESRO-EMSDP V1.3"},
		"3:643":   Application{"sanity", "sanity"},
		"3:644":   Application{"dwr", "dwr"},
		"3:646":   Application{"ldp", "LDP"},
		"3:647":   Application{"dhcp-failover", "DHCP Failover"},
		"3:648":   Application{"rrp", "Registry Registrar Protocol"},
		"3:2639":  Application{"aminet", "AMInet"},
		"3:650":   Application{"obex", "obex"},
		"3:651":   Application{"ieee-mms", "ieee-mms"},
		"3:652":   Application{"hello-port", "HELLO_PORT"},
		"3:653":   Application{"repscmd", "repscmd"},
		"3:654":   Application{"aodv", "AODV"},
		"3:655":   Application{"tinc", "tinc"},
		"3:656":   Application{"spmp", "spmp"},
		"3:657":   Application{"rmc", "rmc"},
		"3:658":   Application{"tenfold", "tenfold"},
		"3:660":   Application{"mac-srvr-admin", "MacOS Server Admin"},
		"3:661":   Application{"hap", "hap"},
		"3:662":   Application{"pftp", "pftp"},
		"3:663":   Application{"purenoise", "purenoise"},
		"3:665":   Application{"sun-dr", "sun-dr"},
		"3:667":   Application{"disclose", "campaign contribution disclosures"},
		"3:668":   Application{"mecomm", "mecomm"},
		"3:669":   Application{"meregister", "meregister"},
		"3:670":   Application{"vacdsm-sws", "VACDSM-SWS"},
		"3:671":   Application{"vacdsm-app", "VACDSM-APP"},
		"3:672":   Application{"vpps-qua", "vpps-qua"},
		"3:673":   Application{"cimplex", "cimplex"},
		"3:674":   Application{"acap", "ACAP"},
		"3:675":   Application{"dctp", "dctp"},
		"3:676":   Application{"vpps-via", "vpps-via"},
		"3:677":   Application{"vpp", "Virtual Presence Protocol"},
		"3:678":   Application{"ggf-ncp", "GNU Generation Foundation NCP"},
		"3:679":   Application{"mrm", "mrm"},
		"3:680":   Application{"entrust-aaas", "entrust-aaas"},
		"3:681":   Application{"entrust-aams", "entrust-aams"},
		"3:685":   Application{"mdc-portmapper", "mdc-portmapper"},
		"3:686":   Application{"hcp-wismar", "Hardware Control Protocol Wismar"},
		"3:687":   Application{"asipregistry", "asipregistry"},
		"3:688":   Application{"realm-rusd", "ApplianceWare management protocol"},
		"3:689":   Application{"nmap", "nmap"},
		"3:690":   Application{"vatp", "Velazquez Application Transfer Protocol"},
		"3:691":   Application{"msexch-routing", "MS Exchange Routing"},
		"3:692":   Application{"hyperwave-isp", "hyperwave-isp"},
		"3:693":   Application{"connendp", "almanid Connection Endpoint"},
		"3:694":   Application{"ha-cluster", "ha-cluster"},
		"3:695":   Application{"ieee-mms-ssl", "ieee-mms-ssl"},
		"3:696":   Application{"rushd", "rushd"},
		"3:697":   Application{"uuidgen", "UUIDGEN"},
		"3:698":   Application{"olsr", "olsr"},
		"3:699":   Application{"accessnetwork", "Access Network"},
		"3:704":   Application{"elcsd", "errlog copy/server daemon"},
		"3:705":   Application{"agentx", "AgentX"},
		"3:706":   Application{"silc", "silc"},
		"3:707":   Application{"borland-dsj", "borland-dsj"},
		"3:709":   Application{"entrust-kmsh", "Entrust Key Management Service Handler"},
		"3:710":   Application{"entrust-ash", "Entrust Administration Service Handler"},
		"3:711":   Application{"cisco-tdp", "Cisco TDP"},
		"3:729":   Application{"netviewdm1", "IBM NetView DM"},
		"3:730":   Application{"netviewdm2", "IBM NetView DM"},
		"3:731":   Application{"netviewdm3", "IBM NetView DM"},
		"3:741":   Application{"netgw", "netgw"},
		"3:742":   Application{"netrcs", "Network based RCS"},
		"3:744":   Application{"flexlm", "Flexible License Manager"},
		"3:747":   Application{"fujitsu-dev", "Fujitsu Device Control"},
		"3:748":   Application{"ris-cm", "Russell Info Sci Calendar Manager"},
		"3:749":   Application{"kerberos-adm", "kerberos administration"},
		"3:751":   Application{"pump", "pump"},
		"3:752":   Application{"qrh", "qrh"},
		"3:753":   Application{"rrh", "rrh"},
		"3:754":   Application{"tell", "send"},
		"3:758":   Application{"nlogin", "nlogin"},
		"3:759":   Application{"con", "con"},
		"3:760":   Application{"ns", "ns"},
		"3:761":   Application{"rxe", "rxe"},
		"3:762":   Application{"quotad", "quotad"},
		"3:763":   Application{"cycleserv", "cycleserv"},
		"3:764":   Application{"omserv", "omserv"},
		"3:765":   Application{"webster", "webster"},
		"3:767":   Application{"phonebook", "Phone"},
		"3:769":   Application{"vid", "vid"},
		"3:770":   Application{"cadlock", "cadlock"},
		"3:771":   Application{"rtip", "rtip"},
		"3:772":   Application{"cycleserv2", "cycleserv2"},
		"3:773":   Application{"submit", "Submit Protocol"},
		"3:775":   Application{"entomb", "entomb"},
		"3:777":   Application{"multiling-http", "Multiling HTTP"},
		"3:780":   Application{"wpgs", "wpgs"},
		"3:801":   Application{"device", "device"},
		"3:828":   Application{"itm-mcell-s", "itm-mcell-s"},
		"3:829":   Application{"pkix-3-ca-ra", "PKIX-3 CA/RA"},
		"3:847":   Application{"dhcp-failover2", "dhcp-failover2"},
		"3:873":   Application{"rsync", "rsync"},
		"3:886":   Application{"iclcnet-locate", "ICL coNETion locate server"},
		"3:887":   Application{"iclcnet_svinfo", "ICL coNETion server info"},
		"3:888":   Application{"accessbuilder", "Access Builder"},
		"3:900":   Application{"omginitialrefs", "omginitialrefs"},
		"3:901":   Application{"smpnameres", "smpnameres"},
		"3:911":   Application{"xact-backup", "xact-backup"},
		"3:989":   Application{"ftps-data", "ftp protocol, data, over TLS/SSL"},
		"3:991":   Application{"nas", "Netnews Administration System"},
		"3:996":   Application{"vsinet", "vsinet"},
		"3:997":   Application{"maitrd", "maitrd"},
		"3:1010":  Application{"surf", "surf"},
		"3:1098":  Application{"rmiactivation", "rmiactivation"},
		"3:1099":  Application{"rmiregistry", "rmiregistry"},
		"3:156":   Application{"sqlsrv", "SQL Service"},
		"3:1434":  Application{"ms-sql-m", "Microsoft-SQL-Monitor"},
		"3:2393":  Application{"ms-olap", "Microsoft OLAP"},
		"3:3268":  Application{"msft-gc", "Microsoft Global Catalog"},
		"3:3269":  Application{"msft-gc-ssl", "Microsoft Global Catalog with LDAP/SSL"},
		"3:3389":  Application{"ms-wbt", "Microsoft Windows based Terminal Services"},
		"3:1527":  Application{"tlisrv", "oracle"},
		"3:1529":  Application{"coauthor", "oracle"},
		"3:1571":  Application{"rdb-dbs-disp", "Oracle Remote Data Base"},
		"3:1575":  Application{"oraclenames", "oraclenames"},
		"3:1630":  Application{"oraclenet8cman", "Oracle Net8 Cman"},
		"3:1830":  Application{"net8-cman", "Oracle Net8 CMan Admin"},
		"3:1534":  Application{"micromuse-lm", "micromuse-lm"},
		"3:3075":  Application{"orbix-locator", "Orbix 2000 Locator"},
		"3:3076":  Application{"orbix-config", "Orbix 2000 Config"},
		"3:3077":  Application{"orbix-loc-ssl", "Orbix 2000 Locator SSL"},
		"3:1626":  Application{"shockwave", "Shockwave"},
		"3:2629":  Application{"sitaraserver", "sitaraserver"},
		"3:2630":  Application{"sitaramgmt", "sitaramgmt"},
		"3:2631":  Application{"sitaradir", "sitaradir"},
		"3:3306":  Application{"mysql", "database management system"},
		"3:3300":  Application{"net-assistant", "DEPRECATED,traffic will not match"},
		"3:1863":  Application{"msnp", "msnp"},
		"3:2492":  Application{"groove", "groove"},
		"3:2234":  Application{"directplay", "DirectPlay"},
		"3:6073":  Application{"directplay8", "DirectPlay8"},
		"3:2213":  Application{"kali", "kali"},
		"3:2595":  Application{"worldfusion", "World Fusion"},
		"3:3334":  Application{"directv-web", "Direct TV Webcasting"},
		"3:3335":  Application{"directv-soft", "Direct TV Software Updates"},
		"3:3336":  Application{"directv-tick", "Direct TV Tickers"},
		"3:3337":  Application{"directv-catlg", "Direct TV Data Catalog"},
		"3:2948":  Application{"wap-push", "WAP PUSH"},
		"3:2949":  Application{"wap-pushsecure", "WAP PUSH SECURE"},
		"3:4035":  Application{"wap-push-http", "WAP Push OTA-HTTP port"},
		"3:4036":  Application{"wap-push-https", "WAP Push OTA-HTTP secure"},
		"3:9200":  Application{"wap-wsp", "WAP connectionless session service"},
		"3:9201":  Application{"wap-wsp-wtp", "WAP session service"},
		"3:9202":  Application{"wap-wsp-s", "WAP secure connectionless session service"},
		"3:9203":  Application{"wap-wsp-wtp-s", "WAP secure session service"},
		"3:9204":  Application{"wap-vcard", "WAP vCard"},
		"3:9205":  Application{"wap-vcal", "WAP vCal"},
		"3:9206":  Application{"wap-vcard-s", "WAP vCard Secure"},
		"3:9207":  Application{"wap-vcal-s", "WAP vCal Secure"},
		"3:6714":  Application{"ibprotocol", "Internet Backplane Protocol"},
		"3:1812":  Application{"radius", "Remote Authentication Dial In User Service protocol"},
		"3:2152":  Application{"gtp-user", "GTP-User Plane"},
		"3:3088":  Application{"xdtp", "eXtensible Data Transfer Protocol"},
		"3:6582":  Application{"parsec-game", "Parsec Gameserver"},
		"3:346":   Application{"zserv", "Zebra server"},
		"3:345":   Application{"pawserv", "Perf Analysis Workbench"},
		"3:333":   Application{"texar", "Texar Security Port"},
		"3:322":   Application{"rtsps", "RTSPS"},
		"3:1321":  Application{"pip", "pip"},
		"3:320":   Application{"ptp-general", "PTP General"},
		"3:3478":  Application{"stun-nat", "Session Traversal Utilities for NAT (STUN)"},
		"3:2":     Application{"compressnet", "Management Utility"},
		"3:5":     Application{"rje", "Remote Job Entry"},
		"3:9":     Application{"discard", "Discard"},
		"3:17":    Application{"qotd", "Quote of the Day"},
		"3:18":    Application{"msp", "Message Send Protocol"},
		"3:20":    Application{"ftp-data", "File Transfer Protocol, Data part only"},
		"3:27":    Application{"nsw-fe", "NSW User System FE"},
		"3:29":    Application{"msg-icp", "msg-icp"},
		"3:348":   Application{"csi-sgwp", "Cabletron Management Protocol"},
		"3:31":    Application{"msg-auth", "msg-auth"},
		"3:33":    Application{"dsp", "Display Support Protocol"},
		"3:38":    Application{"rap", "Route Access Protocol"},
		"3:39":    Application{"rlp", "Resource Location Protocol"},
		"3:41":    Application{"graphics", "Graphics"},
		"3:42":    Application{"name", "Host Name Server"},
		"3:136":   Application{"profile", "PROFILE Naming System"},
		"3:44":    Application{"mpm-flags", "MPM FLAGS Protocol"},
		"3:45":    Application{"mpm", "Message Processing Module"},
		"3:46":    Application{"mpm-snd", "MPM [default send]"},
		"3:47":    Application{"ni-ftp", "NI FTP"},
		"3:48":    Application{"auditd", "Digital Audit daemon"},
		"3:140":   Application{"emfis-data", "EMFIS Data Service"},
		"3:50":    Application{"re-mail-ck", "Remote Mail Checking Protocol"},
		"3:51":    Application{"la-maint", "IMP Logical Address Maintenance"},
		"3:52":    Application{"xns-time", "XNS Time Protocol"},
		"3:141":   Application{"emfis-cntl", "EMFIS Control Service"},
		"3:54":    Application{"xns-ch", "XNS Clearinghouse"},
		"3:142":   Application{"bl-idm", "Britton Lee IDM"},
		"3:56":    Application{"xns-auth", "XNS Authentication"},
		"3:58":    Application{"xns-mail", "XNS mail"},
		"3:61":    Application{"ni-mail", "NI MAIL"},
		"3:62":    Application{"acas", "ACA Services"},
		"3:64":    Application{"covia", "Communications Integrator"},
		"3:145":   Application{"uaac", "UAAC Protocol"},
		"3:146":   Application{"iso-tp0", "iso-tp0"},
		"3:71":    Application{"netrjs-1", "Remote Job Service"},
		"3:72":    Application{"netrjs-2", "Remote Job Service"},
		"3:73":    Application{"netrjs-3", "Remote Job Service"},
		"3:74":    Application{"netrjs-4", "Remote Job Service"},
		"3:76":    Application{"deos", "Distributed External Object Store"},
		"3:147":   Application{"iso-ip", "iso-ip"},
		"3:82":    Application{"xfer", "XFER Utility"},
		"3:83":    Application{"mit-ml-dev", "MIT ML Device"},
		"3:84":    Application{"ctf", "Common Trace Facility"},
		"3:86":    Application{"mfcobol", "Micro Focus Cobol"},
		"3:148":   Application{"jargon", "Jargon"},
		"3:89":    Application{"su-mit-tg", "SU/MIT Telnet Gateway"},
		"3:90":    Application{"dnsix", "DNSIX Security Attribute Token Map"},
		"3:91":    Application{"mit-dov", "MIT Dover Spooler"},
		"3:149":   Application{"aed-512", "AED 512 Emulation service"},
		"3:93":    Application{"dcp", "Device Control Protocol"},
		"3:94":    Application{"objcall", "Tivoli Object Dispatcher"},
		"3:95":    Application{"supdup", "SUPDUP"},
		"3:96":    Application{"dixie", "DIXIE Protocol Specification"},
		"3:97":    Application{"swift-rvf", "Swift Remote Virtual File Protocol"},
		"3:98":    Application{"tacnews", "TAC News"},
		"3:99":    Application{"metagram", "metagram"},
		"3:101":   Application{"hostname", "NIC Host Name Server"},
		"3:102":   Application{"iso-tsap", "ISO-TSAP Class 0"},
		"3:104":   Application{"acr-nema", "ACR-NEMA Digital Img"},
		"3:105":   Application{"csnet-ns", "Mailbox Name Nameserver"},
		"3:106":   Application{"3com-tsmux", "3Com TSMUX"},
		"3:150":   Application{"sql-net", "SQL-NET"},
		"3:108":   Application{"snagas", "SNA Gateway Access Server"},
		"3:109":   Application{"pop2", "Post Office Protocol - Version 2"},
		"3:151":   Application{"hems", "hems"},
		"3:112":   Application{"mcidas", "McIDAS Data Transmission Protocol"},
		"3:113":   Application{"auth", "Authentication Service"},
		"3:115":   Application{"sftp", "Simple File Transfer Protocol"},
		"3:116":   Application{"ansanotify", "ANSA REX Notify"},
		"3:117":   Application{"uucp-path", "UUCP Path Service"},
		"3:118":   Application{"sqlserv", "SQL Services"},
		"3:120":   Application{"cfdptkt", "cfdptkt"},
		"3:121":   Application{"erpc", "Encore Expedited Remote Pro.Call"},
		"3:122":   Application{"smakynet", "smakynet"},
		"3:152":   Application{"bftp", "Background File Transfer Program"},
		"3:124":   Application{"ansatrader", "ansatrader"},
		"3:125":   Application{"locus-map", "Locus PC-Interface Net Map Server"},
		"3:126":   Application{"nxedit", "nxedit"},
		"3:127":   Application{"locus-con", "Locus PC-Interface Conn Server"},
		"3:128":   Application{"gss-xlicen", "GNU Generation Foundation NCP"},
		"3:129":   Application{"pwdgen", "Password Generator Protocol"},
		"3:130":   Application{"cisco-fna", "cisco FNATIVE"},
		"3:153":   Application{"sgmp", "sgmp"},
		"3:154":   Application{"netsc-prod", "NETSC"},
		"3:155":   Application{"netsc-dev", "NETSC"},
		"3:157":   Application{"knet-cmp", "KNET/VM Command/Message Protocol"},
		"3:158":   Application{"pcmail-srv", "PCMail Server"},
		"3:159":   Application{"nss-routing", "NSS-Routing"},
		"3:160":   Application{"sgmp-traps", "sgmp-traps"},
		"3:163":   Application{"cmip-man", "CMIP/TCP Manager"},
		"3:164":   Application{"cmip-agent", "CMIP/TCP Agent"},
		"3:165":   Application{"xns-courier", "Xerox"},
		"3:166":   Application{"s-net", "Sirius Systems"},
		"3:167":   Application{"namp", "namp"},
		"3:168":   Application{"rsvd", "rsvd"},
		"3:169":   Application{"send", "SEND"},
		"3:170":   Application{"print-srv", "Network PostScript"},
		"3:171":   Application{"multiplex", "Network Innovations Multiplex"},
		"3:173":   Application{"xyplex-mux", "Xyplex"},
		"3:174":   Application{"mailq", "MAILQ"},
		"3:175":   Application{"vmnet", "vmnet"},
		"3:176":   Application{"genrad-mux", "genrad-mux"},
		"3:178":   Application{"nextstep", "NextStep Window Server"},
		"3:180":   Application{"ris", "Intergraph"},
		"3:181":   Application{"unify", "Unify"},
		"3:182":   Application{"audit", "Unisys Audit SITP"},
		"3:183":   Application{"ocbinder", "ocbinder"},
		"3:184":   Application{"ocserver", "ocserver"},
		"3:185":   Application{"remote-kis", "remote-kis"},
		"3:186":   Application{"kis", "KIS Protocol"},
		"3:188":   Application{"mumps", "Plus Fives MUMPS"},
		"3:189":   Application{"qft", "Queued File Transport"},
		"3:190":   Application{"gacp", "Gateway Access Control Protocol"},
		"3:191":   Application{"prospero", "Prospero Directory Service"},
		"3:192":   Application{"osu-nms", "OSU Network Monitoring System"},
		"3:193":   Application{"srmp", "Spider Remote Monitoring Protocol"},
		"3:195":   Application{"dn6-nlm-aud", "DNSIX Network Level Module Audit"},
		"3:197":   Application{"dls", "Directory Location Service"},
		"3:198":   Application{"dls-mon", "Directory Location Service Monitor"},
		"3:199":   Application{"smux", "SMUX"},
		"3:200":   Application{"src", "IBM System Resource Controller"},
		"3:201":   Application{"at-rtmp", "AppleTalk Routing Maintenance"},
		"3:202":   Application{"at-nbp", "AppleTalk Name Binding"},
		"3:203":   Application{"at-3", "AppleTalk Unused"},
		"3:204":   Application{"at-echo", "AppleTalk Echo"},
		"3:205":   Application{"at-5", "AppleTalk Unused"},
		"3:206":   Application{"at-zis", "AppleTalk Zone Information"},
		"3:207":   Application{"at-7", "AppleTalk Unused"},
		"3:208":   Application{"at-8", "AppleTalk Unused"},
		"3:209":   Application{"qmtp", "The Quick Mail Transfer Protocol"},
		"3:210":   Application{"z39.50", ""},
		"3:211":   Application{"914c/g", ""},
		"3:212":   Application{"anet", "ATEXSSTR"},
		"3:214":   Application{"vmpwscs", "vmpwscs"},
		"3:215":   Application{"softpc", "Insignia Solutions"},
		"3:216":   Application{"CAIlic", "Computer Associates Intl License Server"},
		"3:217":   Application{"dbase", "dBASE Unix"},
		"3:218":   Application{"mpp", "Netix Message Posting Protocol"},
		"3:219":   Application{"uarps", "Unisys ARPs"},
		"3:221":   Application{"fln-spx", "Berkeley rlogind with SPX auth"},
		"3:222":   Application{"rsh-spx", "Berkeley rshd with SPX auth"},
		"3:223":   Application{"cdc", "Certificate Distribution Center"},
		"3:224":   Application{"masqdialer", "masqdialer"},
		"3:243":   Application{"sur-meas", "Survey Measurement"},
		"3:244":   Application{"inbusiness", "inbusiness"},
		"3:246":   Application{"dsp3270", "Display Systems Protocol"},
		"3:247":   Application{"subntbcst_tftp", "subntbcst_tftp"},
		"3:248":   Application{"bhfhs", "bhfhs"},
		"3:257":   Application{"set", "Secure Electronic Transaction"},
		"3:259":   Application{"esro-gen", "Efficient Short Remote Operations"},
		"3:260":   Application{"openport", "openport"},
		"3:261":   Application{"nsiiops", "IIOP Name Service over TLS/SSL"},
		"3:262":   Application{"arcisdms", "arcisdms"},
		"3:263":   Application{"hdap", "hdap"},
		"3:264":   Application{"bgmp", "BGMP"},
		"3:265":   Application{"x-bone-ctl", "Xbone CTL"},
		"3:266":   Application{"sst", "SCSI on ST"},
		"3:267":   Application{"td-service", "Tobit David Service Layer"},
		"3:268":   Application{"td-replica", "Tobit David Replica"},
		"3:280":   Application{"http-mgmt", "http-mgmt"},
		"3:281":   Application{"personal-link", "personal-link"},
		"3:282":   Application{"cableport-ax", "Cable Port A/X"},
		"3:283":   Application{"rescap", "rescap"},
		"3:284":   Application{"corerjd", "corerjd"},
		"3:287":   Application{"k-block", "k-block"},
		"3:308":   Application{"novastorbakcup", "Novastor Backup"},
		"3:310":   Application{"bhmds", "bhmds"},
		"3:311":   Application{"asip-webadmin", "AppleShare IP WebAdmin"},
		"3:312":   Application{"vslmp", "vslmp"},
		"3:313":   Application{"magenta-logic", "magenta-logic"},
		"3:314":   Application{"opalis-robot", "opalis-robot"},
		"3:315":   Application{"dpsi", "dpsi"},
		"3:316":   Application{"decauth", "decauth"},
		"3:317":   Application{"zannet", "zannet"},
		"3:318":   Application{"pkix-timestamp", "pkix-timestamp"},
		"3:319":   Application{"ptp-event", "PTP Event"},
		"3:131":   Application{"cisco-tna", "cisco TNATIVE"},
		"3:132":   Application{"cisco-sys", "cisco SYSMAINT"},
		"3:133":   Application{"statsrv", "Statistics Service"},
		"3:134":   Application{"ingres-net", "INGRES-NET Service"},
		"3:6085":  Application{"Konspire2b", "konspire2b p2p network"},
		"3:5246":  Application{"capwap-control", "Control And Provisioning of Wireless Access Points Cont"},
		"3:5190":  Application{"aol-protocol", "America OnLine software suite"},
		"3:135":   Application{"epmap", "DCE endpoint resolution"},
		"3:2811":  Application{"gsiftp", "GSI FTP"},
		"3:5349":  Application{"stuns", "STUN over TLS"},
		"3:5222":  Application{"xmpp-client", "Extensible Messaging and Presence Protocol (XMPP) Clien"},
		"3:5247":  Application{"capwap-data", "Control And Provisioning of Wireless Access Points Data"},
		"3:548":   Application{"afpovertcp", "AFP over TCP"},
		"3:8211":  Application{"aruba-papi", "Aruba access point manager"},
		"3:4569":  Application{"iax", "Inter-Asterisk eXchange"},
		"3:47808": Application{"bacnet", "Building Automation and Control Networks"},
		"3:1984":  Application{"bb", "Big Brother network monitoring tool"},
		"3:18190": Application{"checkpoint-cpmi", "Check Point Management Interface"},
		"3:8905":  Application{"cisco-nac", "Cisco Network Access Control (NAC) system"},
		"3:6499":  Application{"cooltalk", "Internet telephony tool"},
		"3:2301":  Application{"cpq-wbem", "Compaq HTTP"},
		"3:2401":  Application{"cvspserver", "CVS pserver"},
		"3:5999":  Application{"cvsup", "Cvsup"},
		"3:52300": Application{"desknets", "Groupware application for resource sharing"},
		"3:3632":  Application{"distcc", "Distributed Compiler"},
		"3:20000": Application{"dnp", "Distributed Network Protocol (DNP3) over TCP"},
		"3:3218":  Application{"smartpackets", "EMC SmartPackets"},
		"3:3050":  Application{"gds_db", "GDS DataBase"},
		"3:19150": Application{"gkrellm", "Monitoring program"},
		"3:5325":  Application{"goboogy", "P2P file sharing"},
		"3:2217":  Application{"gotodevice", "Online device management application"},
		"3:1677":  Application{"groupwise", "Groupwise messaging and groupware platform"},
		"3:20016": Application{"hitachi-spc", "Hitachi Universal Storage Platform"},
		"3:3260":  Application{"iscsi-target", "Internet Small Computer System Interface"},
		"3:4514":  Application{"loglogic", "Log and security management"},
		"3:7210":  Application{"maxdb", "MaxDB relational database management system"},
		"3:8801":  Application{"mcafee-update", "Update client of McAfee-computer security software"},
		"3:1755":  Application{"ms-streaming", "Microsoft media services"},
		"3:6891":  Application{"ms-ocs-file-transfer", "Microsoft Office Communications Server and File Transfe"},
		"3:10000": Application{"ndmp", "Network Data Management Protocol"},
		"3:33435": Application{"netvmg-traceroute", "Routing diagnostics tool"},
		"3:9703":  Application{"oracle-bi", "Oracle Business Intelligence"},
		"3:2351":  Application{"psrserver", "Pharos psrserver"},
		"3:5432":  Application{"postgresql", "PostgreSQL database"},
		"3:4899":  Application{"radmin-port", "Remote Admin"},
		"3:6970":  Application{"rdt", "Real Data Transport"},
		"3:6343":  Application{"sflow", "Sflow traffic monitoring"},
		"3:19880": Application{"softros-messenger-ft", "Softros LAN Messenger and File Transfer"},
		"3:3690":  Application{"svn", "Apache subversion software revision control"},
		"3:27665": Application{"trinoo", "Set of computer programs to conduct a DDoS attack"},
		"3:15868": Application{"websense", "Web filtering software"},
		"3:7100":  Application{"font-service", "X font service"},
		"3:25999": Application{"xfire", "Freeware instant messaging service"},
		"3:3817":  Application{"tapeware", "Yosemite tech tapeware"},
		"3:2160":  Application{"apc-powerchute", "American Power Conversion"},
		"3:9022":  Application{"applejuice", "Apple juice P2P file sharing"},
		"3:3211":  Application{"avocent", "Secure management and installation discovery"},
		"3:20500": Application{"call-of-duty", "Call of duty online gaming"},
		"3:8880":  Application{"cddbp-alt", "CD Data base Protocol"},
		"3:6305":  Application{"dclink", "Automated Data Collection Solution"},
		"3:2189":  Application{"esignal", "Real-time market data and decision support tools"},
		"3:2399":  Application{"filemaker-announcement", "Filemaker relational database application"},
		"3:12975": Application{"hamachi", "Shareware VPN application"},
		"3:7220":  Application{"heroix-longitude", "Network performance monitoring software"},
		"3:9100":  Application{"hp-pdl-datastr", "PDL data streaming port"},
		"3:1533":  Application{"virtual-places", "Virtual places software"},
		"3:6997":  Application{"MobilitySrv", "Mobility XE protocol"},
		"3:1270":  Application{"opsmgr", "Microsoft Operations Manager"},
		"3:5723":  Application{"omhs", "Operations Manager - Health Service"},
		"3:1521":  Application{"ncube-lm", "Ncube License Manager"},
		"3:1498":  Application{"sybase", "Database management system"},
		"3:40001": Application{"teamsound", "Voice conferencing software for online game"},
		"3:7631":  Application{"tesla-sys-msg", "TESLA System Messaging"},
		"3:11010": Application{"tradestation", "Technical analysis software"},
		"3:8182":  Application{"vmware-fdm", "VMware Fault Domain Manager"},
		"3:5330":  Application{"war-rock", "War-rock online gaming"},
		"3:2048":  Application{"wccp", "Web Cache Communication Protocol"},
		"3:2887":  Application{"wlccp", "Wireless LAN Context Control Protocol"},
		"3:4490":  Application{"ibm-director", "Element management system"},
		"3:1970":  Application{"netop-remote-control", "Remote control management and support software"},
		"3:6665":  Application{"p10", "Internet relay chat"},
		"3:137":   Application{"netbios-ns", "NetBIOS Naming Service"},
		"3:1698":  Application{"rsvp-encap-1", "Resource Reservation Protocol"},
		"3:1699":  Application{"rsvp-encap-2", "Resource Reservation Protocol"},
		"3:66":    Application{"oracle-sqlnet", "SQL*NET for Oracle"},
		"3:4172":  Application{"pcoip", "PC-over-IP - Virtual Desktop Infrastructure"},
		"3:5061":  Application{"sip-tls", "Secure Session Initiation Protocol tunneled in SSL or T"},
		"3:1604":  Application{"citrix-static", "Citrix Static"},
		"3:860":   Application{"iscsi", "Internet Small Computer System Interface"},
		"3:1352":  Application{"lotus-notes", "IBM Lotus Notes collaborative client-server platform"},
		"3:3283":  Application{"apple-remote-desktop", "Apple Remote Desktop"},
		"3:17500": Application{"dropbox", "Dropbox, file hosting service"},
		"3:10080": Application{"amanda", "Advanced Maryland Automatic Network Disk Archiver"},
		"13:0":    Application{"unclassified", "Unclassified traffic"},
		"13:1":    Application{"unknown", "Unknown application"},
		"13:9":    Application{"ipsec", "IPSec traffic"},
		"13:12":   Application{"cuseeme", "CU-SeeMe desktop video conference"},
		"13:13":   Application{"dhcp", "Dynamic Host Configuration Protocol"},
		"13:26":   Application{"netbios", "netbios"},
		"13:2000": Application{"notes", "DEPRECATED, traffic will not match. Please use lotus-no"},
		"13:32":   Application{"pcanywhere", "Symantec pcAnywhere remote desktop"},
		"13:41":   Application{"syslog", "System Logging Utility"},
		"13:47":   Application{"novadigm", "Novadigm EDM"},
		"13:49":   Application{"exchange", "MS-Exchange"},
		"13:425":  Application{"vdolive", "VDOLive streaming video"},
		"13:426":  Application{"netshow", "Microsoft Netshow, media streaming protocol"},
		"13:427":  Application{"streamwork", "Xing Technology StreamWorks player"},
		"13:56":   Application{"citrix", "Citrix Systems Metaframe 3.0"},
		"13:57":   Application{"fasttrack", "DEPRECATED, traffic will not match"},
		"13:58":   Application{"gnutella", "Gnutella Version2 Traffic, peer-to-peer file-sharing pr"},
		"13:59":   Application{"kazaa2", "DEPRECATED, traffic will not match"},
		"13:61":   Application{"rtp", "Real Time Protocol"},
		"13:62":   Application{"mgcp", "Media Gateway Control Protocol"},
		"13:63":   Application{"skinny", "Skinny Call Control Protocol"},
		"13:64":   Application{"h323", "H323 Protocol"},
		"13:66":   Application{"rtcp", "Real Time Control Protocol"},
		"13:67":   Application{"edonkey", "eDonkey p2p file sharing client"},
		"13:68":   Application{"winmx", "WinMx file-sharing application"},
		"13:69":   Application{"bittorrent", "bittorrent p2p file sharing client"},
		"13:70":   Application{"directconnect", "Direct Connect Version 2.0, peer-to-peer file sharing p"},
		"13:73":   Application{"hl7", "Health Level Seven protocol, information exchanging bet"},
		"13:74":   Application{"fix", "Financial Information eXchange Protocol"},
		"13:75":   Application{"msn-messenger", "MSN Messenger IM, Status Messages, News and Gaming"},
		"13:76":   Application{"dicom", "Digital Imaging and Communication in Medicine"},
		"13:77":   Application{"yahoo-messenger", "Yahoo Messenger, Instant Messaging Client"},
		"13:78":   Application{"mapi", "Messaging Application Programming Interface"},
		"13:79":   Application{"aol-messenger", "AOL Instant Messenger Text Chat"},
		"13:80":   Application{"cifs", "common internet file system"},
		"13:81":   Application{"cisco-phone", "Cisco IP Phones and PC-based Unified Communicators"},
		"13:82":   Application{"youtube", "Youtube, video streaming"},
		"13:83":   Application{"skype", "Skype Peer-to-Peer Internet Telephony Protocol"},
		"13:84":   Application{"sap", "SAP Systems Applications Product in Data processing"},
		"13:100":  Application{"vnc", "Virtual Network Computing"},
		"13:113":  Application{"telepresence-media", "Cisco Telepresence-media"},
		"13:114":  Application{"telepresence-control", "Cisco Telepresence-control"},
		"13:428":  Application{"zattoo", "Peer-to-Peer Internet Video Protocol"},
		"13:429":  Application{"sopcast", "Free P2P internet TV"},
		"13:299":  Application{"flash-video", "Flash video streams"},
		"13:301":  Application{"flashyahoo", "Flash streams at yahoo"},
		"13:300":  Application{"flashmyspace", "Flash streams at myspace.com"},
		"13:430":  Application{"audio-over-http", "Audio traffic over HTTP"},
		"13:431":  Application{"binary-over-http", "Binary traffic over HTTP"},
		"13:432":  Application{"video-over-http", "Video traffic over HTTP"},
		"13:420":  Application{"networking-gnutella", "Gnutella-networking Version2 Traffic"},
		"13:469":  Application{"winny", "winny2 and winnyP traffic, peer-to-peer file sharing pr"},
		"13:266":  Application{"manolito", "Free secure P2P file sharing"},
		"13:267":  Application{"soulseek", "P2P file sharing application"},
		"13:433":  Application{"filetopia", "Secure P2P file sharing application"},
		"13:434":  Application{"itunes", "Organize and play media application"},
		"13:268":  Application{"napster", "Commercial Media Distribution Application"},
		"13:421":  Application{"waste", "encrypted file sharing client"},
		"13:542":  Application{"pptv", "P2P video streaming app"},
		"13:422":  Application{"yahoo-voip-messenger", "Free P2P calls"},
		"13:264":  Application{"applix", "Applix ac"},
		"13:423":  Application{"ppstream", "P2P video streaming application"},
		"13:424":  Application{"poco", "P2P file sharing Software"},
		"13:435":  Application{"tunnel-http", "HTTP Tunneling"},
		"13:436":  Application{"guruguru", "DEPRECATED, traffic will not match"},
		"13:437":  Application{"kuro", "Japanese file sharing client"},
		"13:438":  Application{"soribada", "a Korean P2P music sharing protocol"},
		"13:417":  Application{"encrypted-emule", "P2P file sharing encrypted protocol"},
		"13:439":  Application{"dht", "Distributed sloppy Hash Table protocol"},
		"13:440":  Application{"sling", "SlingBox Internet TV"},
		"13:441":  Application{"google-earth", "Location Based Service"},
		"13:269":  Application{"icq", "I seek you (ICQ), Instant Messaging Protocol"},
		"13:470":  Application{"gtalk", "Base google-talk protocol"},
		"13:60":   Application{"fring-video", "Fring Video, video conversations on mobiles"},
		"13:328":  Application{"secondlife", "SecondLife traffic"},
		"13:331":  Application{"tcpoverdns", "TCP over DNS traffic"},
		"13:442":  Application{"baidu-movie", "Internet TV"},
		"13:443":  Application{"pando", "Peer-to-Peer File-Sharing"},
		"13:54":   Application{"fring", "Fring IM setups and Ads"},
		"13:444":  Application{"fring-voip", "Fring Voip, voice conversations on mobiles over IP"},
		"13:445":  Application{"webthunder", "Peer-to-Peer File-Sharing"},
		"13:454":  Application{"babelgum", "Internet TV web platform"},
		"13:418":  Application{"rtmp", "Real Time Messaging Protocol"},
		"13:446":  Application{"ventrilo", "Ventrilo VOIP and chat protocol"},
		"13:447":  Application{"teamspeak", "Voice communication protocol"},
		"13:462":  Application{"gmail", "Gmail and Gmail-chat traffic"},
		"13:533":  Application{"yahoo-accounts", "Yahoo Accounts"},
		"13:448":  Application{"maplestory", "Maple Story Gaming Protocol"},
		"13:449":  Application{"tomatopang", "Tomatopang Peer-to-Peer File Sharing"},
		"13:450":  Application{"songsari", "Songsari P2P File Sharing"},
		"13:473":  Application{"active-directory", "Active Directory Traffic"},
		"13:302":  Application{"yahoo-voip-over-sip", "Yahoo VoIP over SIP"},
		"13:305":  Application{"gtalk-voip", "Google Talk voice"},
		"13:308":  Application{"gtalk-ft", "Google Talk File Transfer"},
		"13:309":  Application{"msn-messenger-ft", "MSN Messenger file transfer"},
		"13:311":  Application{"icq-filetransfer", "DEPRECATED, signatures moved to OSCAR File-Transfer"},
		"13:312":  Application{"my-jabber-ft", "DEPRECATED,traffic will not match"},
		"13:313":  Application{"encrypted-bittorrent", "Encrypted Bittorrent Traffic"},
		"13:323":  Application{"msn-messenger-video", "MSN Messenger Video"},
		"13:326":  Application{"teredo-ipv6-tunneled", "Teredo IPv6 over IPv4 tunneling protocol"},
		"13:327":  Application{"ayiya-ipv6-tunneled", "Ayiya IPv6 tunneling protocol"},
		"13:329":  Application{"isatap-ipv6-tunneled", "Intra-Site Automatic Tunnel Addressing Protocol IPv6 ov"},
		"13:330":  Application{"sixtofour-ipv6-tunneled", "Sixtofour IPv6 over IPv4 tunneling protocol"},
		"13:401":  Application{"netapp-snapmirror", "Data replication Enterprise Solution"},
		"13:414":  Application{"webex-meeting", "Online conferencing application"},
		"13:415":  Application{"windows-update", "DEPRECATED,traffic will not match"},
		"13:451":  Application{"gridftp", "File Transfer Protocol over the Grid"},
		"13:1310": Application{"ms-rpc", "Microsoft Remote Procedure Call"},
		"13:453":  Application{"ssl", "Secure Socket Layer Protocol"},
		"13:455":  Application{"openvpn", "OpenVPN protocol"},
		"13:456":  Application{"cisco-ip-camera", "Cisco video surveillance camera"},
		"13:457":  Application{"netflix", "Netflix online video streaming and browsing"},
		"13:458":  Application{"hulu", "Hulu browsing"},
		"13:459":  Application{"megavideo", "DEPRECATED, traffic will not match"},
		"13:460":  Application{"tor", "The Onion Routing Protocol"},
		"13:1320": Application{"viber", "Viber VoIP is a mobile voice communication application."},
		"13:467":  Application{"fasttrack-static", "FastTrack Traffic - KaZaA, Morpheus, Grokster..."},
		"13:464":  Application{"gtalk-chat", "IM between the Google Talk servers and its clients"},
		"13:475":  Application{"ip-messenger", "Instant messaging over IP application"},
		"13:416":  Application{"edonkey-static", "Static Edonkey"},
		"13:506":  Application{"game-spy", "Game-spy online gaming"},
		"13:378":  Application{"lwapp", "Lightweight Access Point Protocol"},
		"13:379":  Application{"synergy", "Computer resources sharing application"},
		"13:472":  Application{"steam", "Online game platform"},
		"13:474":  Application{"livemeeting", "DEPRECATED, traffic will not match"},
		"13:471":  Application{"gtalk-video", "Google Talk Video Call"},
		"13:479":  Application{"ping", "Ping is echo-req/echo-reply over ICMP"},
		"13:480":  Application{"livestation", "Live television and radio broadcasts"},
		"13:481":  Application{"ms-win-dns", "MS-RPC windows Domain Naming System"},
		"13:482":  Application{"ms-iis", "MS-RPC Internet Information Services (IIS)"},
		"13:483":  Application{"ms-netlogon", "MS-RPC Net Logon, log on management service"},
		"13:484":  Application{"ms-sms", "Microsoft Systems Management Server"},
		"13:485":  Application{"vnc-http", "VNC-HTTP is a graphical desktop sharing system that run"},
		"13:486":  Application{"perforce", "Software Version Management"},
		"13:487":  Application{"rtmpe", "Encrypted Real Time Messaging Protocol"},
		"13:488":  Application{"share-point", "SharePoint web application protocol"},
		"13:489":  Application{"rhapsody", "Online Music Service"},
		"13:490":  Application{"activesync", "Microsoft Activesync protocolmobile data synchronizatio"},
		"13:491":  Application{"rtmpt", "Real Time Messaging Protocol tunneled over HTTP"},
		"13:492":  Application{"dmp", "Cisco Digital Media Player"},
		"13:476":  Application{"vmware-view", "match UI and login of VMware. Actual desktop data is se"},
		"13:493":  Application{"vmware-vmotion", "VMware live Migration of Virtual Machines"},
		"13:494":  Application{"teamviewer", "free remote access and desktop sharing"},
		"13:495":  Application{"ms-office-365", "Microsoft Office 365"},
		"13:497":  Application{"ms-update", "Microsoft Update Service"},
		"13:498":  Application{"ms-live-accounts", "Windows Live Services Authentication"},
		"13:499":  Application{"gotomypc", "GoToMyPc is a remote control service"},
		"13:500":  Application{"aol-messenger-audio", "AOL Instant Messenger Audio Calls traffic"},
		"13:501":  Application{"aol-messenger-video", "AOL Instant Messenger Video Calls traffic"},
		"13:502":  Application{"aol-messenger-ft", "DEPRECATED, signatures moved to OSCAR File-Transfer"},
		"13:503":  Application{"ghostsurf", "DEPRECATED, traffic will not match"},
		"13:528":  Application{"google-accounts", "Google Services Authentication"},
		"13:505":  Application{"adobe-connect", "web conferencing software"},
		"13:507":  Application{"realmedia", "RealMedia traffic"},
		"13:508":  Application{"ms-dynamics-crm-online", "Microsoft Dynamics CRM Online"},
		"13:509":  Application{"salesforce", "Customer relationship management web application"},
		"13:510":  Application{"windows-azure", "Microsoft Windows Azure"},
		"13:511":  Application{"hotmail", "DEPRECATED, traffic will not match. Please check outloo"},
		"13:513":  Application{"oscar-filetransfer", "OSCAR Protocol File-transfer classification"},
		"13:514":  Application{"mikogo", "Mikogo is a remote desktop sharing software"},
		"13:515":  Application{"pandora", "Pandora Internet Radio"},
		"13:516":  Application{"oracle-ebsuite-unsecured", "Oracle E-Business Suite - Un-encrypted Traffic"},
		"13:517":  Application{"twitter", "Twitter Microblogging Social Network"},
		"13:518":  Application{"facebook", "Facebook, social web application and service"},
		"13:519":  Application{"logmein", "remote-access software for PC and Mobile"},
		"13:520":  Application{"google-services", "google-services, set of tools and apis used by google a"},
		"13:521":  Application{"google-plus", "google-plus, social networking web and mobile applicati"},
		"13:522":  Application{"google-docs", "google-docs, web-based office suite and data storage"},
		"13:523":  Application{"picasa", "Picasa, social photo sharing web application"},
		"13:525":  Application{"blogger", "blogger, social blog-publishing service"},
		"13:526":  Application{"yahoo-mail", "Yahoo! Mail"},
		"13:527":  Application{"linkedin", "LinkedIn Professional Network"},
		"13:530":  Application{"gbridge", "Remote Access and file sharing software"},
		"13:531":  Application{"ms-lync", "MS-Lync, a unified communications platform"},
		"13:532":  Application{"ms-lync-media", "DEPRECATED, see ms-lync-video and ms-lync-audio"},
		"13:534":  Application{"showmypc", "Showmypc is a remote control software"},
		"13:535":  Application{"facetime", "Facetime video calling software"},
		"13:537":  Application{"xunlei", "Xunlei is a Chinese download manager and p2p client."},
		"13:538":  Application{"xunlei-kankan", "xunlei-kankan, xunlei-kankan is a chinese download mana"},
		"13:541":  Application{"spdy", "SPDY is a web content transporting protocol."},
		"13:540":  Application{"qqlive", "QQLIVE, a video streaming freeware"},
		"13:543":  Application{"bittorrent-networking", "bittorrent p2p file sharing client networking"},
		"13:544":  Application{"shoutcast", "SHOUTcast Internet Radio"},
		"13:545":  Application{"webex-media", "Webex audio, video and file sharing with HTTP-Proxy con"},
		"13:546":  Application{"webex-app-sharing", "Webex application sharing with HTTP-Proxy configured"},
		"13:547":  Application{"dameware-mrc", "DameWare Mini Remote Control"},
		"13:549":  Application{"airplay", "Apple AirPlay wireless media streaming"},
		"13:550":  Application{"outlook-web-service", "Microsoft Web-Based email services under Outlook brand,"},
		"13:551":  Application{"espn-browsing", "ESPN related websites browsing and mobile applications"},
		"13:552":  Application{"espn-video", "ESPN related websites and mobile applications video con"},
		"13:553":  Application{"whatsapp", "WhatsApp, Text chat and multimedia sharing"},
		"13:554":  Application{"qq-accounts", "QQ general account login and common traffic"},
		"13:555":  Application{"modbus", "Industrial Standard Communication Protocol"},
		"13:557":  Application{"cisco-jabber-im", "Cisco Jabber Client; Instant Messaging"},
		"13:558":  Application{"cisco-jabber-audio", "Cisco Jabber Client; Audio Calls and Voice Mail"},
		"13:561":  Application{"cisco-jabber-video", "Cisco Jabber Client; Video Calls"},
		"13:559":  Application{"ms-lync-audio", "MS Lync Audio flows classification"},
		"13:560":  Application{"ms-lync-video", "MS Lync video calls classification"},
		"13:556":  Application{"cisco-jabber-control", "Cisco Jabber Client; Control and Signaling"},
		"13:562":  Application{"skydrive", "SkyDrive Cloud Storage Server From Microsoft"},
		"13:563":  Application{"ms-office-web-apps", "Web-based versions of Microsoft Word, Excel, PowerPoint"},
		"13:478":  Application{"telepresence-data", "telepresence-data stream"},
		"13:5060": Application{"sip", "Session Initiation Protocol"},
		"13:496":  Application{"jabber", "Jabber Protocol"},
		"13:5222": Application{"xmpp-client", "XMPP Client"},
		"13:777":  Application{"ip-camera", "IP Video Surveillance Camera"},
		"13:778":  Application{"surveillance-distributio", "Surveillance Distribution"},
	}
	for {
		select {
		case <-n.done:
			return nil
		case read := <-n.readApplication:
			log.Println("D! read application")
			application, ok := applicationTable[read.Key]
			if ok {
				read.Resp <- application
			} else {
				read.Resp <- Application{"unknown", "Unknown"}
			}
		}
	}
}
