// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/cmerror/cmerror.proto

package cmerror

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Juniper Error Item information
//
type Error struct {
	// Identifier that uniquely identifies the source of
	// the error.
	// e.g.
	//
	// junos/system/linecard/0/pcie/0/lane/0/pcie_cmerror_uncorrectable_major
	//
	Identifier *string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// Name of the error
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Instance id of the associated resource
	ComponentId *uint32 `protobuf:"varint,3,opt,name=component_id,json=componentId" json:"component_id,omitempty"`
	// Fru information
	FruType *string `protobuf:"bytes,4,opt,name=fru_type,json=fruType" json:"fru_type,omitempty"`
	FruSlot *uint32 `protobuf:"varint,5,opt,name=fru_slot,json=fruSlot" json:"fru_slot,omitempty"`
	// Scope,Category,Severity
	// in which this error belong to.
	Scope    *string `protobuf:"bytes,6,opt,name=scope" json:"scope,omitempty"`
	Category *string `protobuf:"bytes,7,opt,name=category" json:"category,omitempty"`
	Severity *string `protobuf:"bytes,8,opt,name=severity" json:"severity,omitempty"`
	// Thresholds and action configured for this
	// error.
	Threshold         *uint32 `protobuf:"varint,9,opt,name=threshold" json:"threshold,omitempty"`
	Limit             *uint32 `protobuf:"varint,10,opt,name=limit" json:"limit,omitempty"`
	RaisingThreshold  *uint32 `protobuf:"varint,11,opt,name=raising_threshold,json=raisingThreshold" json:"raising_threshold,omitempty"`
	ClearingThreshold *uint32 `protobuf:"varint,12,opt,name=clearing_threshold,json=clearingThreshold" json:"clearing_threshold,omitempty"`
	Action            *uint32 `protobuf:"varint,13,opt,name=action" json:"action,omitempty"`
	// local/global/both
	ActionHandlingType *uint32 `protobuf:"varint,14,opt,name=action_handling_type,json=actionHandlingType" json:"action_handling_type,omitempty"`
	// user configured thresholds and limits for this error.
	ConfiguredThreshold   *uint32  `protobuf:"varint,15,opt,name=configured_threshold,json=configuredThreshold" json:"configured_threshold,omitempty"`
	ConfiguredLimit       *uint32  `protobuf:"varint,16,opt,name=configured_limit,json=configuredLimit" json:"configured_limit,omitempty"`
	ConfiguredAction      *uint32  `protobuf:"varint,17,opt,name=configured_action,json=configuredAction" json:"configured_action,omitempty"`
	ConfiguredClearAction *uint32  `protobuf:"varint,18,opt,name=configured_clear_action,json=configuredClearAction" json:"configured_clear_action,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmerror_57b51643d8812561, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *Error) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Error) GetComponentId() uint32 {
	if m != nil && m.ComponentId != nil {
		return *m.ComponentId
	}
	return 0
}

func (m *Error) GetFruType() string {
	if m != nil && m.FruType != nil {
		return *m.FruType
	}
	return ""
}

func (m *Error) GetFruSlot() uint32 {
	if m != nil && m.FruSlot != nil {
		return *m.FruSlot
	}
	return 0
}

func (m *Error) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *Error) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *Error) GetSeverity() string {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ""
}

func (m *Error) GetThreshold() uint32 {
	if m != nil && m.Threshold != nil {
		return *m.Threshold
	}
	return 0
}

func (m *Error) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *Error) GetRaisingThreshold() uint32 {
	if m != nil && m.RaisingThreshold != nil {
		return *m.RaisingThreshold
	}
	return 0
}

func (m *Error) GetClearingThreshold() uint32 {
	if m != nil && m.ClearingThreshold != nil {
		return *m.ClearingThreshold
	}
	return 0
}

func (m *Error) GetAction() uint32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *Error) GetActionHandlingType() uint32 {
	if m != nil && m.ActionHandlingType != nil {
		return *m.ActionHandlingType
	}
	return 0
}

func (m *Error) GetConfiguredThreshold() uint32 {
	if m != nil && m.ConfiguredThreshold != nil {
		return *m.ConfiguredThreshold
	}
	return 0
}

func (m *Error) GetConfiguredLimit() uint32 {
	if m != nil && m.ConfiguredLimit != nil {
		return *m.ConfiguredLimit
	}
	return 0
}

func (m *Error) GetConfiguredAction() uint32 {
	if m != nil && m.ConfiguredAction != nil {
		return *m.ConfiguredAction
	}
	return 0
}

func (m *Error) GetConfiguredClearAction() uint32 {
	if m != nil && m.ConfiguredClearAction != nil {
		return *m.ConfiguredClearAction
	}
	return 0
}

type GlobalErrorConfiguration struct {
	// configuration bucket identifier
	Scope    *string `protobuf:"bytes,1,opt,name=scope" json:"scope,omitempty"`
	Category *string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Severity *string `protobuf:"bytes,3,opt,name=severity" json:"severity,omitempty"`
	// configured parameters for this bucket.
	Threshold            *uint32  `protobuf:"varint,4,opt,name=threshold" json:"threshold,omitempty"`
	Action               *uint32  `protobuf:"varint,5,opt,name=action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalErrorConfiguration) Reset()         { *m = GlobalErrorConfiguration{} }
func (m *GlobalErrorConfiguration) String() string { return proto.CompactTextString(m) }
func (*GlobalErrorConfiguration) ProtoMessage()    {}
func (*GlobalErrorConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmerror_57b51643d8812561, []int{1}
}
func (m *GlobalErrorConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalErrorConfiguration.Unmarshal(m, b)
}
func (m *GlobalErrorConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalErrorConfiguration.Marshal(b, m, deterministic)
}
func (dst *GlobalErrorConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalErrorConfiguration.Merge(dst, src)
}
func (m *GlobalErrorConfiguration) XXX_Size() int {
	return xxx_messageInfo_GlobalErrorConfiguration.Size(m)
}
func (m *GlobalErrorConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalErrorConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalErrorConfiguration proto.InternalMessageInfo

func (m *GlobalErrorConfiguration) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *GlobalErrorConfiguration) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *GlobalErrorConfiguration) GetSeverity() string {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ""
}

func (m *GlobalErrorConfiguration) GetThreshold() uint32 {
	if m != nil && m.Threshold != nil {
		return *m.Threshold
	}
	return 0
}

func (m *GlobalErrorConfiguration) GetAction() uint32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

//
// Top-level Cmerror message
//
type Cmerror struct {
	// collection of error items
	ErrorItem []*Error `protobuf:"bytes,1,rep,name=error_item,json=errorItem" json:"error_item,omitempty"`
	// last configuration change for cmerror.
	LastConfigurationChange *uint64 `protobuf:"varint,2,opt,name=last_configuration_change,json=lastConfigurationChange" json:"last_configuration_change,omitempty"`
	// This will toggle at start of every wrap cycle
	WrapCycleMarker *bool `protobuf:"varint,3,opt,name=wrap_cycle_marker,json=wrapCycleMarker" json:"wrap_cycle_marker,omitempty"`
	// Fru slot identifier
	FruSlot *uint32 `protobuf:"varint,4,opt,name=fru_slot,json=fruSlot" json:"fru_slot,omitempty"`
	FruType *string `protobuf:"bytes,5,opt,name=fru_type,json=fruType" json:"fru_type,omitempty"`
	// Collection of global configuration items
	GlobalConfigurationItem []*GlobalErrorConfiguration `protobuf:"bytes,6,rep,name=global_configuration_item,json=globalConfigurationItem" json:"global_configuration_item,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                    `json:"-"`
	XXX_unrecognized        []byte                      `json:"-"`
	XXX_sizecache           int32                       `json:"-"`
}

func (m *Cmerror) Reset()         { *m = Cmerror{} }
func (m *Cmerror) String() string { return proto.CompactTextString(m) }
func (*Cmerror) ProtoMessage()    {}
func (*Cmerror) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmerror_57b51643d8812561, []int{2}
}
func (m *Cmerror) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmerror.Unmarshal(m, b)
}
func (m *Cmerror) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmerror.Marshal(b, m, deterministic)
}
func (dst *Cmerror) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmerror.Merge(dst, src)
}
func (m *Cmerror) XXX_Size() int {
	return xxx_messageInfo_Cmerror.Size(m)
}
func (m *Cmerror) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmerror.DiscardUnknown(m)
}

var xxx_messageInfo_Cmerror proto.InternalMessageInfo

func (m *Cmerror) GetErrorItem() []*Error {
	if m != nil {
		return m.ErrorItem
	}
	return nil
}

func (m *Cmerror) GetLastConfigurationChange() uint64 {
	if m != nil && m.LastConfigurationChange != nil {
		return *m.LastConfigurationChange
	}
	return 0
}

func (m *Cmerror) GetWrapCycleMarker() bool {
	if m != nil && m.WrapCycleMarker != nil {
		return *m.WrapCycleMarker
	}
	return false
}

func (m *Cmerror) GetFruSlot() uint32 {
	if m != nil && m.FruSlot != nil {
		return *m.FruSlot
	}
	return 0
}

func (m *Cmerror) GetFruType() string {
	if m != nil && m.FruType != nil {
		return *m.FruType
	}
	return ""
}

func (m *Cmerror) GetGlobalConfigurationItem() []*GlobalErrorConfiguration {
	if m != nil {
		return m.GlobalConfigurationItem
	}
	return nil
}

var E_JnprCmerrorExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*Cmerror)(nil),
	Field:         20,
	Name:          "jnpr_cmerror_ext",
	Tag:           "bytes,20,opt,name=jnpr_cmerror_ext,json=jnprCmerrorExt",
	Filename:      "plugins/parsers/jtinative/cmerror/cmerror.proto",
}

func init() {
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*GlobalErrorConfiguration)(nil), "GlobalErrorConfiguration")
	proto.RegisterType((*Cmerror)(nil), "Cmerror")
	proto.RegisterExtension(E_JnprCmerrorExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/cmerror/cmerror.proto", fileDescriptor_cmerror_57b51643d8812561)
}

var fileDescriptor_cmerror_57b51643d8812561 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x73, 0xda, 0x3e,
	0x10, 0x1d, 0x13, 0x4c, 0x40, 0xe4, 0x0f, 0x28, 0xfc, 0x7e, 0x88, 0x4c, 0x0f, 0x94, 0x99, 0xce,
	0xd0, 0x76, 0x0a, 0x6d, 0x0e, 0x3d, 0xe4, 0xd4, 0x96, 0xc9, 0xb4, 0xe9, 0xbf, 0x83, 0x93, 0x9e,
	0x3d, 0xaa, 0x59, 0x40, 0x89, 0x2d, 0x79, 0x64, 0x91, 0x84, 0x6b, 0x0f, 0xfd, 0x18, 0xbd, 0xf5,
	0x7b, 0x76, 0xb4, 0x32, 0xd8, 0x64, 0x26, 0x39, 0x59, 0xbb, 0xef, 0x3d, 0x49, 0x6f, 0xb5, 0x6b,
	0x32, 0x4e, 0xe3, 0xe5, 0x5c, 0xc8, 0x6c, 0x9c, 0x72, 0x9d, 0x81, 0xce, 0xc6, 0x57, 0x46, 0x48,
	0x6e, 0xc4, 0x0d, 0x8c, 0xa3, 0x04, 0xb4, 0x56, 0x7a, 0xfd, 0x1d, 0xa5, 0x5a, 0x19, 0x75, 0x7c,
	0x64, 0x20, 0x86, 0x04, 0x8c, 0x5e, 0x85, 0x46, 0xa5, 0x2e, 0x39, 0xf8, 0xed, 0x13, 0xff, 0xcc,
	0x92, 0xe8, 0x33, 0x42, 0xc4, 0x14, 0xa4, 0x11, 0x33, 0x01, 0x9a, 0x79, 0x7d, 0x6f, 0xd8, 0xf8,
	0xe0, 0xff, 0x7a, 0x57, 0xa9, 0x7b, 0x41, 0x09, 0xa0, 0x94, 0x54, 0x25, 0x4f, 0x80, 0x55, 0x2c,
	0x21, 0xc0, 0x35, 0x7d, 0x4a, 0xf6, 0x22, 0x95, 0xa4, 0x4a, 0x82, 0x34, 0xa1, 0x98, 0xb2, 0x9d,
	0xbe, 0x37, 0xdc, 0x0f, 0x9a, 0x9b, 0xdc, 0xf9, 0x94, 0xf6, 0x48, 0x7d, 0xa6, 0x97, 0xa1, 0x59,
	0xa5, 0xc0, 0xaa, 0x28, 0xdd, 0x9d, 0xe9, 0xe5, 0xe5, 0x2a, 0x85, 0x35, 0x94, 0xc5, 0xca, 0x30,
	0x1f, 0x95, 0x16, 0xba, 0x88, 0x95, 0xa1, 0x1d, 0xe2, 0x67, 0x91, 0x4a, 0x81, 0xd5, 0x50, 0xe2,
	0x02, 0x7a, 0x4c, 0xea, 0x11, 0x37, 0x30, 0x57, 0x7a, 0xc5, 0x76, 0x11, 0xd8, 0xc4, 0x16, 0xcb,
	0xe0, 0x06, 0xb4, 0x30, 0x2b, 0x56, 0x77, 0xd8, 0x3a, 0xa6, 0x4f, 0x48, 0xc3, 0x2c, 0x34, 0x64,
	0x0b, 0x15, 0x4f, 0x59, 0x03, 0x4f, 0x2a, 0x12, 0xf6, 0xac, 0x58, 0x24, 0xc2, 0x30, 0x82, 0x88,
	0x0b, 0xe8, 0x4b, 0xd2, 0xd6, 0x5c, 0x64, 0x42, 0xce, 0xc3, 0x42, 0xdb, 0x44, 0x46, 0x2b, 0x07,
	0x2e, 0x37, 0x5b, 0xbc, 0x22, 0x34, 0x8a, 0x81, 0xeb, 0x6d, 0xf6, 0x1e, 0xb2, 0xdb, 0x6b, 0xa4,
	0xa0, 0xff, 0x4f, 0x6a, 0x3c, 0x32, 0x42, 0x49, 0xb6, 0x8f, 0x94, 0x3c, 0xa2, 0xaf, 0x49, 0xc7,
	0xad, 0xc2, 0x05, 0x97, 0xd3, 0x18, 0x77, 0xb3, 0x75, 0x3b, 0x40, 0x16, 0x75, 0xd8, 0xa7, 0x1c,
	0xc2, 0x12, 0xbe, 0x21, 0x9d, 0x48, 0xc9, 0x99, 0x98, 0x2f, 0x35, 0x4c, 0x4b, 0x47, 0x1f, 0xa2,
	0xe2, 0xa8, 0xc0, 0x8a, 0xc3, 0x9f, 0x93, 0x56, 0x49, 0xe2, 0x9c, 0xb7, 0x90, 0x7e, 0x58, 0xe4,
	0xbf, 0xae, 0x6b, 0x50, 0xa2, 0xe6, 0x57, 0x6e, 0xbb, 0x1a, 0x14, 0xc0, 0x7b, 0x77, 0xf9, 0xb7,
	0xa4, 0x5b, 0x22, 0xa3, 0xe9, 0xb5, 0x84, 0xa2, 0xe4, 0xbf, 0x02, 0x9e, 0x58, 0xd4, 0xe9, 0x06,
	0x7f, 0x3c, 0xc2, 0x3e, 0xc6, 0xea, 0x27, 0x8f, 0xb1, 0x1d, 0x27, 0x39, 0x89, 0xe3, 0xa6, 0x9b,
	0x3e, 0xf0, 0x1e, 0xea, 0x83, 0xca, 0x23, 0x7d, 0xb0, 0xf3, 0x58, 0x1f, 0x54, 0xef, 0xf7, 0x41,
	0xf1, 0x2a, 0x7e, 0xf9, 0x55, 0x06, 0x7f, 0x2b, 0x64, 0x77, 0xe2, 0x06, 0xca, 0xce, 0x0a, 0x2e,
	0x42, 0x61, 0x20, 0x61, 0x5e, 0x7f, 0x67, 0xd8, 0x3c, 0xa9, 0x8d, 0xf0, 0xe2, 0x41, 0x03, 0x91,
	0x73, 0x03, 0x09, 0x3d, 0x25, 0xbd, 0x98, 0x67, 0x26, 0x8c, 0xca, 0x66, 0xc2, 0x68, 0xc1, 0xe5,
	0xdc, 0x0d, 0x50, 0x35, 0xe8, 0x5a, 0xc2, 0x96, 0xd9, 0x09, 0xc2, 0xf4, 0x05, 0x69, 0xdf, 0x6a,
	0x9e, 0x86, 0xd1, 0x2a, 0x8a, 0x21, 0x4c, 0xb8, 0xbe, 0x06, 0x8d, 0x4e, 0xea, 0xc1, 0xa1, 0x05,
	0x26, 0x36, 0xff, 0x0d, 0xd3, 0x5b, 0x13, 0x54, 0xdd, 0x9e, 0xa0, 0xf2, 0xdc, 0xf9, 0xdb, 0x73,
	0xf7, 0x83, 0xf4, 0xe6, 0x58, 0xf0, 0x7b, 0xf7, 0x43, 0x4f, 0x35, 0xf4, 0xd4, 0x1b, 0x3d, 0xf4,
	0x24, 0x41, 0xd7, 0x69, 0xb7, 0x92, 0xd6, 0xf4, 0xe9, 0x17, 0xd2, 0xba, 0x92, 0xa9, 0x0e, 0xf3,
	0x9f, 0x4f, 0x08, 0x77, 0x86, 0x76, 0x47, 0x9f, 0x97, 0x52, 0xa4, 0xa0, 0xbf, 0x83, 0xb9, 0x55,
	0xfa, 0x3a, 0xbb, 0x00, 0x99, 0x29, 0x9d, 0xb1, 0x4e, 0xdf, 0x1b, 0x36, 0x4f, 0xea, 0xa3, 0xbc,
	0xb0, 0xc1, 0x81, 0x95, 0xe6, 0xc1, 0xd9, 0x9d, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x29,
	0x91, 0xe4, 0xe5, 0x04, 0x00, 0x00,
}
