// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/pfed_oc/pfed_oc.proto

package pfed_oc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JunosPfe struct {
	NpuMemory            []*JunosPfeNpuMemoryList `protobuf:"bytes,151,rep,name=npu_memory,json=npuMemory" json:"npu_memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *JunosPfe) Reset()         { *m = JunosPfe{} }
func (m *JunosPfe) String() string { return proto.CompactTextString(m) }
func (*JunosPfe) ProtoMessage()    {}
func (*JunosPfe) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfed_oc_dbe95495f86730f1, []int{0}
}
func (m *JunosPfe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunosPfe.Unmarshal(m, b)
}
func (m *JunosPfe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunosPfe.Marshal(b, m, deterministic)
}
func (dst *JunosPfe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunosPfe.Merge(dst, src)
}
func (m *JunosPfe) XXX_Size() int {
	return xxx_messageInfo_JunosPfe.Size(m)
}
func (m *JunosPfe) XXX_DiscardUnknown() {
	xxx_messageInfo_JunosPfe.DiscardUnknown(m)
}

var xxx_messageInfo_JunosPfe proto.InternalMessageInfo

func (m *JunosPfe) GetNpuMemory() []*JunosPfeNpuMemoryList {
	if m != nil {
		return m.NpuMemory
	}
	return nil
}

type JunosPfeNpuMemoryList struct {
	PfeName              *string  `protobuf:"bytes,51,opt,name=pfe_name,json=pfeName" json:"pfe_name,omitempty"`
	CombinedPoolName     *string  `protobuf:"bytes,52,opt,name=combined_pool_name,json=combinedPoolName" json:"combined_pool_name,omitempty"`
	CombinedSize         *uint32  `protobuf:"varint,53,opt,name=combined_size,json=combinedSize" json:"combined_size,omitempty"`
	CombinedUsageCount   *uint32  `protobuf:"varint,54,opt,name=combined_usage_count,json=combinedUsageCount" json:"combined_usage_count,omitempty"`
	CombinedUtilization  *uint32  `protobuf:"varint,55,opt,name=combined_utilization,json=combinedUtilization" json:"combined_utilization,omitempty"`
	GlobalPoolName       *string  `protobuf:"bytes,56,opt,name=global_pool_name,json=globalPoolName" json:"global_pool_name,omitempty"`
	GlobalUsageCount     *uint32  `protobuf:"varint,57,opt,name=global_usage_count,json=globalUsageCount" json:"global_usage_count,omitempty"`
	GlobalAllocCount     *uint32  `protobuf:"varint,58,opt,name=global_alloc_count,json=globalAllocCount" json:"global_alloc_count,omitempty"`
	GlobalFreeCount      *uint32  `protobuf:"varint,59,opt,name=global_free_count,json=globalFreeCount" json:"global_free_count,omitempty"`
	LocalPoolName        *string  `protobuf:"bytes,60,opt,name=local_pool_name,json=localPoolName" json:"local_pool_name,omitempty"`
	LocalUsageCount      *uint32  `protobuf:"varint,61,opt,name=local_usage_count,json=localUsageCount" json:"local_usage_count,omitempty"`
	LocalAllocCount      *uint32  `protobuf:"varint,62,opt,name=local_alloc_count,json=localAllocCount" json:"local_alloc_count,omitempty"`
	LocalFreeCount       *uint32  `protobuf:"varint,63,opt,name=local_free_count,json=localFreeCount" json:"local_free_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JunosPfeNpuMemoryList) Reset()         { *m = JunosPfeNpuMemoryList{} }
func (m *JunosPfeNpuMemoryList) String() string { return proto.CompactTextString(m) }
func (*JunosPfeNpuMemoryList) ProtoMessage()    {}
func (*JunosPfeNpuMemoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfed_oc_dbe95495f86730f1, []int{0, 0}
}
func (m *JunosPfeNpuMemoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunosPfeNpuMemoryList.Unmarshal(m, b)
}
func (m *JunosPfeNpuMemoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunosPfeNpuMemoryList.Marshal(b, m, deterministic)
}
func (dst *JunosPfeNpuMemoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunosPfeNpuMemoryList.Merge(dst, src)
}
func (m *JunosPfeNpuMemoryList) XXX_Size() int {
	return xxx_messageInfo_JunosPfeNpuMemoryList.Size(m)
}
func (m *JunosPfeNpuMemoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_JunosPfeNpuMemoryList.DiscardUnknown(m)
}

var xxx_messageInfo_JunosPfeNpuMemoryList proto.InternalMessageInfo

func (m *JunosPfeNpuMemoryList) GetPfeName() string {
	if m != nil && m.PfeName != nil {
		return *m.PfeName
	}
	return ""
}

func (m *JunosPfeNpuMemoryList) GetCombinedPoolName() string {
	if m != nil && m.CombinedPoolName != nil {
		return *m.CombinedPoolName
	}
	return ""
}

func (m *JunosPfeNpuMemoryList) GetCombinedSize() uint32 {
	if m != nil && m.CombinedSize != nil {
		return *m.CombinedSize
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetCombinedUsageCount() uint32 {
	if m != nil && m.CombinedUsageCount != nil {
		return *m.CombinedUsageCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetCombinedUtilization() uint32 {
	if m != nil && m.CombinedUtilization != nil {
		return *m.CombinedUtilization
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetGlobalPoolName() string {
	if m != nil && m.GlobalPoolName != nil {
		return *m.GlobalPoolName
	}
	return ""
}

func (m *JunosPfeNpuMemoryList) GetGlobalUsageCount() uint32 {
	if m != nil && m.GlobalUsageCount != nil {
		return *m.GlobalUsageCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetGlobalAllocCount() uint32 {
	if m != nil && m.GlobalAllocCount != nil {
		return *m.GlobalAllocCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetGlobalFreeCount() uint32 {
	if m != nil && m.GlobalFreeCount != nil {
		return *m.GlobalFreeCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetLocalPoolName() string {
	if m != nil && m.LocalPoolName != nil {
		return *m.LocalPoolName
	}
	return ""
}

func (m *JunosPfeNpuMemoryList) GetLocalUsageCount() uint32 {
	if m != nil && m.LocalUsageCount != nil {
		return *m.LocalUsageCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetLocalAllocCount() uint32 {
	if m != nil && m.LocalAllocCount != nil {
		return *m.LocalAllocCount
	}
	return 0
}

func (m *JunosPfeNpuMemoryList) GetLocalFreeCount() uint32 {
	if m != nil && m.LocalFreeCount != nil {
		return *m.LocalFreeCount
	}
	return 0
}

var E_JnprJunosPfeExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*JunosPfe)(nil),
	Field:         57,
	Name:          "jnpr_junos_pfe_ext",
	Tag:           "bytes,57,opt,name=jnpr_junos_pfe_ext,json=jnprJunosPfeExt",
	Filename:      "plugins/parsers/jtinative/pfed_oc/pfed_oc.proto",
}

func init() {
	proto.RegisterType((*JunosPfe)(nil), "junos_pfe")
	proto.RegisterType((*JunosPfeNpuMemoryList)(nil), "junos_pfe.npu_memory_list")
	proto.RegisterExtension(E_JnprJunosPfeExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/pfed_oc/pfed_oc.proto", fileDescriptor_pfed_oc_dbe95495f86730f1)
}

var fileDescriptor_pfed_oc_dbe95495f86730f1 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x86, 0x55, 0x60, 0x62, 0x3b, 0xa3, 0x6b, 0xe7, 0x21, 0x11, 0xf5, 0xaa, 0x02, 0x09, 0x45,
	0xd3, 0xd4, 0xc2, 0xf8, 0x2e, 0xdf, 0x20, 0xb8, 0x98, 0xc4, 0x54, 0x65, 0xe2, 0xda, 0xca, 0xb2,
	0x93, 0xca, 0xc5, 0xf1, 0xb1, 0x6c, 0x07, 0xb6, 0x5e, 0xf2, 0x0f, 0xb8, 0xe2, 0x27, 0xf1, 0xb7,
	0x50, 0x9c, 0xd4, 0x35, 0x5c, 0x45, 0x3e, 0xef, 0x73, 0xde, 0x3c, 0xb2, 0x0c, 0x53, 0x2d, 0xeb,
	0x85, 0x50, 0x76, 0xaa, 0x73, 0x63, 0xd1, 0xd8, 0xe9, 0xd2, 0x09, 0x95, 0x3b, 0xf1, 0x1d, 0xa7,
	0xba, 0xc4, 0x0b, 0x4e, 0xc5, 0xfa, 0x3b, 0xd1, 0x86, 0x1c, 0x8d, 0x0e, 0x1c, 0x4a, 0xac, 0xd0,
	0x99, 0x2b, 0xee, 0x48, 0xb7, 0xc3, 0xbb, 0xbf, 0xb6, 0x60, 0x67, 0x59, 0x2b, 0xb2, 0x5c, 0x97,
	0xc8, 0x66, 0x00, 0x4a, 0xd7, 0xbc, 0xc2, 0x8a, 0xcc, 0x55, 0xf2, 0xbb, 0x37, 0xbe, 0x9e, 0xee,
	0x1e, 0x8f, 0x26, 0x01, 0x98, 0x6c, 0x52, 0x2e, 0x85, 0x75, 0xd9, 0x8e, 0xd2, 0xf5, 0x17, 0x7f,
	0x1e, 0xfd, 0xb9, 0x01, 0x83, 0xff, 0x62, 0x36, 0x86, 0x6d, 0x5d, 0x22, 0x57, 0x79, 0x85, 0xc9,
	0xa3, 0x71, 0x2f, 0xdd, 0xf9, 0xb0, 0xf5, 0xf3, 0xdd, 0xb5, 0xed, 0x5e, 0x76, 0x53, 0x97, 0x78,
	0x9a, 0x57, 0xc8, 0x8e, 0x80, 0x15, 0x54, 0x9d, 0x0b, 0x85, 0x17, 0x5c, 0x13, 0xc9, 0x96, 0x7d,
	0xdc, 0xb0, 0xd9, 0x70, 0x9d, 0xcc, 0x89, 0xa4, 0xa7, 0xef, 0x41, 0x3f, 0xd0, 0x56, 0xac, 0x30,
	0x79, 0x32, 0xee, 0xa5, 0xfd, 0xec, 0xd6, 0x7a, 0x78, 0x26, 0x56, 0xc8, 0x1e, 0xc0, 0xed, 0x00,
	0xd5, 0x36, 0x5f, 0x20, 0x2f, 0xa8, 0x56, 0x2e, 0x79, 0xea, 0xd9, 0xf0, 0xbb, 0xaf, 0x4d, 0xf4,
	0xb1, 0x49, 0xd8, 0xc3, 0x78, 0xc3, 0x09, 0x29, 0x56, 0xb9, 0x13, 0xa4, 0x92, 0x67, 0x7e, 0xe3,
	0x20, 0x6c, 0x6c, 0x22, 0x96, 0xc2, 0x70, 0x21, 0xe9, 0x3c, 0x97, 0x91, 0xf5, 0x73, 0x6f, 0xbd,
	0xd7, 0xce, 0x83, 0xf3, 0x11, 0xb0, 0x8e, 0x8c, 0x65, 0x5e, 0xf8, 0xea, 0xae, 0x23, 0x52, 0xd9,
	0xd0, 0xb9, 0x94, 0x54, 0x74, 0xf4, 0x2c, 0xa6, 0xdf, 0x37, 0x41, 0x4b, 0x1f, 0xc2, 0x7e, 0x47,
	0x97, 0x06, 0xd7, 0xd5, 0x2f, 0x3d, 0x3c, 0x68, 0x83, 0xcf, 0x06, 0xbb, 0xe6, 0xfb, 0x30, 0x90,
	0x54, 0xfc, 0x23, 0xfc, 0xca, 0x0b, 0xf7, 0xfd, 0x38, 0xf8, 0x1e, 0xc2, 0x7e, 0xcb, 0xc5, 0xba,
	0xaf, 0xdb, 0x4e, 0x1f, 0x44, 0xb6, 0x81, 0x8d, 0x65, 0xdf, 0x44, 0x6c, 0xe4, 0x9a, 0xc2, 0xb0,
	0x65, 0x23, 0xd5, 0xb7, 0x1e, 0xdd, 0xf3, 0xf3, 0x60, 0x3a, 0x9b, 0x03, 0x5b, 0x2a, 0x6d, 0x78,
	0x78, 0x76, 0x1c, 0x2f, 0x1d, 0xbb, 0x33, 0x39, 0xa9, 0x95, 0xd0, 0x68, 0x4e, 0xd1, 0xfd, 0x20,
	0xf3, 0xcd, 0x9e, 0xa1, 0xb2, 0x64, 0xac, 0xbf, 0xca, 0xdd, 0x63, 0xd8, 0xbc, 0xd2, 0x6c, 0xd0,
	0xac, 0x9f, 0x34, 0xc7, 0x79, 0x89, 0x9f, 0x2e, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x9e, 0x6b, 0x90, 0x2c, 0x03, 0x00, 0x00,
}
