# Parse the new lines appended to a file
[[inputs.tail]]
  files = ["/var/mymetrics.out"]

  ## Read from the beginning using the deprecated option
  initial_read_offset = "beginning"

  data_format = "influx"
