// Code generated by mockery v2.0.4. DO NOT EDIT.

package etherscan

import (
	mock "github.com/stretchr/testify/mock"
)

// MockValidatingBalanceResponder is an autogenerated mock type for the ValidatingBalanceResponder type
type MockValidatingBalanceResponder struct {
	mock.Mock
}

// Result provides a mock function with given fields:
func (_m *MockValidatingBalanceResponder) Result() []AccountBalance {
	ret := _m.Called()

	var r0 []AccountBalance
	if rf, ok := ret.Get(0).(func() []AccountBalance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AccountBalance)
		}
	}

	return r0
}

// ValidateResponseStatus provides a mock function with given fields:
func (_m *MockValidatingBalanceResponder) ValidateResponseStatus() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
