
DROP TABLE IF EXISTS TELEGRAF_METRIC_SETTINGS;
CREATE TABLE TELEGRAF_METRIC_SETTINGS 
(
    SERIES_NAME  VARCHAR (100 )PRIMARY KEY,
    QUERY          VARCHAR (4000 )NOT NULL,
    TAGS         VARCHAR (1024 )NULL,
    FIELDS       VARCHAR (1024 )NULL,
    PIVOT_KEY    VARCHAR (100 )NULL,
    PIVOT        INT NOT NULL DEFAULT 0 
);

DROP TABLE IF EXISTS TELEGRAF_GLOBAL_SETTINGS;
CREATE TABLE TELEGRAF_GLOBAL_SETTINGS 
(
  SETTING_KEY VARCHAR(100)  PRIMARY KEY, 
  SETTING_VALUE INT NOT NULL 
);

-- TELEGRAF_GLOBAL_SETTINGS
INSERT INTO TELEGRAF_GLOBAL_SETTINGS VALUES ( 'CLUSTER_MODE', 0);

-- TELEGRAF_METRIC_SETTINGS 
INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_session_stat', 
       'SELECT * FROM MONITOR_SESSION_STAT',
       'CLUSTER_NAME',
       'TOTAL_SESSION_COUNT|ACTIVE_SESSION_COUNT|TOTAL_STATEMENT_COUNT|LONG_RUNNING_STATEMENT_COUNT|TOTAL_TRANSACTION_COUNT|LONG_RUNNING_TRANSACTION_COUNT', 
       NULL, 
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_instance_stat', 
       'SELECT * FROM MONITOR_INSTANCE',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME',
       'RELEASE_VERSION|STARTUP_TIME|INSTANCE_STATUS', 
       NULL, 
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_sql_stat', 
       'SELECT * FROM MONITOR_SQL_STAT',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME',
       'STAT_VALUE', 
       'STAT_NAME', 
       1
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_cluster_dispatcher_stat', 
       'SELECT * FROM MONITOR_CLUSTER_DISPATCHER',
       'CLUSTER_NAME|GROUP_NAME',
       'RX_BYTES|TX_BYTES|RX_JOBS|TX_JOBS', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_cluster_dispatcher_detail', 
       'SELECT * FROM MONITOR_CLUSTER_DISPATCHER_DETAIL',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME',
       'RX_BYTES|TX_BYTES|RX_JOBS|TX_JOBS', 
       NULL,
       0
FROM DUAL ;  


INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_tablespace_stat', 
       'SELECT * FROM MONITOR_TABLESPACE_STAT',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME|NAME|ATTR',
       'TOTAL_BYTES|USED_BYTES|USED_PCT', 
       NULL,
       0
FROM DUAL ;  


INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_ager_stat', 
       'SELECT * FROM MONITOR_AGER_STAT',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME',
       'GLOBAL_GAP|GROUP_GAP|LOCAL_GAP', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_session_detail', 
       'SELECT * FROM MONITOR_SESSION_DETAIL',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME|SESSION_ID',
       'SERIAL_NO|TRANS_ID|CONNECTION_TYPE|USER_NAME|PROCESS_ID|LOGON_TIME|PROGRAM_NAME|CLIENT_ADDRESS|CLIENT_PORT|IS_ACTIVE', 
       NULL,
       0
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_statement_detail', 
       'SELECT * FROM MONITOR_STATEMENT_DETAIL',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME|SESSIONS_STMT_ID',
       'PROGRAM_NAME|PROCESS_ID|STATUS|SQL_TEXT|ELASPED_SECONDS', 
       NULL,
       0
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_transaction_detail', 
       'SELECT * FROM MONITOR_TRANSACTION_DETAIL',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME|TRANS_ID',
       'GROUP_NAME|MEMBER_NAME|TRANS_ID|SESSION_ID|PROGRAM_NAME|PROCESS_ID|TRANS_STATE|IS_XA|ELAPSED_SECONDS', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_ssa_stat', 
       'SELECT * FROM MONITOR_SSA_STAT',
       'CLUSTER_NAME|GROUP_NAME|MEMBER_NAME',
       'TOTAL_BYTES|USED_BYTES|USED_PCT', 
       NULL,
       0
FROM DUAL ;  

/*
INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_shard_table_distibution', 
       'SELECT * FROM MONITOR_SHARD_TAB_DISTRIBUTION',
       'CLUSTER_NAME|OWNER|TABLE_SCHEMA|TABLE_NAME|GROUP_NAME',
       'ALLOC_BYTES', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_shard_index_distibution', 
       'SELECT * FROM MONITOR_SHARD_IND_DISTRIBUTION',
       'CLUSTER_NAME|OWNER|TABLE_SCHEMA|TABLE_NAME|INDEX_NAME|GROUP_NAME',
       'ALLOC_BYTES', 
       NULL,
       0
FROM DUAL ;  
*/

INSERT INTO TELEGRAF_METRIC_SETTINGS
SELECT 'goldilocks_tech_shard',
       'SELECT * FROM MONITOR_SHARD_TRANS',
       '',
       'MEMBER_NAME|DRIVER_ID|DRIVER_COUNT|ID|SERIAL|TRANS_ID|TOP_LAYER|CONNECTION|USER_ID|LOGIN_USER_ID|STATUS|WATCH|SERVER|CLIENT_CHARSET|CLIENT_PROCESS|SERVER_PROCESS|LOGON_TIME|PROGRAM|ADDRESS|PORT|DRIVER_MEMBER_POS|DRIVER_SESSION_ID|DRIVER_SESSION_SERIAL|IN_FULL|IN_JOB|FAILOVER_TYPE|FAILED_OVER',
       NULL,
       0
FROM DUAL ;

INSERT INTO TELEGRAF_METRIC_SETTINGS
SELECT 'goldilocks_lock_wait',
       'SELECT * FROM MONITOR_LOCK_WAIT',
       'CLUSTER_NAME',
       'GRANTED_MEMBER_NAME|GRANTED_ID|GRANTED_SERIAL|GRANTED_PROGRAM|GRANTED_PROCESS_ID|REQUESTED_MEMBER_NAME|REQUESTED_ID|REQUESTED_SERIAL|REQUESTED_PROGRAM|REQUESTED_PROCESS_ID',
       NULL,
       0
FROM DUAL ;
