package cisco_telemetry_mdt

func createDatabase() map[string]map[string]string {
	return map[string]map[string]string{
		// Physical memory
		"show processes memory physical": {
			"processname": "string",
		},
		// BGP v4
		"show bgp ipv4 unicast": {
			"aspath": "string",
		},
		// CPU
		"show processes cpu": {
			"kernel_percent": "float",
			"idle_percent":   "float",
			"process":        "string",
			"user_percent":   "float",
			"onesec":         "float",
		},
		// System resources
		"show system resources": {
			"cpu_state_user":        "float",
			"kernel":                "float",
			"current_memory_status": "string",
			"load_avg_15min":        "float",
			"idle":                  "float",
			"load_avg_1min":         "float",
			"user":                  "float",
			"cpu_state_idle":        "float",
			"load_avg_5min":         "float",
			"cpu_state_kernel":      "float",
		},
		// Power
		"show environment power": {
			"reserve_sup":               "string",
			"det_volt":                  "string",
			"heatsink_temp":             "string",
			"det_pintot":                "string",
			"det_iinb":                  "string",
			"ps_input_current":          "string",
			"modnum":                    "string",
			"trayfannum":                "string",
			"modstatus_3k":              "string",
			"fan2rpm":                   "string",
			"amps_alloced":              "string",
			"all_inlets_connected":      "string",
			"tot_pow_out_actual_draw":   "string",
			"ps_redun_op_mode":          "string",
			"curtemp":                   "string",
			"mod_model":                 "string",
			"fanmodel":                  "string",
			"ps_output_current":         "string",
			"majthres":                  "string",
			"input_type":                "string",
			"allocated":                 "string",
			"fanhwver":                  "string",
			"clkhwver":                  "string",
			"fannum":                    "string",
			"watts_requested":           "string",
			"cumulative_power":          "string",
			"tot_gridB_capacity":        "string",
			"pow_used_by_mods":          "string",
			"tot_pow_alloc_budgeted":    "string",
			"psumod":                    "string",
			"ps_status_3k":              "string",
			"temptype":                  "string",
			"regval":                    "string",
			"inlet_temp":                "string",
			"det_cord":                  "string",
			"reserve_fan":               "string",
			"det_pina":                  "string",
			"minthres":                  "string",
			"actual_draw":               "string",
			"sensor":                    "string",
			"zone":                      "string",
			"det_iin":                   "string",
			"det_iout":                  "string",
			"det_vin":                   "string",
			"fan1rpm":                   "string",
			"tot_gridA_capacity":        "string",
			"fanperc":                   "string",
			"det_pout":                  "string",
			"alarm_str":                 "string",
			"zonespeed":                 "string",
			"det_total_cap":             "string",
			"reserve_xbar":              "string",
			"det_vout":                  "string",
			"watts_alloced":             "string",
			"ps_in_power":               "string",
			"tot_pow_input_actual_draw": "string",
			"ps_output_voltage":         "string",
			"det_name":                  "string",
			"tempmod":                   "string",
			"clockname":                 "string",
			"fanname":                   "string",
			"regnumstr":                 "string",
			"bitnumstr":                 "string",
			"ps_slot":                   "string",
			"actual_out":                "string",
			"ps_input_voltage":          "string",
			"psmodel":                   "string",
			"speed":                     "string",
			"clkmodel":                  "string",
			"ps_redun_mode_3k":          "string",
			"tot_pow_capacity":          "string",
			"amps":                      "string",
			"available_pow":             "string",
			"reserve_supxbarfan":        "string",
			"watts":                     "string",
			"det_pinb":                  "string",
			"det_vinb":                  "string",
			"ps_state":                  "string",
			"det_sw_alarm":              "string",
			"regnum":                    "string",
			"amps_requested":            "string",
			"fanrpm":                    "string",
			"actual_input":              "string",
			"outlet_temp":               "string",
			"tot_capa":                  "string",
		},
		// PTP correction
		"show ptp corrections": {
			"sup-time":       "string",
			"correction-val": "int64",
			"ptp-header":     "string",
			"intf-name":      "string",
			"ptp-end":        "string",
		},
		// Transeiver
		"show interface transceiver details": {
			"uncorrect_ber_alrm_hi":     "string",
			"uncorrect_ber_cur_warn_lo": "string",
			"current_warn_lo":           "float",
			"pre_fec_ber_max_alrm_hi":   "string",
			"serialnum":                 "string",
			"pre_fec_ber_acc_warn_lo":   "string",
			"pre_fec_ber_max_warn_lo":   "string",
			"laser_temp_warn_hi":        "float",
			"type":                      "string",
			"rx_pwr_0":                  "float",
			"rx_pwr_warn_hi":            "float",
			"uncorrect_ber_warn_hi":     "string",
			"qsfp_or_cfp":               "string",
			"protocol_type":             "string",
			"uncorrect_ber":             "string",
			"uncorrect_ber_cur_alrm_hi": "string",
			"tec_current":               "float",
			"pre_fec_ber":               "string",
			"uncorrect_ber_max_warn_lo": "string",
			"uncorrect_ber_min":         "string",
			"current_alrm_lo":           "float",
			"uncorrect_ber_acc_warn_lo": "string",
			"snr_warn_lo":               "float",
			"rev":                       "string",
			"laser_temp_alrm_lo":        "float",
			"current":                   "float",
			"rx_pwr_1":                  "float",
			"tec_current_warn_hi":       "float",
			"pre_fec_ber_cur_warn_lo":   "string",
			"cisco_part_number":         "string",
			"uncorrect_ber_acc_warn_hi": "string",
			"temp_warn_hi":              "float",
			"laser_freq_warn_lo":        "float",
			"uncorrect_ber_max_alrm_lo": "string",
			"snr_alrm_hi":               "float",
			"pre_fec_ber_cur_alrm_lo":   "string",
			"tx_pwr_alrm_hi":            "float",
			"pre_fec_ber_min_warn_lo":   "string",
			"pre_fec_ber_min_warn_hi":   "string",
			"rx_pwr_alrm_hi":            "float",
			"tec_current_warn_lo":       "float",
			"uncorrect_ber_acc_alrm_hi": "string",
			"rx_pwr_4":                  "float",
			"uncorrect_ber_cur":         "string",
			"pre_fec_ber_alrm_hi":       "string",
			"rx_pwr_warn_lo":            "float",
			"bit_encoding":              "string",
			"pre_fec_ber_acc":           "string",
			"sfp":                       "string",
			"pre_fec_ber_acc_alrm_hi":   "string",
			"pre_fec_ber_min":           "string",
			"current_warn_hi":           "float",
			"pre_fec_ber_max_alrm_lo":   "string",
			"uncorrect_ber_cur_warn_hi": "string",
			"current_alrm_hi":           "float",
			"pre_fec_ber_acc_alrm_lo":   "string",
			"snr_alrm_lo":               "float",
			"uncorrect_ber_acc":         "string",
			"tx_len":                    "string",
			"uncorrect_ber_alrm_lo":     "string",
			"pre_fec_ber_alrm_lo":       "string",
			"txcvr_type":                "string",
			"tec_current_alrm_lo":       "float",
			"volt_alrm_lo":              "float",
			"temp_alrm_hi":              "float",
			"uncorrect_ber_min_warn_lo": "string",
			"laser_freq":                "float",
			"uncorrect_ber_min_warn_hi": "string",
			"uncorrect_ber_cur_alrm_lo": "string",
			"pre_fec_ber_max_warn_hi":   "string",
			"name":                      "string",
			"fiber_type_byte0":          "string",
			"laser_freq_alrm_lo":        "float",
			"pre_fec_ber_cur_warn_hi":   "string",
			"partnum":                   "string",
			"snr":                       "float",
			"volt_alrm_hi":              "float",
			"connector_type":            "string",
			"tx_medium":                 "string",
			"tx_pwr_warn_hi":            "float",
			"cisco_vendor_id":           "string",
			"cisco_ext_id":              "string",
			"uncorrect_ber_max_warn_hi": "string",
			"pre_fec_ber_max":           "string",
			"uncorrect_ber_min_alrm_hi": "string",
			"pre_fec_ber_warn_hi":       "string",
			"tx_pwr_alrm_lo":            "float",
			"uncorrect_ber_warn_lo":     "string",
			"10gbe_code":                "string",
			"cable_type":                "string",
			"laser_freq_alrm_hi":        "float",
			"rx_pwr_3":                  "float",
			"rx_pwr":                    "float",
			"volt_warn_hi":              "float",
			"pre_fec_ber_cur_alrm_hi":   "string",
			"temperature":               "float",
			"voltage":                   "float",
			"tx_pwr":                    "float",
			"laser_temp_alrm_hi":        "float",
			"tx_speeds":                 "string",
			"uncorrect_ber_min_alrm_lo": "string",
			"pre_fec_ber_min_alrm_hi":   "string",
			"ciscoid":                   "string",
			"tx_pwr_warn_lo":            "float",
			"cisco_product_id":          "string",
			"info_not_available":        "string",
			"laser_temp":                "float",
			"pre_fec_ber_cur":           "string",
			"fiber_type_byte1":          "string",
			"tx_type":                   "string",
			"pre_fec_ber_min_alrm_lo":   "string",
			"pre_fec_ber_warn_lo":       "string",
			"temp_alrm_lo":              "float",
			"volt_warn_lo":              "float",
			"rx_pwr_alrm_lo":            "float",
			"rx_pwr_2":                  "float",
			"tec_current_alrm_hi":       "float",
			"uncorrect_ber_acc_alrm_lo": "string",
			"uncorrect_ber_max_alrm_hi": "string",
			"temp_warn_lo":              "float",
			"snr_warn_hi":               "float",
			"laser_temp_warn_lo":        "float",
			"pre_fec_ber_acc_warn_hi":   "string",
			"laser_freq_warn_hi":        "float",
			"uncorrect_ber_max":         "string",
		},
		// IGMP
		"show ip igmp groups vrf all": {
			"group-type":    "string",
			"translate":     "string",
			"sourceaddress": "string",
			"vrf-cntxt":     "string",
			"expires":       "string",
			"group-addr":    "string",
			"uptime":        "string",
		},
		// VRF all
		"show ip igmp interface vrf all": {
			"if-name":              "string",
			"static-group-map":     "string",
			"rll":                  "string",
			"host-proxy":           "string",
			"il":                   "string",
			"join-group-map":       "string",
			"expires":              "string",
			"host-proxy-group-map": "string",
			"next-query":           "string",
			"q-ver":                "string",
			"if-status":            "string",
			"un-solicited":         "string",
			"ip-sum":               "string",
		},
		// IGMP snooping
		"show ip igmp snooping": {
			"repsup":            "string",
			"omf_enabled":       "string",
			"v3repsup":          "string",
			"grepsup":           "string",
			"lkupmode":          "string",
			"description":       "string",
			"vlinklocalgrpsup":  "string",
			"gv3repsup":         "string",
			"reportfloodall":    "string",
			"leavegroupaddress": "string",
			"enabled":           "string",
			"omf":               "string",
			"sq":                "string",
			"sqr":               "string",
			"eht":               "string",
			"fl":                "string",
			"reportfloodenable": "string",
			"snoop-on":          "string",
			"glinklocalgrpsup":  "string",
		},
		// IGMP snooping groups
		"show ip igmp snooping groups": {
			"src-uptime":    "string",
			"source":        "string",
			"dyn-if-name":   "string",
			"raddr":         "string",
			"old-host":      "string",
			"snoop-enabled": "string",
			"expires":       "string",
			"omf-enabled":   "string",
			"uptime":        "string",
			"src-expires":   "string",
			"addr":          "string",
		},
		// IGMP snooping group details
		"show ip igmp snooping groups detail": {
			"src-uptime":    "string",
			"source":        "string",
			"dyn-if-name":   "string",
			"raddr":         "string",
			"old-host":      "string",
			"snoop-enabled": "string",
			"expires":       "string",
			"omf-enabled":   "string",
			"uptime":        "string",
			"src-expires":   "string",
			"addr":          "string",
		},
		// IGMP snooping groups summary
		"show ip igmp snooping groups summary": {
			"src-uptime":    "string",
			"source":        "string",
			"dyn-if-name":   "string",
			"raddr":         "string",
			"old-host":      "string",
			"snoop-enabled": "string",
			"expires":       "string",
			"omf-enabled":   "string",
			"uptime":        "string",
			"src-expires":   "string",
			"addr":          "string",
		},
		// mrouter
		"show ip igmp snooping mrouter": {
			"uptime":  "string",
			"expires": "string",
		},
		// Snooping statistics
		"show ip igmp snooping statistics": {
			"ut": "string",
		},
		// PIM interface
		"show ip pim interface vrf all": {
			"if-is-border":       "string",
			"cached_if_status":   "string",
			"genid":              "string",
			"if-name":            "string",
			"last-cleared":       "string",
			"is-pim-vpc-svi":     "string",
			"if-addr":            "string",
			"is-pim-enabled":     "string",
			"pim-dr-address":     "string",
			"hello-timer":        "string",
			"pim-bfd-enabled":    "string",
			"vpc-peer-nbr":       "string",
			"nbr-policy-name":    "string",
			"is-auto-enabled":    "string",
			"if-status":          "string",
			"jp-out-policy-name": "string",
			"if-addr-summary":    "string",
			"if-dr":              "string",
			"jp-in-policy-name":  "string",
		},
		// PIM neighborhood
		"show ip pim neighbor vrf all": {
			"longest-hello-intvl": "string",
			"if-name":             "string",
			"uptime":              "string",
			"expires":             "string",
			"bfd-state":           "string",
		},
		// PIM route
		"show ip pim route vrf all": {
			"rpf-nbr-1":                "string",
			"rpf-nbr-addr":             "string",
			"register":                 "string",
			"sgexpire":                 "string",
			"oif-bf-str":               "string",
			"mcast-addrs":              "string",
			"rp-addr":                  "string",
			"immediate-bf-str":         "string",
			"sgr-prune-list-bf-str":    "string",
			"context-name":             "string",
			"intf-name":                "string",
			"immediate-timeout-bf-str": "string",
			"rp-local":                 "string",
			"sgrexpire":                "string",
			"timeout-bf-str":           "string",
			"timeleft":                 "string",
		},
		// PIM RP
		"show ip pim rp vrf all": {
			"is-bsr-forward-only":      "string",
			"is-rpaddr-local":          "string",
			"bsr-expires":              "string",
			"autorp-expire-time":       "string",
			"rp-announce-policy-name":  "string",
			"rp-cand-policy-name":      "string",
			"is-autorp-forward-only":   "string",
			"rp-uptime":                "string",
			"rp-owner-flags":           "string",
			"df-bits-recovered":        "string",
			"bs-timer":                 "string",
			"rp-discovery-policy-name": "string",
			"arp-rp-addr":              "string",
			"auto-rp-addr":             "string",
			"autorp-expires":           "string",
			"is-autorp-enabled":        "string",
			"is-bsr-local":             "string",
			"is-autorp-listen-only":    "string",
			"autorp-dis-timer":         "string",
			"bsr-rp-expires":           "string",
			"static-rp-group-map":      "string",
			"rp-source":                "string",
			"autorp-cand-address":      "string",
			"autorp-up-time":           "string",
			"is-bsr-enabled":           "string",
			"bsr-uptime":               "string",
			"is-bsr-listen-only":       "string",
			"rpf-nbr-address":          "string",
			"is-rp-local":              "string",
			"is-autorp-local":          "string",
			"bsr-policy-name":          "string",
			"grange-grp":               "string",
			"rp-addr":                  "string",
			"anycast-rp-addr":          "string",
		},
		// PIM statistics
		"show ip pim statistics vrf all": {
			"vrf-name": "string",
		},
		// Interface brief
		"show interface brief": {
			"speed": "string",
			"vlan":  "string",
		},
		// PIM VRF
		"show ip pim vrf all": {
			"table-id": "string",
		},
		// IP mroute
		"show ip mroute summary vrf all": {
			"nat-mode":             "string",
			"oif-name":             "string",
			"nat-route-type":       "string",
			"uptime":               "string",
			"mofrr-nbr":            "string",
			"extranet_addr":        "string",
			"stale-route":          "string",
			"pending":              "string",
			"bidir":                "string",
			"expry_timer":          "string",
			"mofrr-iif":            "string",
			"group_addrs":          "string",
			"mpib-name":            "string",
			"rpf":                  "string",
			"mcast-addrs":          "string",
			"route-mdt-iod":        "string",
			"sr-oif":               "string",
			"stats-rate-buf":       "string",
			"source_addr":          "string",
			"route-iif":            "string",
			"rpf-nbr":              "string",
			"translated-route-src": "string",
			"group_addr":           "string",
			"lisp-src-rloc":        "string",
			"stats-pndg":           "string",
			"rate_buf":             "string",
			"extranet_vrf_name":    "string",
			"fabric-interest":      "string",
			"translated-route-grp": "string",
			"internal":             "string",
			"oif-mpib-name":        "string",
			"oif-uptime":           "string",
			"omd-vpc-svi":          "string",
			"source_addrs":         "string",
			"stale-oif":            "string",
			"core-interest":        "string",
			"oif-list-bitfield":    "string",
		},
		// IPv6 mroute
		"show ipv6 mroute summary vrf all": {
			"nat-mode":             "string",
			"oif-name":             "string",
			"nat-route-type":       "string",
			"uptime":               "string",
			"mofrr-nbr":            "string",
			"extranet_addr":        "string",
			"stale-route":          "string",
			"pending":              "string",
			"bidir":                "string",
			"expry_timer":          "string",
			"mofrr-iif":            "string",
			"group_addrs":          "string",
			"mpib-name":            "string",
			"rpf":                  "string",
			"mcast-addrs":          "string",
			"route-mdt-iod":        "string",
			"sr-oif":               "string",
			"stats-rate-buf":       "string",
			"source_addr":          "string",
			"route-iif":            "string",
			"rpf-nbr":              "string",
			"translated-route-src": "string",
			"group_addr":           "string",
			"lisp-src-rloc":        "string",
			"stats-pndg":           "string",
			"rate_buf":             "string",
			"extranet_vrf_name":    "string",
			"fabric-interest":      "string",
			"translated-route-grp": "string",
			"internal":             "string",
			"oif-mpib-name":        "string",
			"oif-uptime":           "string",
			"omd-vpc-svi":          "string",
			"source_addrs":         "string",
			"stale-oif":            "string",
			"core-interest":        "string",
			"oif-list-bitfield":    "string",
		},
		// VPC
		"sys/vpc": {
			"type2CompatQualStr": "string",
			"compatQualStr":      "string",
			"name":               "string",
			"issuFromVer":        "string",
			"issuToVer":          "string",
		},
		// BGP
		"sys/bgp": {
			"dynRtMap":       "string",
			"nhRtMap":        "string",
			"epePeerSet":     "string",
			"asn":            "string",
			"peerImp":        "string",
			"wght":           "string",
			"assocDom":       "string",
			"tblMap":         "string",
			"unSupprMap":     "string",
			"sessionContImp": "string",
			"allocLblRtMap":  "string",
			"defMetric":      "string",
			"password":       "string",
			"retainRttRtMap": "string",
			"clusterId":      "string",
			"localAsn":       "string",
			"name":           "string",
			"defOrgRtMap":    "string",
		},
		// CH
		"sys/ch": {
			"fanName":           "string",
			"typeCordConnected": "string",
			"vendor":            "string",
			"model":             "string",
			"rev":               "string",
			"vdrId":             "string",
			"hardwareAlarm":     "string",
			"unit":              "string",
			"hwVer":             "string",
		},
		// Intf
		"sys/intf": {
			"descr":       "string",
			"name":        "string",
			"lastStCause": "string",
			"description": "string",
			"unit":        "string",
			"operFECMode": "string",
			"operBitset":  "string",
			"mdix":        "string",
		},
		// Procsys
		"sys/procsys": {
			"name":      "string",
			"id":        "string",
			"upTs":      "string",
			"interval":  "string",
			"memstatus": "string",
		},
		// Proc
		"sys/proc": {
			"processName": "string",
			"procArg":     "string",
		},
		// BFD
		"sys/bfd/inst": {
			"descr":   "string",
			"vrfName": "string",
			"name":    "string",
		},
		// LLDP
		"sys/lldp": {
			"sysDesc":    "string",
			"portDesc":   "string",
			"portIdV":    "string",
			"chassisIdV": "string",
			"sysName":    "string",
			"name":       "string",
			"id":         "string",
		},
	}
}
