// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/sr_stats_per_sid/sr_stats_per_sid.proto

package sr_stats_per_sid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Top-level message
//
type SrStatsPerSid struct {
	// List of SR stats per SID records (ingress only as of now)
	SidStats             []*SegmentRoutingRecord `protobuf:"bytes,1,rep,name=sid_stats,json=sidStats" json:"sid_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SrStatsPerSid) Reset()         { *m = SrStatsPerSid{} }
func (m *SrStatsPerSid) String() string { return proto.CompactTextString(m) }
func (*SrStatsPerSid) ProtoMessage()    {}
func (*SrStatsPerSid) Descriptor() ([]byte, []int) {
	return fileDescriptor_sr_stats_per_sid_dc61ef1f0cf3e149, []int{0}
}
func (m *SrStatsPerSid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrStatsPerSid.Unmarshal(m, b)
}
func (m *SrStatsPerSid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrStatsPerSid.Marshal(b, m, deterministic)
}
func (dst *SrStatsPerSid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrStatsPerSid.Merge(dst, src)
}
func (m *SrStatsPerSid) XXX_Size() int {
	return xxx_messageInfo_SrStatsPerSid.Size(m)
}
func (m *SrStatsPerSid) XXX_DiscardUnknown() {
	xxx_messageInfo_SrStatsPerSid.DiscardUnknown(m)
}

var xxx_messageInfo_SrStatsPerSid proto.InternalMessageInfo

func (m *SrStatsPerSid) GetSidStats() []*SegmentRoutingRecord {
	if m != nil {
		return m.SidStats
	}
	return nil
}

//
// SR statistics record
//
type SegmentRoutingRecord struct {
	// Name of the SID
	SidIdentifier *string `protobuf:"bytes,1,req,name=sid_identifier,json=sidIdentifier" json:"sid_identifier,omitempty"`
	// Instance Identifier for cases when RPD creates multiple instances
	InstanceIdentifier *uint32 `protobuf:"varint,2,opt,name=instance_identifier,json=instanceIdentifier" json:"instance_identifier,omitempty"`
	// Name of the counter. This is useful when an SR label has multiple counters.
	// For some scenarios like routing restart, it is possible that a new counter is
	// created in the hardware.
	CounterName *string `protobuf:"bytes,3,opt,name=counter_name,json=counterName" json:"counter_name,omitempty"`
	// Ingress Traffic statistics
	IngressStats *SegmentRoutingStats `protobuf:"bytes,4,opt,name=ingress_stats,json=ingressStats" json:"ingress_stats,omitempty"`
	// Egress statistics
	EgressStats          *SegmentRoutingStats `protobuf:"bytes,5,opt,name=egress_stats,json=egressStats" json:"egress_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SegmentRoutingRecord) Reset()         { *m = SegmentRoutingRecord{} }
func (m *SegmentRoutingRecord) String() string { return proto.CompactTextString(m) }
func (*SegmentRoutingRecord) ProtoMessage()    {}
func (*SegmentRoutingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_sr_stats_per_sid_dc61ef1f0cf3e149, []int{1}
}
func (m *SegmentRoutingRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentRoutingRecord.Unmarshal(m, b)
}
func (m *SegmentRoutingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentRoutingRecord.Marshal(b, m, deterministic)
}
func (dst *SegmentRoutingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentRoutingRecord.Merge(dst, src)
}
func (m *SegmentRoutingRecord) XXX_Size() int {
	return xxx_messageInfo_SegmentRoutingRecord.Size(m)
}
func (m *SegmentRoutingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentRoutingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentRoutingRecord proto.InternalMessageInfo

func (m *SegmentRoutingRecord) GetSidIdentifier() string {
	if m != nil && m.SidIdentifier != nil {
		return *m.SidIdentifier
	}
	return ""
}

func (m *SegmentRoutingRecord) GetInstanceIdentifier() uint32 {
	if m != nil && m.InstanceIdentifier != nil {
		return *m.InstanceIdentifier
	}
	return 0
}

func (m *SegmentRoutingRecord) GetCounterName() string {
	if m != nil && m.CounterName != nil {
		return *m.CounterName
	}
	return ""
}

func (m *SegmentRoutingRecord) GetIngressStats() *SegmentRoutingStats {
	if m != nil {
		return m.IngressStats
	}
	return nil
}

func (m *SegmentRoutingRecord) GetEgressStats() *SegmentRoutingStats {
	if m != nil {
		return m.EgressStats
	}
	return nil
}

type SegmentRoutingStats struct {
	// Packet and Byte statistics
	Packets *uint64 `protobuf:"varint,1,opt,name=packets" json:"packets,omitempty"`
	Bytes   *uint64 `protobuf:"varint,2,opt,name=bytes" json:"bytes,omitempty"`
	// Rates of the above counters.
	PacketRate           *uint64  `protobuf:"varint,3,opt,name=packet_rate,json=packetRate" json:"packet_rate,omitempty"`
	ByteRate             *uint64  `protobuf:"varint,4,opt,name=byte_rate,json=byteRate" json:"byte_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentRoutingStats) Reset()         { *m = SegmentRoutingStats{} }
func (m *SegmentRoutingStats) String() string { return proto.CompactTextString(m) }
func (*SegmentRoutingStats) ProtoMessage()    {}
func (*SegmentRoutingStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_sr_stats_per_sid_dc61ef1f0cf3e149, []int{2}
}
func (m *SegmentRoutingStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentRoutingStats.Unmarshal(m, b)
}
func (m *SegmentRoutingStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentRoutingStats.Marshal(b, m, deterministic)
}
func (dst *SegmentRoutingStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentRoutingStats.Merge(dst, src)
}
func (m *SegmentRoutingStats) XXX_Size() int {
	return xxx_messageInfo_SegmentRoutingStats.Size(m)
}
func (m *SegmentRoutingStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentRoutingStats.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentRoutingStats proto.InternalMessageInfo

func (m *SegmentRoutingStats) GetPackets() uint64 {
	if m != nil && m.Packets != nil {
		return *m.Packets
	}
	return 0
}

func (m *SegmentRoutingStats) GetBytes() uint64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *SegmentRoutingStats) GetPacketRate() uint64 {
	if m != nil && m.PacketRate != nil {
		return *m.PacketRate
	}
	return 0
}

func (m *SegmentRoutingStats) GetByteRate() uint64 {
	if m != nil && m.ByteRate != nil {
		return *m.ByteRate
	}
	return 0
}

var E_JnprSrStatsPerSidExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*SrStatsPerSid)(nil),
	Field:         16,
	Name:          "jnpr_sr_stats_per_sid_ext",
	Tag:           "bytes,16,opt,name=jnpr_sr_stats_per_sid_ext,json=jnprSrStatsPerSidExt",
	Filename:      "plugins/parsers/jtinative/sr_stats_per_sid/sr_stats_per_sid.proto",
}

func init() {
	proto.RegisterType((*SrStatsPerSid)(nil), "SrStatsPerSid")
	proto.RegisterType((*SegmentRoutingRecord)(nil), "SegmentRoutingRecord")
	proto.RegisterType((*SegmentRoutingStats)(nil), "SegmentRoutingStats")
	proto.RegisterExtension(E_JnprSrStatsPerSidExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/sr_stats_per_sid/sr_stats_per_sid.proto", fileDescriptor_sr_stats_per_sid_dc61ef1f0cf3e149)
}

var fileDescriptor_sr_stats_per_sid_dc61ef1f0cf3e149 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0x87, 0xb5, 0x69, 0x22, 0x92, 0x71, 0x52, 0xa1, 0x4d, 0x10, 0x06, 0x0e, 0x58, 0x39, 0x20,
	0x1f, 0x50, 0x22, 0xe5, 0x00, 0x82, 0x13, 0x7f, 0xc4, 0x01, 0x0e, 0x15, 0x5a, 0x3f, 0x80, 0x59,
	0xe2, 0x21, 0xda, 0xb6, 0x59, 0xaf, 0x66, 0x26, 0xd0, 0x5e, 0x79, 0x0c, 0x2e, 0xbc, 0x2a, 0xb2,
	0x37, 0x69, 0xdd, 0x52, 0xf5, 0xe8, 0xdf, 0x7c, 0xdf, 0x78, 0x67, 0x34, 0xf0, 0x3e, 0x9c, 0xef,
	0x36, 0xce, 0xf3, 0x32, 0x58, 0x62, 0x24, 0x5e, 0x9e, 0x8a, 0xf3, 0x56, 0xdc, 0x4f, 0x5c, 0x32,
	0x95, 0x2c, 0x56, 0xb8, 0x0c, 0x48, 0x25, 0xbb, 0xea, 0xbf, 0x60, 0x11, 0xa8, 0x96, 0xfa, 0xe9,
	0x54, 0xf0, 0x1c, 0xb7, 0x28, 0x74, 0x59, 0x4a, 0x1d, 0x62, 0x38, 0xff, 0x08, 0x93, 0x82, 0x8a,
	0x86, 0xfe, 0x8a, 0x54, 0xb8, 0x4a, 0xaf, 0x60, 0xc4, 0xae, 0x8a, 0x0d, 0x52, 0x95, 0x1d, 0xe5,
	0xc9, 0xea, 0xd1, 0xa2, 0xc0, 0xcd, 0x16, 0xbd, 0x98, 0x7a, 0x27, 0xce, 0x6f, 0x0c, 0xae, 0x6b,
	0xaa, 0xcc, 0x90, 0x5d, 0xd5, 0x9a, 0xf3, 0x3f, 0x3d, 0x98, 0xdd, 0x85, 0xe8, 0x97, 0x70, 0xdc,
	0x34, 0x73, 0x15, 0x7a, 0x71, 0x3f, 0x1c, 0x52, 0xaa, 0xb2, 0x5e, 0x3e, 0xfa, 0x30, 0xf8, 0xfd,
	0xae, 0x37, 0x54, 0x66, 0xc2, 0xae, 0xfa, 0x7c, 0x55, 0xd3, 0xaf, 0x60, 0xea, 0x3c, 0x8b, 0xf5,
	0x6b, 0xec, 0x2a, 0xbd, 0x4c, 0xe5, 0x93, 0x83, 0xa2, 0x0f, 0x44, 0xc7, 0xcb, 0x61, 0xbc, 0xae,
	0x77, 0x5e, 0x90, 0x4a, 0x6f, 0xb7, 0x98, 0x1e, 0x65, 0xea, 0xfa, 0x1f, 0xc9, 0xbe, 0x74, 0x62,
	0xb7, 0xa8, 0xdf, 0xc0, 0xc4, 0xf9, 0x0d, 0x21, 0xf3, 0x7e, 0xc0, 0x7e, 0xa6, 0xf2, 0x64, 0x35,
	0xbb, 0x35, 0x60, 0x3b, 0x95, 0x19, 0xef, 0xd1, 0xf6, 0x4b, 0xbf, 0x86, 0x31, 0x76, 0xcd, 0xc1,
	0x3d, 0x66, 0x82, 0xd7, 0xe2, 0xfc, 0xaf, 0x82, 0xe9, 0x1d, 0x90, 0x7e, 0x0e, 0x0f, 0x82, 0x5d,
	0x9f, 0x61, 0xbb, 0x66, 0x95, 0xf7, 0xdb, 0x07, 0xa7, 0xca, 0x1c, 0x52, 0xfd, 0x0c, 0x06, 0xdf,
	0x2f, 0x05, 0xb9, 0x5d, 0xc0, 0x55, 0x39, 0x66, 0xfa, 0x05, 0x24, 0x91, 0x2b, 0xc9, 0x4a, 0x1c,
	0x39, 0x22, 0x99, 0x32, 0x10, 0x2b, 0xc6, 0x0a, 0xea, 0x39, 0x8c, 0x1a, 0x21, 0x52, 0xfd, 0x2e,
	0x35, 0x6c, 0xf2, 0x86, 0x79, 0xfb, 0x0d, 0x9e, 0x9c, 0xfa, 0x40, 0xe5, 0xed, 0xbb, 0x29, 0xf1,
	0x42, 0xf4, 0xe3, 0xc5, 0x97, 0x9d, 0x77, 0x01, 0xe9, 0x04, 0xe5, 0x57, 0x4d, 0x67, 0x5c, 0xa0,
	0xe7, 0x9a, 0x38, 0x7d, 0xd8, 0x2e, 0xe0, 0x78, 0x71, 0xe3, 0x7c, 0xcc, 0xac, 0xe9, 0x74, 0x23,
	0xfa, 0x74, 0x21, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x11, 0x24, 0xde, 0x77, 0xbe, 0x02, 0x00,
	0x00,
}
