#!/bin/bash
currentDir="$( cd "$(dirname "$0")" ; pwd -P )"

if [[ $currentDir == *"AppTranslocation"* ]]; then
  osascript -e "display alert \"Please copy Telegraf to somewhere on your machine. It can't be run from the image.\" as critical"
else
  cd $currentDir
  open -a Terminal ../Resources/usr/bin/telegraf
fi
