# Reads 'mntr' stats from one or many zookeeper servers
[[inputs.zookeeper]]
  ## An array of address to gather stats about. Specify an ip or hostname
  ## with port. ie localhost:2181, 10.0.0.1:2181, etc.
  servers = ["localhost:2181"]

  ## Enable TLS using the deprecated option
  tls_enable = true
