// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/l2ald_oc/l2ald_oc.proto

package l2ald_oc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VlansL2Al struct {
	Vlan                 []*VlansL2AlVlanList `protobuf:"bytes,151,rep,name=vlan" json:"vlan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VlansL2Al) Reset()         { *m = VlansL2Al{} }
func (m *VlansL2Al) String() string { return proto.CompactTextString(m) }
func (*VlansL2Al) ProtoMessage()    {}
func (*VlansL2Al) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0}
}
func (m *VlansL2Al) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2Al.Unmarshal(m, b)
}
func (m *VlansL2Al) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2Al.Marshal(b, m, deterministic)
}
func (dst *VlansL2Al) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2Al.Merge(dst, src)
}
func (m *VlansL2Al) XXX_Size() int {
	return xxx_messageInfo_VlansL2Al.Size(m)
}
func (m *VlansL2Al) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2Al.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2Al proto.InternalMessageInfo

func (m *VlansL2Al) GetVlan() []*VlansL2AlVlanList {
	if m != nil {
		return m.Vlan
	}
	return nil
}

type VlansL2AlVlanList struct {
	VlanId               *uint32                       `protobuf:"varint,51,opt,name=vlan_id,json=vlanId" json:"vlan_id,omitempty"`
	State                *VlansL2AlVlanListStateType   `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	Members              *VlansL2AlVlanListMembersType `protobuf:"bytes,152,opt,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *VlansL2AlVlanList) Reset()         { *m = VlansL2AlVlanList{} }
func (m *VlansL2AlVlanList) String() string { return proto.CompactTextString(m) }
func (*VlansL2AlVlanList) ProtoMessage()    {}
func (*VlansL2AlVlanList) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0}
}
func (m *VlansL2AlVlanList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanList.Unmarshal(m, b)
}
func (m *VlansL2AlVlanList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanList.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanList.Merge(dst, src)
}
func (m *VlansL2AlVlanList) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanList.Size(m)
}
func (m *VlansL2AlVlanList) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanList.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanList proto.InternalMessageInfo

func (m *VlansL2AlVlanList) GetVlanId() uint32 {
	if m != nil && m.VlanId != nil {
		return *m.VlanId
	}
	return 0
}

func (m *VlansL2AlVlanList) GetState() *VlansL2AlVlanListStateType {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *VlansL2AlVlanList) GetMembers() *VlansL2AlVlanListMembersType {
	if m != nil {
		return m.Members
	}
	return nil
}

type VlansL2AlVlanListStateType struct {
	VlanId               *uint32  `protobuf:"varint,52,opt,name=vlan_id,json=vlanId" json:"vlan_id,omitempty"`
	Name                 *string  `protobuf:"bytes,51,opt,name=name" json:"name,omitempty"`
	Status               *string  `protobuf:"bytes,53,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VlansL2AlVlanListStateType) Reset()         { *m = VlansL2AlVlanListStateType{} }
func (m *VlansL2AlVlanListStateType) String() string { return proto.CompactTextString(m) }
func (*VlansL2AlVlanListStateType) ProtoMessage()    {}
func (*VlansL2AlVlanListStateType) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0, 0}
}
func (m *VlansL2AlVlanListStateType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanListStateType.Unmarshal(m, b)
}
func (m *VlansL2AlVlanListStateType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanListStateType.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanListStateType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanListStateType.Merge(dst, src)
}
func (m *VlansL2AlVlanListStateType) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanListStateType.Size(m)
}
func (m *VlansL2AlVlanListStateType) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanListStateType.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanListStateType proto.InternalMessageInfo

func (m *VlansL2AlVlanListStateType) GetVlanId() uint32 {
	if m != nil && m.VlanId != nil {
		return *m.VlanId
	}
	return 0
}

func (m *VlansL2AlVlanListStateType) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *VlansL2AlVlanListStateType) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

type VlansL2AlVlanListMembersType struct {
	Member               []*VlansL2AlVlanListMembersTypeMemberList `protobuf:"bytes,151,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *VlansL2AlVlanListMembersType) Reset()         { *m = VlansL2AlVlanListMembersType{} }
func (m *VlansL2AlVlanListMembersType) String() string { return proto.CompactTextString(m) }
func (*VlansL2AlVlanListMembersType) ProtoMessage()    {}
func (*VlansL2AlVlanListMembersType) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0, 1}
}
func (m *VlansL2AlVlanListMembersType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanListMembersType.Unmarshal(m, b)
}
func (m *VlansL2AlVlanListMembersType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanListMembersType.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanListMembersType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanListMembersType.Merge(dst, src)
}
func (m *VlansL2AlVlanListMembersType) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanListMembersType.Size(m)
}
func (m *VlansL2AlVlanListMembersType) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanListMembersType.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanListMembersType proto.InternalMessageInfo

func (m *VlansL2AlVlanListMembersType) GetMember() []*VlansL2AlVlanListMembersTypeMemberList {
	if m != nil {
		return m.Member
	}
	return nil
}

type VlansL2AlVlanListMembersTypeMemberList struct {
	InterfaceRef         *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType `protobuf:"bytes,151,opt,name=interface_ref,json=interfaceRef" json:"interface_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                `json:"-"`
	XXX_unrecognized     []byte                                                  `json:"-"`
	XXX_sizecache        int32                                                   `json:"-"`
}

func (m *VlansL2AlVlanListMembersTypeMemberList) Reset() {
	*m = VlansL2AlVlanListMembersTypeMemberList{}
}
func (m *VlansL2AlVlanListMembersTypeMemberList) String() string { return proto.CompactTextString(m) }
func (*VlansL2AlVlanListMembersTypeMemberList) ProtoMessage()    {}
func (*VlansL2AlVlanListMembersTypeMemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0, 1, 0}
}
func (m *VlansL2AlVlanListMembersTypeMemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList.Unmarshal(m, b)
}
func (m *VlansL2AlVlanListMembersTypeMemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanListMembersTypeMemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList.Merge(dst, src)
}
func (m *VlansL2AlVlanListMembersTypeMemberList) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList.Size(m)
}
func (m *VlansL2AlVlanListMembersTypeMemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberList proto.InternalMessageInfo

func (m *VlansL2AlVlanListMembersTypeMemberList) GetInterfaceRef() *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType {
	if m != nil {
		return m.InterfaceRef
	}
	return nil
}

type VlansL2AlVlanListMembersTypeMemberListInterfaceRefType struct {
	State                *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                         `json:"-"`
	XXX_unrecognized     []byte                                                           `json:"-"`
	XXX_sizecache        int32                                                            `json:"-"`
}

func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) Reset() {
	*m = VlansL2AlVlanListMembersTypeMemberListInterfaceRefType{}
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) String() string {
	return proto.CompactTextString(m)
}
func (*VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) ProtoMessage() {}
func (*VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0, 1, 0, 0}
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType.Unmarshal(m, b)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType.Merge(dst, src)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType.Size(m)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefType proto.InternalMessageInfo

func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefType) GetState() *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType {
	if m != nil {
		return m.State
	}
	return nil
}

type VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType struct {
	Interface            *string  `protobuf:"bytes,51,opt,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) Reset() {
	*m = VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType{}
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) String() string {
	return proto.CompactTextString(m)
}
func (*VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) ProtoMessage() {}
func (*VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) Descriptor() ([]byte, []int) {
	return fileDescriptor_l2ald_oc_7f783fa0c7d134b3, []int{0, 0, 1, 0, 0, 0}
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType.Unmarshal(m, b)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType.Marshal(b, m, deterministic)
}
func (dst *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType.Merge(dst, src)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) XXX_Size() int {
	return xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType.Size(m)
}
func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) XXX_DiscardUnknown() {
	xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType.DiscardUnknown(m)
}

var xxx_messageInfo_VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType proto.InternalMessageInfo

func (m *VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType) GetInterface() string {
	if m != nil && m.Interface != nil {
		return *m.Interface
	}
	return ""
}

var E_JnprVlansL2AlExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*VlansL2Al)(nil),
	Field:         50,
	Name:          "jnpr_vlans_l2al_ext",
	Tag:           "bytes,50,opt,name=jnpr_vlans_l2al_ext,json=jnprVlansL2alExt",
	Filename:      "plugins/parsers/jtinative/l2ald_oc/l2ald_oc.proto",
}

func init() {
	proto.RegisterType((*VlansL2Al)(nil), "vlans_l2al")
	proto.RegisterType((*VlansL2AlVlanList)(nil), "vlans_l2al.vlan_list")
	proto.RegisterType((*VlansL2AlVlanListStateType)(nil), "vlans_l2al.vlan_list.state_type")
	proto.RegisterType((*VlansL2AlVlanListMembersType)(nil), "vlans_l2al.vlan_list.members_type")
	proto.RegisterType((*VlansL2AlVlanListMembersTypeMemberList)(nil), "vlans_l2al.vlan_list.members_type.member_list")
	proto.RegisterType((*VlansL2AlVlanListMembersTypeMemberListInterfaceRefType)(nil), "vlans_l2al.vlan_list.members_type.member_list.interface_ref_type")
	proto.RegisterType((*VlansL2AlVlanListMembersTypeMemberListInterfaceRefTypeStateType)(nil), "vlans_l2al.vlan_list.members_type.member_list.interface_ref_type.state_type")
	proto.RegisterExtension(E_JnprVlansL2AlExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/l2ald_oc/l2ald_oc.proto", fileDescriptor_l2ald_oc_7f783fa0c7d134b3)
}

var fileDescriptor_l2ald_oc_7f783fa0c7d134b3 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0xcf, 0x8b, 0xd3, 0x40,
	0x18, 0x25, 0xb5, 0x3f, 0xec, 0x97, 0x16, 0x64, 0x8a, 0x36, 0x04, 0x91, 0xd2, 0x53, 0xe9, 0x21,
	0xc5, 0xa8, 0x08, 0x82, 0xa0, 0x82, 0x88, 0x52, 0x04, 0x53, 0xf0, 0x3a, 0x8c, 0xed, 0xd7, 0x92,
	0x9a, 0x4c, 0xc2, 0xcc, 0xb4, 0xb6, 0x57, 0xff, 0x89, 0xdd, 0xd3, 0xde, 0xf6, 0xb6, 0xff, 0xdc,
	0xde, 0xf6, 0xb8, 0xcc, 0x24, 0x4d, 0xda, 0x6d, 0x61, 0x59, 0xf6, 0xf6, 0xbd, 0x37, 0xef, 0xbd,
	0x79, 0x7c, 0x1f, 0xbc, 0x4e, 0xa3, 0xd5, 0x22, 0xe4, 0x72, 0x94, 0x32, 0x21, 0x51, 0xc8, 0xd1,
	0x52, 0x85, 0x9c, 0xa9, 0x70, 0x8d, 0xa3, 0xc8, 0x67, 0xd1, 0x8c, 0x26, 0xd3, 0x62, 0xf0, 0x52,
	0x91, 0xa8, 0xc4, 0xed, 0x28, 0x8c, 0x30, 0x46, 0x25, 0xb6, 0x54, 0x25, 0x69, 0x46, 0xf6, 0xaf,
	0x6a, 0x00, 0xeb, 0x88, 0x71, 0x49, 0xb5, 0x9a, 0x0c, 0xa1, 0xaa, 0x91, 0x73, 0x66, 0xf5, 0x9e,
	0x0c, 0x6c, 0xff, 0xb9, 0x57, 0xbe, 0x99, 0x91, 0x46, 0xa1, 0x54, 0x81, 0xd1, 0xb8, 0xd7, 0x55,
	0x68, 0x16, 0x1c, 0x79, 0x05, 0x0d, 0x03, 0xc2, 0x99, 0xf3, 0xa6, 0x67, 0x0d, 0xda, 0x5f, 0x6a,
	0xff, 0x3f, 0x55, 0x9e, 0x5a, 0x41, 0x5d, 0xb3, 0xdf, 0x67, 0xe4, 0x3d, 0xd4, 0xa4, 0x62, 0x0a,
	0x75, 0xb4, 0x35, 0xb0, 0xfd, 0xde, 0xc9, 0x68, 0xcf, 0x68, 0xa8, 0xda, 0xa6, 0x18, 0x64, 0x7a,
	0xf2, 0x11, 0x1a, 0x31, 0xc6, 0x7f, 0x50, 0x48, 0xe7, 0x3c, 0xb3, 0xf6, 0x4f, 0x5b, 0x73, 0x55,
	0x66, 0xde, 0x79, 0xdc, 0x5f, 0x00, 0x65, 0x26, 0xe9, 0x96, 0x2d, 0xdf, 0xea, 0x96, 0x45, 0x3d,
	0x02, 0x55, 0xce, 0x62, 0x34, 0xdd, 0x9b, 0x81, 0x99, 0xc9, 0x0b, 0xa8, 0x6b, 0xeb, 0x4a, 0x3a,
	0xef, 0x0c, 0x9b, 0x23, 0xf7, 0xa6, 0x02, 0xad, 0xfd, 0xcf, 0xc8, 0x37, 0xa8, 0x67, 0x78, 0xb7,
	0x37, 0xef, 0xfe, 0x86, 0x39, 0xc8, 0x16, 0x9a, 0xdb, 0xdd, 0x8b, 0x0a, 0xd8, 0x7b, 0x3c, 0x59,
	0x40, 0x3b, 0xe4, 0x0a, 0xc5, 0x9c, 0x4d, 0x91, 0x0a, 0x9c, 0xef, 0x96, 0xf7, 0xf9, 0x61, 0xf9,
	0xde, 0x41, 0x48, 0xb6, 0xa0, 0x56, 0xc1, 0x05, 0x38, 0x77, 0x2f, 0x2d, 0x20, 0xc7, 0x22, 0x32,
	0xbd, 0x73, 0xb4, 0xf1, 0xa3, 0xff, 0x3d, 0x3e, 0xb0, 0x3b, 0x3c, 0xb8, 0xd0, 0x4b, 0x68, 0x16,
	0xae, 0xfc, 0x1a, 0x25, 0xf1, 0x61, 0x02, 0x9d, 0x25, 0x4f, 0x05, 0x2d, 0x6b, 0x50, 0xdc, 0x28,
	0xd2, 0xf5, 0x7e, 0xac, 0x78, 0x98, 0xa2, 0xf8, 0x89, 0xea, 0x5f, 0x22, 0xfe, 0xca, 0x09, 0x72,
	0x99, 0x08, 0xe9, 0xf8, 0xa6, 0xb6, 0xbd, 0x57, 0x3b, 0x78, 0xa6, 0x03, 0x7e, 0x6b, 0x3c, 0xf6,
	0x59, 0xf4, 0x75, 0xa3, 0x6e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x4e, 0x68, 0xa5, 0x4c, 0x03,
	0x00, 0x00,
}
