# Read current weather and forecasts data from openweathermap.org
[[inputs.openweathermap]]
  app_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  city_id = ["5391959"]
  units = "metric"

  ## Deprecated option, ignored due to the upstream API change
  query_style = "batch"
