// Code generated by "stringer -type=algorithm"; DO NOT EDIT.

package crypto

import "strconv"

const _algorithm_name = "scryptsha256scryptnfx11x13keccakx15nist5neoscryptlyra2rewhirlpoolxqubitquarkaxiomlyra2rev2scryptjanenf16blake256r8blake256r14blake256r8vnlhodlethashdecredcryptonightlbryequihashpascalx11gostsiablake2sskunkcryptonightv7"

var _algorithm_index = [...]uint8{0, 6, 12, 20, 23, 26, 32, 35, 40, 49, 56, 66, 71, 76, 81, 90, 104, 114, 125, 138, 142, 148, 154, 165, 169, 177, 183, 190, 193, 200, 205, 218}

func (i algorithm) String() string {
	if i < 0 || i >= algorithm(len(_algorithm_index)-1) {
		return "algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _algorithm_name[_algorithm_index[i]:_algorithm_index[i+1]]
}
