name: telegraf
adopt-info: telegraf
summary: Telegraf agent
description: |
  Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics
confinement: classic
grade: stable

apps:
  telegraf:
    command: 'bin/telegraf.wrapper'
    daemon: simple

parts:

  ## This wrapper will be called to start telegraf. It will import the default
  ## config file if none exists, and start telegraf
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      scripts/telegraf.snap_wrapper: bin/telegraf.wrapper
    stage:
      - etc
      - bin

  telegraf:
    build-attributes: [no-patchelf]
    plugin: nil
    build-snaps: [go]
    override-build: |
      cd ..
      export GOPATH=$(pwd)/go
      export GO111MODULE="off"
      mkdir -p $GOPATH
      go get -d github.com/influxdata/telegraf
      cd $GOPATH/src/github.com/influxdata/telegraf
      tag="$(git tag -l | egrep -v '\-rc' | sort -rV | head -n 1)"
      version="$(echo $tag | cut -d 'v' -f 2)"
      snapcraftctl set-version "$version"
      git checkout tags/$tag
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -p telegraf $SNAPCRAFT_PART_INSTALL/bin/
