name: telegraf
base: core18
adopt-info: telegraf
summary: Telegraf agent
description: |
  Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics
confinement: classic
grade: stable
passthrough:
  system-usernames:
    snap_daemon: shared

apps:
  telegraf:
    command: 'bin/telegraf.wrapper'
    daemon: simple

parts:
  ## This wrapper will be called to start telegraf. It will use setpriv to run
  ## as the snap_daemon user https://snapcraft.io/docs/system-usernames
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      scripts/telegraf.snap_wrapper: bin/telegraf.wrapper
    stage:
      - etc
      - bin

  telegraf:
    build-attributes: [no-patchelf]
    plugin: nil
    build-snaps: [go]
    build-packages: [make, gcc, git]
    stage-packages: [util-linux]
    override-build: |
      git clone https://github.com/influxdata/telegraf.git
      cd telegraf
      tag="$(git tag -l | egrep -v '\-rc' | sort -rV | head -n 1)"
      version="$(echo $tag | cut -d 'v' -f 2)"
      snapcraftctl set-version "$version"
      git checkout tags/$tag
      LDFLAGS='' make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -p telegraf $SNAPCRAFT_PART_INSTALL/bin/
