# Configuration for the Kafka server to send metrics to
[[outputs.kafka]]
  ## URLs of kafka brokers
  brokers = ["localhost:9092"]

  ## Kafka topic for producer messages
  topic = "telegraf"

  ## Optional TLS Config with both the deprecated and the new option set to
  ## the same value
  tls_ca = "../../testutil/pki/cacert.pem"
  tls_cert = "../../testutil/pki/clientcert.pem"
  tls_key = "../../testutil/pki/clientkey.pem"

  ## Data format to output.
  data_format = "influx"
