// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/parsers/jtinative/pfe_mpls_sr_egress_oc/pfe_mpls_sr_egress_oc.proto

package pfe_mpls_sr_egress_oc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "github.com/influxdata/telegraf/plugins/parsers/jtinative/telemetry_top"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MplsPfeMplsSrEgress struct {
	SignalingProtocols   *MplsPfeMplsSrEgressSignalingProtocolsType `protobuf:"bytes,151,opt,name=signaling_protocols,json=signalingProtocols" json:"signaling_protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *MplsPfeMplsSrEgress) Reset()         { *m = MplsPfeMplsSrEgress{} }
func (m *MplsPfeMplsSrEgress) String() string { return proto.CompactTextString(m) }
func (*MplsPfeMplsSrEgress) ProtoMessage()    {}
func (*MplsPfeMplsSrEgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0}
}
func (m *MplsPfeMplsSrEgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgress.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgress.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgress.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgress) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgress.Size(m)
}
func (m *MplsPfeMplsSrEgress) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgress.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgress proto.InternalMessageInfo

func (m *MplsPfeMplsSrEgress) GetSignalingProtocols() *MplsPfeMplsSrEgressSignalingProtocolsType {
	if m != nil {
		return m.SignalingProtocols
	}
	return nil
}

type MplsPfeMplsSrEgressSignalingProtocolsType struct {
	SegmentRouting       *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType `protobuf:"bytes,151,opt,name=segment_routing,json=segmentRouting" json:"segment_routing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *MplsPfeMplsSrEgressSignalingProtocolsType) Reset() {
	*m = MplsPfeMplsSrEgressSignalingProtocolsType{}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsType) String() string { return proto.CompactTextString(m) }
func (*MplsPfeMplsSrEgressSignalingProtocolsType) ProtoMessage()    {}
func (*MplsPfeMplsSrEgressSignalingProtocolsType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0, 0}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgressSignalingProtocolsType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsType) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType.Size(m)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsType) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsType proto.InternalMessageInfo

func (m *MplsPfeMplsSrEgressSignalingProtocolsType) GetSegmentRouting() *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType {
	if m != nil {
		return m.SegmentRouting
	}
	return nil
}

type MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType struct {
	Interfaces           *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType `protobuf:"bytes,151,opt,name=interfaces" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                   `json:"-"`
	XXX_unrecognized     []byte                                                                     `json:"-"`
	XXX_sizecache        int32                                                                      `json:"-"`
}

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) Reset() {
	*m = MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType{}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) String() string {
	return proto.CompactTextString(m)
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) ProtoMessage() {}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0, 0, 0}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType.Size(m)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType proto.InternalMessageInfo

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType) GetInterfaces() *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType struct {
	Interface            []*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList `protobuf:"bytes,151,rep,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                                  `json:"-"`
	XXX_unrecognized     []byte                                                                                    `json:"-"`
	XXX_sizecache        int32                                                                                     `json:"-"`
}

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) Reset() {
	*m = MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType{}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) String() string {
	return proto.CompactTextString(m)
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) ProtoMessage() {}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0, 0, 0, 0}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType.Size(m)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType proto.InternalMessageInfo

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType) GetInterface() []*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList {
	if m != nil {
		return m.Interface
	}
	return nil
}

type MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList struct {
	State                *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                                         `json:"-"`
	XXX_unrecognized     []byte                                                                                           `json:"-"`
	XXX_sizecache        int32                                                                                            `json:"-"`
}

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) Reset() {
	*m = MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList{}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) String() string {
	return proto.CompactTextString(m)
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) ProtoMessage() {
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0, 0, 0, 0, 0}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList.Size(m)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList proto.InternalMessageInfo

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList) GetState() *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType {
	if m != nil {
		return m.State
	}
	return nil
}

type MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) Reset() {
	*m = MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType{}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) String() string {
	return proto.CompactTextString(m)
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) ProtoMessage() {
}
func (*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) Descriptor() ([]byte, []int) {
	return fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c, []int{0, 0, 0, 0, 0, 0}
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType.Unmarshal(m, b)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType.Marshal(b, m, deterministic)
}
func (dst *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType.Merge(dst, src)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) XXX_Size() int {
	return xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType.Size(m)
}
func (m *MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType) XXX_DiscardUnknown() {
	xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType.DiscardUnknown(m)
}

var xxx_messageInfo_MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType proto.InternalMessageInfo

var E_JnprMplsPfeMplsSrEgressExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*MplsPfeMplsSrEgress)(nil),
	Field:         77,
	Name:          "jnpr_mpls_pfe_mpls_sr_egress_ext",
	Tag:           "bytes,77,opt,name=jnpr_mpls_pfe_mpls_sr_egress_ext,json=jnprMplsPfeMplsSrEgressExt",
	Filename:      "plugins/parsers/jtinative/pfe_mpls_sr_egress_oc/pfe_mpls_sr_egress_oc.proto",
}

func init() {
	proto.RegisterType((*MplsPfeMplsSrEgress)(nil), "mpls_pfe_mpls_sr_egress")
	proto.RegisterType((*MplsPfeMplsSrEgressSignalingProtocolsType)(nil), "mpls_pfe_mpls_sr_egress.signaling_protocols_type")
	proto.RegisterType((*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingType)(nil), "mpls_pfe_mpls_sr_egress.signaling_protocols_type.segment_routing_type")
	proto.RegisterType((*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesType)(nil), "mpls_pfe_mpls_sr_egress.signaling_protocols_type.segment_routing_type.interfaces_type")
	proto.RegisterType((*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceList)(nil), "mpls_pfe_mpls_sr_egress.signaling_protocols_type.segment_routing_type.interfaces_type.interface_list")
	proto.RegisterType((*MplsPfeMplsSrEgressSignalingProtocolsTypeSegmentRoutingTypeInterfacesTypeInterfaceListStateType)(nil), "mpls_pfe_mpls_sr_egress.signaling_protocols_type.segment_routing_type.interfaces_type.interface_list.state_type")
	proto.RegisterExtension(E_JnprMplsPfeMplsSrEgressExt)
}

func init() {
	proto.RegisterFile("plugins/parsers/jtinative/pfe_mpls_sr_egress_oc/pfe_mpls_sr_egress_oc.proto", fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c)
}

var fileDescriptor_pfe_mpls_sr_egress_oc_32cb0f574af04f7c = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0xd3, 0xcb, 0x65, 0x71, 0x0f, 0x37, 0x90, 0x14, 0x13, 0x9a, 0xae, 0x88, 0x2b, 0x56,
	0x25, 0xb2, 0x74, 0x8f, 0x0b, 0x0d, 0x86, 0x94, 0xc4, 0xed, 0xa4, 0x69, 0x0e, 0xcd, 0xe0, 0x30,
	0x33, 0x99, 0x73, 0x10, 0xd8, 0x9b, 0xf8, 0x08, 0xbe, 0x82, 0xef, 0xe1, 0x33, 0xf8, 0x06, 0xfa,
	0x1e, 0x86, 0x56, 0xa8, 0x22, 0x5d, 0x98, 0xa8, 0xab, 0xa6, 0xff, 0x3f, 0xff, 0xf9, 0xbf, 0x73,
	0xe0, 0xc2, 0xaa, 0x45, 0x26, 0x35, 0xf5, 0x6d, 0xe2, 0x08, 0x1d, 0xf5, 0x67, 0x2c, 0x75, 0xc2,
	0xf2, 0x06, 0xfb, 0x76, 0x8a, 0x62, 0x6e, 0x15, 0x09, 0x72, 0x02, 0x33, 0x87, 0x44, 0xc2, 0xa4,
	0x87, 0xd5, 0xc8, 0x3a, 0xc3, 0x26, 0x6c, 0x33, 0x2a, 0x9c, 0x23, 0xbb, 0xb5, 0x60, 0x63, 0x0b,
	0xf1, 0xf8, 0xa5, 0x0e, 0x9d, 0x3c, 0xf0, 0x39, 0xe9, 0xa7, 0xd0, 0x26, 0x99, 0xe9, 0x44, 0x49,
	0x9d, 0x89, 0xfc, 0x79, 0x6a, 0x14, 0x05, 0xf7, 0x5e, 0xd7, 0xeb, 0x35, 0x06, 0x27, 0x51, 0x45,
	0x2e, 0x3a, 0x10, 0x12, 0xbc, 0xb6, 0x18, 0xfb, 0x3b, 0x67, 0xbc, 0x35, 0xc2, 0xe7, 0xbf, 0x10,
	0x54, 0x05, 0x7c, 0x0b, 0x2d, 0xc2, 0x6c, 0x8e, 0x9a, 0x85, 0x33, 0x0b, 0x96, 0x3a, 0xdb, 0xb6,
	0x9f, 0x7d, 0xb9, 0x3d, 0xda, 0x9b, 0x54, 0x20, 0x35, 0xdf, 0xd4, 0xb8, 0x10, 0xc3, 0xa7, 0x1a,
	0x1c, 0x1d, 0x7a, 0xe8, 0x2f, 0x01, 0xa4, 0x66, 0x74, 0xd3, 0x24, 0xc5, 0xdd, 0x0d, 0xae, 0xbe,
	0x87, 0x22, 0x2a, 0x27, 0x17, 0x54, 0xef, 0xaa, 0xc2, 0xc7, 0x3f, 0xd0, 0xda, 0xf3, 0xfd, 0x5b,
	0x0f, 0xfe, 0xed, 0xb4, 0x0d, 0x4c, 0xad, 0xd7, 0x18, 0xe0, 0xcf, 0xc0, 0x94, 0xff, 0x42, 0x49,
	0xe2, 0xb8, 0x2c, 0x0e, 0x1f, 0x3c, 0x68, 0x7e, 0x74, 0xfd, 0x3b, 0x0f, 0xea, 0xc4, 0x09, 0xe3,
	0xf6, 0x44, 0xf6, 0x57, 0xa8, 0xa2, 0xbc, 0xb3, 0x38, 0x5e, 0xd1, 0x1f, 0xfe, 0x07, 0x28, 0xc5,
	0xd3, 0x25, 0x74, 0x67, 0xda, 0x3a, 0x51, 0x01, 0x23, 0x70, 0xc5, 0x7e, 0x27, 0x3a, 0x5f, 0x68,
	0x69, 0xd1, 0x5d, 0x22, 0x2f, 0x8d, 0xbb, 0xa6, 0x09, 0x6a, 0x32, 0x8e, 0x82, 0x51, 0xbe, 0x49,
	0x50, 0xb5, 0x49, 0x1c, 0x6e, 0x46, 0x8f, 0xac, 0xa2, 0xf1, 0x14, 0x37, 0x9f, 0x89, 0x1b, 0xe6,
	0xc6, 0x70, 0xc5, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x8e, 0x2d, 0x2f, 0xc3, 0x03, 0x00,
	0x00,
}
