# Parse the new lines appended to a file
[[inputs.tail]]
  files = ["/var/mymetrics.out"]

  ## The new option takes precedence over the deprecated one
  initial_read_offset = "end"

  data_format = "influx"
