on:
  pull_request:
    types: [opened]

jobs:
  cla-checker:
    runs-on: ubuntu-latest
    name: "Check CLA"
    steps:
      - name: "Lookup PR Author"
        uses: influxdata/clasee@v1
        with:
          spreadsheet: "1jnRZYSw83oa6hcEBb1lxK6nNvXrWnOzPT8Bz9iR4Q8s"
          range: "Form Responses!E:E"
        env:
          CLASEE_SECRET: ${{ secrets.CLASEE_SECRET }}
