name: Target Branch
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  check-target-master:
    name: master
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: echo "Target is ${BASE_REF}"
      - name: success
        if: github.event.pull_request.base.ref == 'master'
        run: exit 0
      - name: error
        if: github.event.pull_request.base.ref != 'master'
        run: |
          echo "Pull-request is not based on master, please rebase"
          exit 1
