# Collects performance metrics from OpenStack services
[[inputs.openstack]]
  ## The identity endpoint to authenticate against and get the service catalog from.
  authentication_endpoint = "https://my.openstack.cloud:5000"

  ## User authentication credentials. Must have admin rights.
  username = "admin"
  password = "password"

  ## Options for tags received from Openstack
  tag_value = "true"

  ## Server diagnostics explicitly disabled
