#!/bin/sh

# Create the needed user and group
if ! getent group telegraf &>/dev/null; then
    groupadd -r telegraf
fi
if ! id telegraf &>/dev/null; then
    useradd -r -M telegraf -s /bin/false -d $SNAP_DATA -g telegraf
fi

# Copy the config file, update permissions, and created telegraf.d
install -m 640 -o root -g telegraf $SNAP/etc/telegraf.conf $SNAP_DATA/telegraf.conf
mkdir -p $SNAP_DATA/telegraf.d
